atomvm/AtomVM

.gitignore
CMakeLists.txt
src/CMakeLists.txt
src/libAtomVM/CMakeLists.txt
src/platforms/generic_unix/CMakeLists.txt
tests/CMakeLists.txt

Broke out platform code into a shared library that is linked by AtomVM and test code and fixed CentOS6 build.  Also added a .gitignore file.
The changes in this PR are licensed under the terms of AtomVM (LGPL and/or Apache2).

Build improvement

---

src/libAtomVM/bif.c
src/libAtomVM/ccontext.h
src/libAtomVM/context.h
src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h
src/platforms/esp32/main/gpiodriver.c
src/platforms/esp32/main/networkdriver.c
src/platforms/esp32/main/udpdriver.c
src/platforms/generic_unix/udpdriver.c

This PR refactors the definition and use of the `term_from_atom_string` function.
* Factored `term_from_atom_string` into a common inline static function in the context module (`context_from_atom_string`), and changed call points.
* Removed multiple instances of static inline definitions of `term_from_atom_string` 
* Changed the input type to Context * (from GlobalContext *)
* Fixed up `ccontext.h` module for inclusion later to include a typedef and static inline declarations
These changes are being submitted under the terms of the LGPLv2 and Apache2 licenses.

Refactor term_from_atom_string

---

src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h

Fixed clang warnings around format strings and GCC #pragmas.
These are insignificant changes that should only affect builds using the clang compiler.
These changes are licensed under the terms of the LGPLv2 and Apache2 licenses.

Fixed clang warnings around format strings and GCC #pragmas

---

src/libAtomVM/avmpack.c
src/libAtomVM/avmpack.h
tools/packbeam/CMakeLists.txt
tools/packbeam/README.md
tools/packbeam/packbeam.c

This change set makes several small improvements to the PackBeam tool.
* Adds help via the -h flag, which displays a summary of options
* Add a list option via the -l flag, to list the contents (modules) of an AVM file
* Adds a README with documentation and an example.
Future enhancements can include generation of a PackBeam file using the contents of other PackBeam "library" files.

PackBeam enhancements

---

tools/packbeam/README.md
tools/packbeam/packbeam.c

This change set modifies the PackBeam executable to support previously created AVM files as inputs.  This allows the creation of AVM "archives", or "libraries", which can be built independently of an application (e.g., estdlib), and which can then be assembled into an AVM that can be flashed to a device or run from the command line.
These changes are backwards compatible with previous uses of PackBeam.
These changes are submitted under the terms of the LGPLv2 and Apache2 licenses.

Add support for PackBeam to take AVM files as input.

---

CMakeLists.txt
CMakeModules/BuildErlang.cmake
README.ESP32.Md
README.Md
examples/CMakeLists.txt
examples/erlang/CMakeLists.txt
examples/erlang/esp32/CMakeLists.txt
examples/erlang/esp32/blink.erl
examples/erlang/hello_world.erl
libs/CMakeLists.txt
libs/eavmlib/CMakeLists.txt
libs/estdlib/CMakeLists.txt
src/libAtomVM/avmpack.c
src/libAtomVM/avmpack.h
tools/packbeam/packbeam.c

This change set adds CMake rules for building AVM files for libraries and examples.
In addition, a bug in the PackBEAM executable is fixed, which fixes an issue with packing previously packed AVM files.
As part of this fix, the avmpack_fold fold function signature was changed, to supply accurate section addresses.  The API documentation was clarified and corrected.
These changes are submitted under the terms of the LGPLv2 and Apache2 licenses.

Adds support for building Erlang libraries and examples

---

src/platforms/esp32/main/gpiodriver.c
src/platforms/esp32/main/networkdriver.c

Avoid interpreting "\x5error" as "\x5e" "rror" and so on

Consistently split all the atoms from their lengths

---

src/libAtomVM/port.c
src/libAtomVM/port.h
src/libAtomVM/socket.c
src/platforms/generic_unix/socket_driver.c

This change ensures there is adequate room in the process heap to store enough data received on a UDP packet.
This change imposes an artificial limitation of 128 bytes on a received packet.  We will revisit this limitation in the future.
This change also fixes a potential memory corruption issue when copying an erlang reference to the event listener for the receive operation.

Ensure adequate memory on UDP receive.

---

libs/estdlib/console.erl
src/libAtomVM/nifs.c
src/libAtomVM/port.c
src/libAtomVM/port.h
tests/erlang_tests/hello_world.erl

This change adds selective receive when sending messages to the console port, using a reference to tag the request.  This way, the calling application can be assured that the request it made was serviced by the port.
This change also adds a flush operation to the console port, to flush any messages buffered by the standard library or OS.
Corresponding changes are made to the console erlang application.

Add selective receive to the console port.

---

src/libAtomVM/socket.c

This change puts the CContext object in the socket port on the stack, instead of on the heap, in conformance with the rest of the ports.
This change is made under the terms of the LGPLv2 and Apache2 licenses.

Place CContext on stack instead of heap.

---

examples/erlang/esp32/CMakeLists.txt
examples/erlang/esp32/setup_network.erl
libs/eavmlib/network.erl
src/libAtomVM/CMakeLists.txt
src/libAtomVM/network.c
src/libAtomVM/network.h
src/libAtomVM/network_driver.h
src/platforms/esp32/main/network_driver.c
src/platforms/esp32/main/sys.c
src/platforms/generic_unix/sys.c

This change set makes an initial set of improvements to the network port driver, including:
* Factored out common parts of the port driver code (the parts that interface directly with AtomVM i/o parameters) into a common set of functions in the libAtomVM module, similar to patterns used in the socket and console drivers;
* Modified the protocol between AtomVM and the network driver to use a reference, to support selective receive;
* Added a setup_network example.
This is part of a multi-phase change to this driver.  Subsequent changes will include a re-design of the network interface, to allow applications to respond to events in the Wifi driver, such as connect, disconnect, and IP acquisition events, as well as acquisition of netwrk information (e.g., ifconfig) and documentation as the …

Phase I changes to the network port driver.

---

src/libAtomVM/globalcontext.c
src/libAtomVM/globalcontext.h
src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h
src/platforms/generic_unix/mapped_file.c
src/platforms/generic_unix/sys.c
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_apply.erl
tests/test.c

This PR adds support for the apply/1 opcode (#112), which supports Module:Function(...) calls.
An additional common function is added to the global_context module to simplify the retrieval of AtomStrings from term objects, and some code paths were cleaned up to allow for the possibility of loading code that does not exist (user error).  A unit test is added for exported module and NIF use cases, as well as for error conditions.

Add support for apply/1 (#112) opcode.

---

src/libAtomVM/avmpack.c
src/libAtomVM/nifs.c
src/platforms/esp32/main/sys.c
src/platforms/generic_unix/sys.c
tools/dev/clean-whitespace.sh
tools/packbeam/packbeam.c

This commit adds a script for cleaning source modules so that there are no modules with trailing whitespace and so that files end in the newline character appropriate for the platform.
In addition, whitespace fixes to existing source modules are made.

Added script for cleaning whitespace in source modules.

---

.travis.yml
CMakeModules/BuildErlang.cmake
examples/erlang/CMakeLists.txt
examples/erlang/server.erl
libs/eavmlib/CMakeLists.txt
libs/eavmlib/console.erl
libs/eavmlib/logger.erl
libs/estdlib/CMakeLists.txt
libs/estdlib/gen_server.erl
libs/estdlib/proplists.erl
libs/etest/etest.erl
libs/include/logger.hrl
tests/CMakeLists.txt
tests/libs/eavmlib/CMakeLists.txt
tests/libs/eavmlib/test_logger.erl
tests/libs/eavmlib/tests.erl
tests/libs/estdlib/CMakeLists.txt
tests/libs/estdlib/test_gen_server.erl
tests/libs/estdlib/test_lists.erl
tests/libs/estdlib/test_proplists.erl
tests/libs/estdlib/tests.erl

This change set adds a gen_server module, as well as a few additional support modules.
Changes include the following:
* Added a gen_server module
* Added a logger module, for enhanced debugging/tracing of code
* Added a proplists module (currently only supports get_value/2,3)
* Added member/2 function to lists module
* Moved the console module to eavmlib
* Added tests for the same
* In order to prevent compilation errors with some erlang modules, each estdlib module must be built in its own directory, so CMakelists erlang rules had to change to accomodate that.
* Added travis rules for running erlang tests

Adds a gen_server module and other enhancements.

---

src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_apply_last.erl
tests/test.c

This is a followup to the addition of support for the apply instruction, adding support for the related apply_last opcode.

Add support for apply_last opcode

---

src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_set_tuple_element.erl
tests/test.c

This change adds support for the set_tuple_element (67) opcode.

Add support for the set_tuple_element opcode.

---

examples/erlang/code_lock.erl
examples/erlang/server.erl
examples/erlang/udp_client.erl
examples/erlang/udp_server.erl
libs/eavmlib/logger.erl
libs/eavmlib/timer_manager.erl
libs/estdlib/CMakeLists.txt
libs/estdlib/avm_calendar.erl
libs/estdlib/avm_gen_server.erl
libs/estdlib/avm_gen_statem.erl
libs/estdlib/avm_gen_udp.erl
libs/estdlib/avm_lists.erl
libs/estdlib/avm_proplists.erl
libs/estdlib/avm_timer.erl
libs/include/estdlib.hrl
tests/libs/estdlib/test_gen_server.erl
tests/libs/estdlib/test_gen_statem.erl
tests/libs/estdlib/test_lists.erl
tests/libs/estdlib/test_proplists.erl
tests/libs/estdlib/test_timer.erl

This change set changes the names of the estdlib library to use names that are not the same
as their OTP equivalents.  All modules in this library are prefixed with 'avm_'.  For
convenience, macros are provided that can be used to insulate the user from these names.
In addition, a few bug fixes and enhancements were made to the logger and avm_lists modules.
This change is made under the terms of the LGPLv2 and Apache2 licenses.

Change the names of modules in the estdlib library.

---

libs/eavmlib/logger.erl
libs/estdlib/avm_lists.erl
src/libAtomVM/opcodesswitch.h
tests/libs/estdlib/test_lists.erl
tools/packbeam/packbeam.c

This change set fixes support for funs in AVM (packed beam) files.  In addition, it fixes some minor issues with calling funs defined in other modules, and add functions and tests in the avm_lists module for using funs.

Fix support for funs in AVM files

---

src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_make_list.erl
tests/test.c

This change set moves the allocation of a list element in the OP_PUT_LIST handling code after the decoding of terms, which may trigger the garbage collector, and could otherwise invalidate the allocated list element in the heap.

Fixed OP_PUT_LIST opcode

---

libs/estdlib/avm_gen_server.erl

This change only fixes minor typos for the current gen_server impl.

Correct minor typos for gen_server

---

src/libAtomVM/ccontext.h
src/libAtomVM/externalterm.c
src/libAtomVM/nifs.c
src/libAtomVM/port.c

The console port does not ensure adequate memory to run, with the new memlimit change.  This change ensures sufficient memory to run console process messages.
This change is made under the terms of the LGPLv2 and Apache2 licenses.

Fix for memory allocation failure in console port.

---

src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_list_processes.erl
tests/test.c

This change set adds support for the erlang:prcoesses/0 NIF.

Add support for erlang:processes/0

---

src/libAtomVM/context.c
src/libAtomVM/context.h
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_process_info.erl
tests/test.c

This change set adds support for process_info/2, where the first argument is a Pid, and the second argument is an atom.
The following statistics are available by specifying the following atoms as the second argument:
* heap_size: size in words of the heap of the process
* stack_size: stack size, in words, of the process
* message_queue_len: number of messages currently in the message queue of the process
* memory: size in bytes of the process. This includes call stack, heap, and internal structures.
The value returned is a tuple with the supplied atom as the first element and the integer value as the second element

Add support for process_info/2

---

src/libAtomVM/term.c

This change makes printing of binaries more similar to OTP.

Improve the printing of binaries with non-printable characters.

---

src/libAtomVM/socket.c
src/libAtomVM/term.h
src/platforms/generic_unix/socket_driver.c

The calculation of the boxed size of a binary is off by 1, which causes the binary to not be properly (shallow) copied during GC and in message passing.
Also modified socket to use binaries and calculate correct heap size.
This fix is made under the terms of the LGPLv2 and Apache2 licenses.

Fixed calculation of boxed size of binaries.

---

src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/spawn_fun1.erl
tests/erlang_tests/spawn_fun2.erl
tests/erlang_tests/spawn_fun3.erl
tests/test.c

This makes it possible to spawn a process using a fun.

Add support for spawn/1 and spawn_opt/2

---

src/libAtomVM/opcodesswitch.h
src/libAtomVM/scheduler.c
src/libAtomVM/sys.h
src/platforms/esp32/main/sys.c
src/platforms/generic_unix/sys.c

In some cases it is nice to be able to debug on UNIX using select for checking the status of file descriptors (e.g., sockets).  This change adds support for select, with the addition of a compile time macro (defaults to using poll, for efficiency).  Select added to ESP32 port.
Also fixes two bugs:
* If the handler on an EventListener removes a listener from the global list of listeners, this has a side effect on the global->listeners pointer, so the check to exit the loop calling handlers may need to have the listeners value updated.  Without this change, we can end up in an infinite loop in some cases.
* Added the stdout to the calls to term_display that had been hidden in the ADAVANCED_TRACING macro.
and …

Adds support for select (for debugging only)

---

src/libAtomVM/network.c
src/libAtomVM/network_driver.h
src/libAtomVM/nifs.c
src/libAtomVM/port.c
src/libAtomVM/port.h
src/libAtomVM/socket.c
src/libAtomVM/socket.h
src/libAtomVM/socket_driver.h
src/platforms/esp32/main/network_driver.c
src/platforms/esp32/main/socket_driver.c
src/platforms/generic_unix/network_driver.c
src/platforms/generic_unix/socket_driver.c

This change set makes a broad set of changes across the network and socket drivers, replacing uses of CContext with the more simple Context structure.
The use of CContext in this code adds unnecessary complexity to the code, while proving no tangible benefit.  All of the gains are via preventing the GC from running inside the execution context of the port.

Remove use of CContext in port drivers.

---

src/libAtomVM/network.c
src/libAtomVM/nifs.c
src/libAtomVM/port.c
src/libAtomVM/port.h
src/libAtomVM/socket.c
src/platforms/esp32/main/network_driver.c
src/platforms/esp32/main/socket_driver.c
src/platforms/generic_unix/network_driver.c
src/platforms/generic_unix/socket_driver.c

This changeset fixes messages of the form {error, Reason} returned from port drivers, so that atoms or tuples are bound to the Reason in an error tuple, instead of arbitrary strings.  Doing this prevents potential crashes due to dynamic memory allocation in port drivers..

Replaces error strings with terms

---

src/platforms/generic_unix/socket_driver.c
src/platforms/generic_unix/sys.c

This change set fixes the UDP Socket server code, so that:
1. The correct estimated heap size is calculated
2. The in-flight update to listeners checks against the possibility of a NULL value after the update

Fix UDP Socket server

---

src/platforms/esp32/main/socket_driver.c

commented out unused static var declarations (bind_a, getsockname_a,  recvfrom_a) because otherwise it won't be comilable using esp-idf 3.2 which defines -Werror=unused-const-variable - i did not delete because i feel there is missing some code which should use these vars.

Update socket_driver.c in order to make it compilable

---

src/platforms/stm32/src/lib/sys.c

stm32: adapt sys_waitevents to new signature

---

doc/atomvm-examples.md
examples/erlang/esp32/CMakeLists.txt
examples/erlang/esp32/udp_server_blink.erl
examples/erlang/udp_client.erl
src/platforms/esp32/main/socket_driver.c

This change set adds support for UDP service on the ESP32 platform.  An example program is provided to illustrate starting a UDP server after obtaining and IP address, and sending UDP messages to the device.
This change set includes documentation for AtomVM examples.

Add support for UDP server on ESP32 platform.

---

tests/libs/eavmlib/test_logger.erl

The AVM logger module is by design asynchronous.  This change adds a sleep to the retrieval of the counted logs to wait for the logger sink to be invoked, and hence the counter to be updated.

Workaround for race condition in logger test failure.

---

libs/estdlib/avm_inet.erl
src/libAtomVM/socket.c
src/libAtomVM/socket_driver.h
src/platforms/esp32/main/socket_driver.c
src/platforms/generic_unix/socket_driver.c
src/platforms/generic_unix/sys.c
tests/libs/estdlib/CMakeLists.txt
tests/libs/estdlib/test_gen_udp.erl
tests/libs/estdlib/tests.erl
tools/dev/clean-whitespace.sh

Add test for gen_udp, fixed close functionality, and added ability to get the actual port number, if a port is dynamically assigend.  
Also fixed a bug in generic_unix sys_waitevents, so that poll_fd_index is incremented only if the event listener has a file descriptor.  Otherwise, we run the risk of passing the wrong count into poll, which can SEGV.

gen_udp test and fixes

---

libs/estdlib/avm_proplists.erl

Remove is_atom(Key) guard when looking up for {K, V} tuples.

proplists: Key is not required to be an atom when using tuples

---

src/libAtomVM/nifs.c

Fixes some code that is untouched unless advanced tracing is turned on.

Fix advanced trace

---

src/libAtomVM/iff.c
src/libAtomVM/iff.h
src/libAtomVM/module.c
src/libAtomVM/module.h
tools/packbeam/packbeam.c

This PR adds support for parsing out string tables in BEAM files, and for including them in packed BEAM files.

Add support for string tables in beam files

---

examples/erlang/esp32/tcp_server_blink.erl
examples/erlang/esp32/udp_server_blink.erl
examples/erlang/tcp_server.erl
examples/erlang/udp_server.erl
libs/estdlib/avm_gen_tcp.erl
libs/estdlib/avm_gen_udp.erl
libs/estdlib/avm_inet.erl
src/libAtomVM/socket.c
src/libAtomVM/socket_driver.h
src/platforms/esp32/main/socket_driver.c
src/platforms/generic_unix/socket_driver.c

Also added ability to specify address on which to bind (for UDP and TCP services).  By not specifying an address (default), application will bind to any (0.0.0.0) interface.
sockname and peername are used to retrieve the address and port of local and remote endpoints of connected sockets.

Added support for avm_inet:sockname/1 and avm_inet:peername/1.

---

libs/eavmlib/logger.erl
libs/eavmlib/network_fsm.erl
libs/eavmlib/timer_manager.erl
libs/estdlib/avm_gen_server.erl
libs/estdlib/avm_gen_statem.erl
libs/include/logger.hrl
tests/libs/eavmlib/test_logger.erl

This change set makes some improvements to the avmlib logger interface, mostly to support formatted logging when using the logging macros.  The macro arity has changed to 2, to allow specification of a format string and argument list.
Because the interface has changed, the uses of the LOG_DEBUG macro have been removed from modules in the estdlib library.
The longer interface also now supported multiple sinks, so that logs can be directed to more than one output channel.  In the future, we can add sinks for protocols like syslog or mqtt.

Added support for formatted logging in logger interface.

---

README.Md

Probably just an obvious documentation change but I installed all the dependencies from the `README` and didn't get a build because you also need to have an Erlang compiler (or I'm really dumb and missed something).

Document requirement for an Erlang compiler.

---

libs/eavmlib/CMakeLists.txt
libs/estdlib/CMakeLists.txt
libs/etest/CMakeLists.txt
libs/exavmlib/CMakeLists.txt
src/libAtomVM/CMakeLists.txt

CMake: fix `make install` for out-of-tree builds

---

examples/elixir/stm32/MultiBlink.ex
examples/erlang/esp32/blink.erl
examples/erlang/esp32/morse_server.erl
examples/erlang/esp32/sht31.erl
examples/erlang/esp32/sx127x.erl
libs/estdlib/CMakeLists.txt
libs/estdlib/calendar.erl
libs/estdlib/gen_server.erl
libs/estdlib/gen_statem.erl
libs/estdlib/gen_tcp.erl
libs/estdlib/gen_udp.erl
libs/estdlib/inet.erl
libs/estdlib/io.erl
libs/estdlib/io_lib.erl
libs/estdlib/lists.erl
libs/estdlib/proplists.erl
libs/estdlib/string.erl
libs/estdlib/timer.erl
libs/exavmlib/Access.ex
libs/exavmlib/Enum.ex
libs/exavmlib/Keyword.ex
libs/exavmlib/List.ex
libs/include/estdlib.hrl

Removed avm_ prefix from erlang estdlib modules

---

libs/estdlib/src/inet.erl
src/platforms/esp32/main/socket_driver.c
src/platforms/generic_unix/socket_driver.c

The return signature on these functions were not in compliance with the OTP implementation.  This has been fixed.
Also converted stray printfs to TRACE in esp32 socket driver

Fixes to inet:sockname/1 and inet:peername/1

---

libs/eavmlib/src/console.erl
libs/eavmlib/src/logger.erl
libs/estdlib/src/io.erl
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf

This change set makes printing to the console more immediate and more efficient, as no message passing is required.

Added console:print/1 NIF, now used by logger

---

libs/eavmlib/src/avm_pubsub.erl

Add a PubSub server that can be useful in projects dealing with sensors.
Example:
```erlang
avm_pubsub:start(pubsub)
avm_pubsub:sub(pubsub, [sensors, :"#"])
avm_pubsub:pub(pubsub, [sensors, 42], 0)
avm_pubsub:pub(pubsub, [sensors, 42], 1)
avm_pubsub:pub(pubsub, [sensors, 42], 2)
avm_pubsub:unsub(pubsub, [sensors, :"#"])
avm_pubsub:pub(pubsub, [sensors, 42], 3)
```

Add AtomVM PubSub server

---

src/libAtomVM/module.c
src/platforms/esp32/main/main.c

These changes should make malformed BEAM or AVM files easier to diagnose.

Improved error handling when startup beam cannot be loaded.

---

doc/atomvm-esp32.md
src/platforms/esp32/main/component_nifs.py

I realized the extra "_nifs_" string in the component nif get function was extraneous.  Best to fix it now, before it gets any real use.

Name change for component_nifs script

---

src/libAtomVM/context.c
src/libAtomVM/context.h
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_selective_receive.erl
tests/test.c

Support for out-of-order messages in selective receive blocks.

---

src/libAtomVM/bif.c
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_bitshift.erl
tests/test.c

Adds support for shift operations on large (boxed) integers.

Support shift left/right on integers > 27 bits

---

src/libAtomVM/memory.c
src/libAtomVM/memory.h
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_gc.erl
tests/test.c

Useful function for debugging, and will be required in obscure edge cases with reference-counted binaries.

Added erlang:garbage_collect/1,2

---

doc/atomvm-memory.md
src/libAtomVM/externalterm.c
src/libAtomVM/memory.c
src/libAtomVM/opcodes.h
src/libAtomVM/opcodesswitch.h
src/libAtomVM/term.c
src/libAtomVM/term.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_map.erl
tests/test.c

This change set adds support for the opcodes needed to support map syntax only.  Additional work is needed to support map bifs and the OTP `map` module.

Added support for maps opcodes.

---

.travis.yml
libs/estdlib/src/CMakeLists.txt
libs/estdlib/src/erlang.erl
libs/estdlib/src/maps.erl
libs/etest/src/etest.erl
libs/include/etest.hrl
src/libAtomVM/bif.c
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/test_map.erl
tests/libs/estdlib/CMakeLists.txt
tests/libs/estdlib/test_maps.erl
tests/libs/estdlib/tests.erl

Adds support for `maps`.
Also adds code TODO comments and documentation to previously added map BIFs, and tightens up test framework a little.

Added support for a subset of the functionality of the Erlang/OTP maps module

---

src/libAtomVM/list.h

It was actually returning the first item instead of the last
Signed-off-by: Riccardo Binetti <rbino@gmx.com>

list.h: fix list_last function

---

libs/estdlib/src/io_lib.erl
src/libAtomVM/interop.c
src/libAtomVM/interop.h
tests/libs/estdlib/test_io_lib.erl

Added support for maps to io_lib and added a useful C function (used by third-party ports) for searching for map entries.

Maps fixes

---

src/main.c

This change sets the module name of the startup BEAM to the basename of the file path, instead of the full path.  This allows users to use full paths to BEAM files reliably.  (Without this change, module lookups fail when BEAM files are specified on the command line that use paths specifiers.

Fix startup beam path

---

doc/atomvm-esp32.md
src/platforms/esp32/mkimage.config
src/platforms/esp32/partitions.csv
tools/release/esp32/flashimage.sh
tools/release/esp32/mkimage.erl

Increased the size of the AtomVM image partition (factory) to 1.75mb, and decreased the size of the AtomVM library partition (data) to 256k.  No user-interface changes.
This change makes room for VM images that are bigger than 1MB.  The current AtomVM library is just under 50k, so a 256k partition should be ample room for core libraries to grow fivefold.

Expand VM image partition (esp32)

---

src/libAtomVM/opcodesswitch.h
tests/erlang_tests/test_bs.erl

…when the type being matched is not a binary but some other type.
Instead of raising an exception, we now switch to the fail label, as directed by the instruction.

Fixed an issue with matching binaries in case clauses

---

doc/atomvm-memory.md
src/libAtomVM/memory.c
src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h
src/libAtomVM/term.c
src/libAtomVM/term.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_sub_binaries.erl
tests/test.c

This change set adds support for sub-binaries, which can significantly reduce the amount of heap space used when processing large binaries.
Sub-binaries are sub-sets of reference counted binaries that are sufficiently large (> 8 bytes).  Sub-binaries are created via the `binary:part/3` function, `binary:split/2` function, and the `/binary` bit syntax modifier.

Added support for sub-binaries.

---

libs/eavmlib/src/CMakeLists.txt
libs/eavmlib/src/port.erl
libs/eavmlib/src/spi.erl
src/platforms/esp32/main/spi_driver.c

This change prevents client calls to the driver from consuming messages not in reply to a request to the driver.

Calls to SPI driver use selective receive

---

libs/eavmlib/src/i2c.erl
src/platforms/esp32/main/i2c_driver.c

This change prevents client calls to the driver from consuming messages not in reply to a request to the driver.

Calls to I2C driver use selective receive

---

libs/eavmlib/src/i2c.erl
src/platforms/esp32/main/i2c_driver.c

Added itc:write_bytes/2 for writing bytes between begin/end transmission calls.
The implementation of this function makes use of the IDF SDK `i2c_master_write` function, which can be useful for queueing up writes from binary data to the I2C device.

Added i2c:write_bytes/2

---

libs/eavmlib/src/gpio.erl
src/platforms/esp32/main/gpio_driver.c

This change prevents client calls to the driver from consuming messages not in reply to a request to the driver.

Calls to GPIO driver use selective receive.

---

libs/estdlib/src/timer.erl
src/libAtomVM/opcodesswitch.h
tests/libs/estdlib/test_timer.erl

... so that arbitrary messages don't interrupt the timer.

Fixed timer to use selective receive

---

src/libAtomVM/externalterm.c
src/libAtomVM/term.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/boxedlit.erl
tests/test.c

... so that they can be parsed into boxed terms, if they are sufficiently large.

Fixed parsing of 32-bit literals

---

src/libAtomVM/externalterm.c
src/libAtomVM/module.c
tests/erlang_tests/test_binary_to_term.erl

This change removes explicit aborts when passing invalid encoded term.  Without this fix, binary_to_term when passed a binary that is not a valid encoded term will abort the process/VM.  
The abort handling is moved out to the module interface, where external term literals are loaded, so the behavior is unchanged in that case.

Fix for binary_to_term with invalid term encoding

---

src/platforms/esp32/main/sys.c

esp32_largest_free_block returns the largest free unfragmented block in the heap.
esp32_minimum_free_size returns the lowest free blocks of heap since boot.

Adds two new memory atoms to erlang:system_info/1

---

src/platforms/esp32/main/sys.c

Adding a 1-tick delay will allow the task to periodically yield when the scheduler pre-empts a running process (every 1024 reductions).

Add a 1 tick delay in sys_consume_pending_events on ESP32 platform.

---

src/libAtomVM/opcodesswitch.h
tests/erlang_tests/test_bs.erl

The change resets the reference to the bs_bin match_state binary, after a potential GC.  Without this change, the reference to the match state binary passed into the sub-binary constructor may be invalid.

Fix memory corruption when taking the tail of a binary.

---

libs/estdlib/src/gen_tcp.erl
src/platforms/esp32/main/network_driver.c
src/platforms/esp32/main/socket_driver.c
src/platforms/esp32/main/socket_driver.h
src/platforms/generic_unix/socket_driver.c
tests/libs/estdlib/CMakeLists.txt
tests/libs/estdlib/test_gen_tcp.erl
tests/libs/estdlib/tests.erl

This change set makes the following fixes to the generic_unix and esp32 socket drivers:
* Fixed a pid leak in both drivers, so that the sockets are properly closed and processes and memory deleted when a socket is closed.
* Fixed an error in the ESP32 driver that prevented multiple listening sockets to initialize properly.
* Cleaned up interdependencies between socket and network code that should not be there. 
* Properly passed off the binary and active flags to from listening socket to accepting socket.
* Set the listening sockets to reuse address and disabled linger
* Added `localhost` atom as a valid address when initializing a socket
* Added a simple test for gen_tcp
These changes are made under both the "Apache 2.0" and the "GNU Lesser …

Socket fixes

---

src/libAtomVM/opcodes.h
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_catch.erl
tests/test.c

Adds support for `catch` and `catch_end` BEAM opcodes.

---

src/platforms/generic_unix/socket_driver.c

Fix FreeBSD compilation error

---

src/libAtomVM/term.h

There is a small typo in src/libAtomVM/term.h.
Should read `uninitialized` rather than `unitialized`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, unitialized -> uninitialized

---

src/libAtomVM/bitstring.c
src/libAtomVM/bitstring.h
src/libAtomVM/opcodesswitch.h
src/libAtomVM/term.h
src/libAtomVM/utils.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_bs.erl
tests/erlang_tests/test_bs_int.erl
tests/test.c

This PR adds support for little endian and signed put operations (8, 16, and 32-bit) on integers in bit syntax.  These changes bring put operations in parity with get/match operations.
Changes include:
* Modified the OP_BS_PUT_INTEGER opcode implementation to support little-endian and signed puts for 8, 16, and 32-bit integers
* Added macros to bitstring.h to support 16 and 32-bit little endian puts
* Added `bitstring_insert_any_integer` function to bustling module for writing 8, 16, and 32-bit signed and little-endian integers -- moved old function from term.h to bustling module.
* Renamed exported `extract_any_integer` to use C-naming convention (use `bitstring_` prefix)
* Added a test to exercise combinations of bit syntax integer operations, and modified `test_bs` test module to …

Added support for little endian and signed put operations on integers

---

doc/src/programmers-guide.md
libs/estdlib/src/erlang.erl

Adds documentation for esp_largest_free_block and esp_get_minimum_free_size erlang:system_info/1 keys.

documentation for erlang:system_info memory keys

---

.github/workflows/esp-idf-v3.3.6-dockerfile
.github/workflows/esp-idf-v4.1.2-dockerfile
.github/workflows/esp-idf-v4.2.3-dockerfile
.github/workflows/esp32-build.yaml

Creates a build matrix that includes Espressif supported version 4.1.2 and 4.2.3
of ESP-IDF and updates 3.x tests to the final release version 3.3.6 of the 3.x
series.

ESP32 build matrix for supported IDF versions

---

.github/workflows/esp32-build.yaml

I accidentally pushed the wrong branch that had spaces in the job name that
cause a failure due to the yaml syntax.

Fix for bad job name id in IDF build matrix

---

CHANGELOG.md
doc/src/programmers-guide.md
libs/eavmlib/src/spi.erl
src/platforms/esp32/main/spi_driver.c

Added support for spi:close/1

---

README.Md

Specify at the top that erlc should be from OTP 21, 22 or 23
Specify cmake define option to disable FP for OTP 22 or 23
Specify at the top that elixirc is also required
Specify how to run tests

Complete build instructions for users with OTP 22 or 23

---

libs/CMakeLists.txt

This adds alisp to the list of library beams to be packed into atomvmlib.avm
Closes isssue #288.

Fix alisp beams missing from atomvmlib.avm

---

CHANGELOG.md
libs/eavmlib/src/timer_manager.erl
libs/estdlib/src/erlang.erl
libs/estdlib/src/gen_statem.erl
tests/libs/eavmlib/test_timer_manager.erl
tests/libs/estdlib/test_gen_statem.erl

This PR fixes the timeout logic in the gen_statem module, by cancelling any timers that have been set on the state machine, if the gen_statem implementation transitions out of the state in which the timer was set. Test added. This PR also simplifies the timeout calculation in the timer manager to use erlang:system_time/1.
Closes #303.

Corrected state timeout logic in gen_statem

---

src/libAtomVM/CMakeLists.txt
src/platforms/esp32/components/libatomvm/component.mk
src/platforms/esp32/main/component.mk

Prevents incorrect version information in mixed build environments.

Move the generated version.h into the build directory

---

CHANGELOG.md
src/libAtomVM/atom.h
src/libAtomVM/context.h
src/libAtomVM/globalcontext.c
src/libAtomVM/globalcontext.h
src/libAtomVM/interop.c
src/libAtomVM/interop.h

This PR aims to address 2 different issues:
- Atoms table gets quickly cluttered with rarely used atoms due to comparisons
- Comparing a term with an atom string is a boring task, that requires a lot of boilerplate.

Add efficient atom comparison helpers

---

CHANGELOG.md
src/platforms/esp32/main/esp32_sys.h
src/platforms/esp32/main/main.c
src/platforms/esp32/main/platform_nifs.c
src/platforms/esp32/main/sys.c

Insead of having a list of available port drivers, which gets converted
into a C source file at build time, rely on the newly introduced
`REGISTER_PORT_DRIVER` macro.
This new mechanism doesn't rely on any additional script or build system
feature, but it just make use of `constructor` gcc attribute, which
allows defining a number of functions that are called at startup time.
How to use this new feature:
Just add to your port driver main source file:
```c
REGISTER_PORT_DRIVER(my_port, my_port_driver_init, my_port_driver_create_port)
```
It is also required to add some additional linker flags to `component.mk`:
```
CFLAGS += -fno-function-sections -fno-data-sections
COMPONENT_ADD_LDFLAGS = -Wl,--whole-archive -l$(COMPONENT_NAME) -Wl,--no-whole-archive
```
Same approach has been implemented …

ESP32: allow adding new port drivers without editing any source file

---

CHANGELOG.md
doc/src/programmers-guide.md
src/platforms/esp32/main/sys.c

This PR changes the esp32_chip_info structure returned from erlang:system_info to a map which includes the chip model, as well as to return the features as a list of atoms.
WARNING: This is a source-incompatible change, as it changes the structure of a term returned from erlang:system_info.
This PR resolves issue #318 

Changed the esp32_chip_info structure

---

CHANGELOG.md
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/bs_append_extra_words.erl

Fix bs_append bug.
See also #322 

Fix bs_append extra zeroes bug

---

CHANGELOG.md
libs/estdlib/src/gen_tcp.erl
src/platforms/esp32/main/socket_driver.c
src/platforms/generic_unix/socket_driver.c
tests/libs/estdlib/test_gen_tcp.erl

Fixes an issue where the parameters set on a listening socket were not propagated to the accepting socket.

Propagate parameters from listening socket to accepted socket

---

src/platforms/esp32/main/esp32_sys.h

A name clash with port drivers was happening due to a copy&paste
mistake.
Signed-off-by: Davide Bettio <davide@uninstall.it>

Fix REGISTER_NIF_COLLECTION

---

CHANGELOG.md
doc/src/programmers-guide.md
src/libAtomVM/bitstring.h
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_bs_int_unaligned.erl
tests/test.c

This PR fixes a bug with packing and unpacking integers that are not aligned on byte boundaries.
Here is an example expression for both packing and unpacking this PR allows.:
`<<A:1, B:7, C:10, D:6, Rest/binary>>`
Note that currently (and for the foreseeable future) in AtomVM, the sizes of contiguous sequences of unaligned integer expressions must still sum to a value that is a factor of 8.  Thus for example `A:1, B:7, C:10, D:6` in the above example is legal, because the sizes sum to 24, but `A:1, B:7, C:10, D:5` would not be.
Previously, there wasn't really any support for unpacking integer values that were not of a size that is a multiple of 8.  That is now fixed.
In addition, there was a bug in the packing of non-aligned ints in some cases, which has also been fixed.
This PR also …

Fixes a bug with packing and unpacking integers unaligned on byte boundaries.

---

.gitignore

Added rule to track the files inside src/platforms/esp32/components/libatomvm/
that were previously being ignored when changes are made. The existing rule
is still required to track the directory, otherwise the wildcard for the files
would still miss the changes.

Fix .gitignore missing file that should be tracked

---

src/platforms/esp32/mkimage.config
tools/release/esp32/mkimage.erl

This change set allows the mkimage script to work with both make and idf.py builds.

Fix mkimage script to support make and idf.py builds

---

README.Md

This adds information about the documentation available on https://AtomVM.net.
This closes issue #300

Update README to include link to atomvm.net

---

CHANGELOG.md
src/platforms/esp32/main/platform_nifs.c

Allow for values above 31 minutes by accepting 64 bits integer, which is what esp_deep_sleep accepts.

Fix deep_sleep nif

---

CHANGELOG.md
src/libAtomVM/bif.c
src/libAtomVM/bif.h
src/libAtomVM/bifs.gperf
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_boolean.erl
tests/test.c

This change set adds the erlang:is_boolean/1 bif, which returns true if the supplied term is a boolean (the atom true or false), and false, otherwise.
This bif can be used in guard expressions.

Add is_boolean/1 bif

---

libs/eavmlib/src/gpio.erl

attach_interrupt() and detach_interrupt() both used open() which could lead to a new process being created each time, this changes attach_interrupt() to use start() instead which checks for a previously started "gpio" process. detach_interrupt() has ben modified to use whereis(gpio), since that should already be started when the interrupt was attached.

Fixed leak in gpio interrupt functions.

---

.clang-format
src/libAtomVM/atom.h
src/libAtomVM/atomshashtable.h
src/libAtomVM/avmpack.h
src/libAtomVM/bif.h
src/libAtomVM/bitstring.h
src/libAtomVM/context.h
src/libAtomVM/debug.h
src/libAtomVM/defaultatoms.h
src/libAtomVM/dictionary.h
src/libAtomVM/externalterm.h
src/libAtomVM/globalcontext.h
src/libAtomVM/iff.h
src/libAtomVM/interop.h
src/libAtomVM/mailbox.h
src/libAtomVM/memory.h
src/libAtomVM/module.h
src/libAtomVM/nifs.h
src/libAtomVM/platform_nifs.h
src/libAtomVM/port.h
src/libAtomVM/refc_binary.h
src/libAtomVM/scheduler.h
src/libAtomVM/sys.h
src/libAtomVM/term.h
src/libAtomVM/term_typedef.h
src/libAtomVM/timer_wheel.h
src/libAtomVM/valueshashtable.h

Required to build some NIFs/Ports that rely on C++-based components (e.g. [M5Unified](https://github.com/M5Stack/M5Unified))

Make libAtomVM compatible with C++

---

CHANGELOG.md
src/platforms/esp32/main/platform_nifs.c

This change set adds support for the arity-2 version of `esp:partition_erase_range`, alllowing users to erase the remainder of a partition, when the partition size is not known, e.g.,
```
esp:partition_erase_range(Partition, Offset)
```

Added support for esp:partition_erase_range/2

---

.github/workflows/check-formatting.yaml
CONTRIBUTING.md

Use clang-format-13 for nicer comments alignment, update doc

---

libs/exavmlib/lib/AVMPort.ex
libs/exavmlib/lib/CMakeLists.txt

Adds `AVMPort.open/2` providing native elixir functionality of `:erlang.open_port/2`.
Adds `AVMPort.call/2` and `AMVPort.call/3` providing native elixir functionality of eavmlib `:port.call/2` and `:port.call/3`.

Add AVMPort module to examvlib

---

CHANGELOG.md
doc/src/programmers-guide.md
libs/eavmlib/src/i2c.erl
src/platforms/esp32/components/avm_builtins/i2c_driver.c

Added support for `i2c:close/1`

---

.gitignore

Adresses an issue where changes made to core component directories src/platforms/esp32/components/avm_builtins and
src/platforms/esp32/components/avm_sys are not tracked.
Closes Issue #355

Git track changes to core ESP32 components.

---

CHANGELOG.md
src/libAtomVM/externalterm.c
src/libAtomVM/externalterm.h
src/libAtomVM/module.c
src/libAtomVM/module.h
tests/erlang_tests/test_binary_to_term.erl

This change set adds range checking to the parsing of external term, for example, when loading modules or when converting binaries to terms.  If an external term contains encodings that do not fit within the range of an allocated buffer, then the conversion will halt with an error.  In the case of `binary_to_term/1`, the function will raise an `error:badarg`.
Without this change, the VM may crash on a malformed or maliciously crafted binary.  In cases where binaries are exchanged between VM instances (e.g., via TCP), this could result in an attack vector (buffer overflow).
This PR fixed Issue #256  …

Fixed potential VM crash when parsing external terms

---

src/platforms/esp32/components/avm_builtins/gpio_driver.c

Instead of always returning an OK_ATOM there is now a check to return an ERROR_ATOM if setting the interrupt fails.
Closes Issue #354

Add error check to gpiodriver_set_int

---

CHANGELOG.md
src/libAtomVM/memory.c
tests/erlang_tests/test_min_heap_size.erl

This change set enforces the min_heap_size option when spawning a process so that the heap size never shrinks below the specified amount, if it is specified in spawn_opt.

Enforce the min_heap_space setting

---

src/platforms/esp32/components/avm_builtins/CMakeLists.txt
src/platforms/esp32/components/avm_builtins/include/spi_driver.h
src/platforms/esp32/components/avm_builtins/spi_driver.c

This change is required to allow sharing the same SPI bus between Erlang devices and native ones, such as the display driver.

ESP32 SPI: Add spi_driver_get_peripheral function

---

CHANGELOG.md
examples/elixir/esp32/CMakeLists.txt
examples/elixir/esp32/Ledc_x4.ex
libs/exavmlib/lib/CMakeLists.txt
libs/exavmlib/lib/LEDC.ex
src/platforms/esp32/components/avm_builtins/ledc_nif.c

Elixir ledc driver for esp32 using nifs in
src/platforms/esp32/components/avm_builtins/ledc_nif.c

Add LEDC driver to exavmlib

---

tests/erlang_tests/CMakeLists.txt

Include tests/erlang_tests/register_unregister.erl in tests/erlang_tests/CMakeLists.txt.

Fix missing cmake rule for `register_unregister.erl` test

---

CHANGELOG.md
doc/src/programmers-guide.md
libs/eavmlib/src/uart.erl
src/platforms/esp32/components/avm_builtins/uart_driver.c

This changeset also changes the processing of messages on the inbound mailbox queue for the UART port, so that only one message is processed at a time, in order to ensure that if the port is closed, clients will get a proper {error, noproc} if a message is sent after a close message has been processed.

Add support for `uart:close/1`

---

examples/elixir/esp32/Ledc_x4.ex
libs/eavmlib/src/console.erl
src/libAtomVM/nifs.c
tests/erlang_tests/test_process_info.erl
tests/libs/eavmlib/test_timer_manager.erl

This set of changes is to take a step towards addressing issue #255. These changes address warnings about unused variables and parameters in functions, and one unused function in the test suite, when compiling the unix_port of the VM.

Fix compiler warnings

---

tools/dev/flash.sh

Changes harcoded settings in `tools/dev/flash.sh` to use settings that can be configured using `idf.py menuconfig`.

Allow other flash modes and speeds

---

libs/eavmlib/src/gpio.erl

This set of changes fixes an discrapancy in the attach_interrupt/2 function spec and adds documentation to the module.

Erlang gpio driver documentation

---

libs/eavmlib/src/timer_manager.erl
libs/estdlib/src/gen_server.erl

Avoid a race condition on name registration.
Also simplify timer_manager singleton logic

Fix logic of registration of gen_server names

---

.github/workflows/build-and-test-other.yaml
.github/workflows/build-and-test.yaml

Also fix Elixir version for OTP 23.
https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp

Use latest version of erlef/setup-beam action

---

libs/estdlib/src/gen_server.erl
tests/libs/estdlib/test_gen_server.erl

- Timeout can be infinity
- Process messages already in message queue before giving up

Fix bug in gen_server's handling of call timeouts

---

.github/workflows/build-and-test-macos.yaml
.github/workflows/build-and-test-other.yaml
.github/workflows/build-and-test.yaml
.github/workflows/esp32-test.yaml

Total GitHub timeout for jobs is 6 hours, but this is very long. Especially useful with SMP code that is more likely to deadlock.

Add timeouts to test steps

---

CHANGELOG.md
src/libAtomVM/globalcontext.c
src/libAtomVM/globalcontext.h
src/libAtomVM/interop.c
src/libAtomVM/interop.h

interop_kv_get_value_default

---

src/libAtomVM/interop.c
src/libAtomVM/interop.h

Fixed interop_kv_get_value_default and added interop_kv_get_value

---

src/libAtomVM/externalterm.c
src/libAtomVM/externalterm.h
src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h
src/platforms/generic_unix/socket_driver.c

Fixes several compiler warnings for libAtomVM and the generic_unix port, part of the ongoing work to address issue #255.

Fix various compiler warnings

---

src/libAtomVM/interop.c
src/libAtomVM/interop.h

Fix interop_atom_term_select_int params order

---

src/libAtomVM/interop.h

interop_kv_get_value function doesn't require a default_value parameter.

Fix interop_kv_get_value signature

---

CHANGELOG.md
examples/elixir/esp32/CMakeLists.txt
examples/elixir/esp32/SHT31.ex
libs/exavmlib/lib/CMakeLists.txt
libs/exavmlib/lib/I2C.ex

Adds an Elixir interface to the I2C driver and an example for the SHT31 that will only be compile along with the generic_unix port if floating point is enabled.

Add Elixir I2C driver and example

---

.github/workflows/build-and-test-other.yaml

Latest version with armv4t is stretch, use backports for a recent CMake. Latest version is bullseye

Bump versions of debian for other architectures

---

src/platforms/esp32/tools/CMakeLists.txt
src/platforms/esp32/tools/flashimage.sh.in
src/platforms/esp32/tools/mkimage.sh.in

Modifies the esp32 tools to add the target chip name to images created with the `AtomVM/src/platforms/esp32/build/mkimage.sh` tool.

Add chip name to constucted esp32 images

---

.github/workflows/run-tests-with-beam.yaml
tests/libs/estdlib/test_gen_server.erl

Also enable BEAMS tests on macOS as CI runners are different

Make test_gen_server more robust

---

src/libAtomVM/interop.c

Fix a problem that may arise if a proplist contains an empty tuple

---

tools/packbeam/packbeam.c

Replace assert calls that have side effects

Fix PackBeam compilation for Release build type

---

src/platforms/generic_unix/main.c

Also fix the error message which was misleading.
Also fix usage of basename(3). Standard says the passed string can be modified, and we can modify argv.

Allow to run src/AtomVM with a beam file followed by AVMs

---

libs/eavmlib/src/timer_manager.erl
src/libAtomVM/nifs.c
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_monitor.erl
tests/libs/eavmlib/test_timer_manager.erl
tests/libs/estdlib/test_gen_statem.erl
tests/test.c

Fix race condition bug in timer_manager (fix #432)

---

libs/estdlib/src/gen_server.erl
tests/libs/estdlib/test_gen_server.erl

Fix already_started error with gen_server

---

.github/workflows/build-and-test.yaml

Math tests also pass with valgrind

---

CHANGELOG.md
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/test_integer_to_binary.erl
tests/erlang_tests/test_integer_to_list.erl
tests/test.c

Also for erlang:integer_to_binary/2
This should fix an issue with io:format on STM32.

Add support for erlang:integer_to_list/2 with bases

---

README.Md

This fix changes the link in
> This project has been created by Davide Bettio, and now is developed from a growing number of contributors.
redirecting to Davide Bettio's GH account.

Fix link to creator's GH account

---

src/libAtomVM/nifs.c
tests/erlang_tests/test_binary_to_list.erl
tests/test.c

Fix binary_to_list/1: values should be unsigned, in 0..255 range

---

src/libAtomVM/globalcontext.c
src/libAtomVM/term_typedef.h

This PR fixes some but not all of the clang warnings.

Fix clang warnings

---

src/libAtomVM/globalcontext.c
src/libAtomVM/globalcontext.h
src/libAtomVM/module.c
src/libAtomVM/module.h
src/platforms/esp32/main/main.c
src/platforms/esp32/test/main/test_main.c
src/platforms/generic_unix/main.c
src/platforms/stm32/src/main.c
tests/test.c

Simplify API globalcontext_insert_module* consequently.

First atom is module name

---

src/libAtomVM/nifs.c

xtensa GCC 8.4.0 when using additional optimization level is reporting bogus: "error: 'dst' may be used uninitialized" in base64 function.

nifs.c: fix bogus may be used uninitialized

---

src/platforms/stm32/src/CMakeLists.txt
src/platforms/stm32/src/lib/sys.c

This fixes the compiler warnings specific to the stm32 port. The remainder of the warnings when compiling for stm32 are from libAtomVM and related to the API type mismatches.
This is part of meta issue #255.

Fix stm32 warnings

---

src/libAtomVM/bitstring.c
src/libAtomVM/bitstring.h
tests/erlang_tests/test_bs_int.erl

Add support for native endianness for integer in bitstrings

---

src/libAtomVM/opcodesswitch.h
src/platforms/esp32/components/avm_builtins/network_driver.c
src/platforms/esp32/components/avm_builtins/socket_driver.c

This PR fixes some but not all of the ESP32 warnings.

Fix ESP32 warnings

---

src/libAtomVM/opcodesswitch.h

Some UNUSED are not required anymore since the merge of #442.

Remove leftover UNUSED(...)

---

src/libAtomVM/opcodesswitch.h

DECODE_LABEL and DECODE_COMPACT_TERM have been changed in order to remove redundant offset parameter.

opcodesswitch.h: fix build after #442

---

src/libAtomVM/bitstring.c
src/libAtomVM/bitstring.h
src/libAtomVM/opcodes.h
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_bs_utf.erl
tests/test.c

This PR is a step towards OTP25 support. OTP25 doesn't use these opcodes but `bs_create_bin/6` needs the primitives that were missing for utf encoding.
Add support for the following opcodes
- bs_utf8_size
- bs_put_utf8
- bs_utf16_size
- bs_put_utf16
- bs_put_utf32

Add support for bitstring UTF opcodes

---

src/libAtomVM/bitstring.c
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/test_bs.erl

Fix unit with put integer

---

src/libAtomVM/opcodesswitch.h

Signed-off-by: Davide Bettio <davide@uninstall.it>

opcodesswitch.h: remove some extra whitespaces

---

libs/estdlib/src/timer.erl
src/libAtomVM/opcodesswitch.h
src/libAtomVM/scheduler.c
src/libAtomVM/scheduler.h
src/libAtomVM/timer_wheel.h
tests/libs/estdlib/test_timer.erl
tests/libs/estdlib/tests.erl

This PR fixes calls to `timer:sleep` with `infinity` as a parameter.  Also does range checking on integer values to ensure values are within range (per OTP).
This PR also fixes a bug in the handling of messages that have come in to a process while it is waiting for a timeout.  Previously, a process would resume prematurely if it received a message in its mailbox and it was waiting with a timeout.
As a result of these changes, the implementation of `timer:sleep` is greatly simplified.

Fixes calls to timer:sleep(infinity)

---

src/platforms/esp32/components/avm_sys/sys.c

ESP32 sys: add missing unlock in receive_events

---

.clang-format-ignore
src/libAtomVM/scheduler.c
src/platforms/esp32/components/avm_sys/sys.c

Fix formatting issues and keep it formatted.
Signed-off-by: Davide Bettio <davide@uninstall.it>

Run clang-format on scheduler.c and ESP32 sys.c

---

src/libAtomVM/utils.h

Fix unaligned writes of big endian values

---

src/libAtomVM/dictionary.c
src/libAtomVM/memory.c
src/platforms/esp32/components/avm_builtins/spi_driver.c

Always use LIST_FOR_EACH for getting the struct containing the list head, since the struct layout might change causing hard to find bugs.

Do not cast, always use LIST_FOR_EACH

---

.github/workflows/esp32-mkimage.yaml
src/platforms/esp32/components/avm_sys/platform_nifs.c

This PR adds a GitHub workflow to build complete images for the ESP32 family of chipsets, including
* esp32
* esp32c3
* esp32s2
* esp32s3
Images are available as artifacts that can be downloaded after the build completes.
This workflow will be run after a successful run of the ESP32 Build workflow.

Add image creation workflow for esp32 family

---

libs/estdlib/src/supervisor.erl
tests/libs/estdlib/CMakeLists.txt
tests/libs/estdlib/notify_init_server.erl
tests/libs/estdlib/test_supervisor.erl

This PR corrects the order of initialization of children under the supervision of a supervisor, to ensure that they are started in the order specified in the OTP supervisor behavior.

Fix order of supervisor child initialization

---

src/libAtomVM/utils.h
src/platforms/esp32/components/avm_sys/sys.c

Remove "conversion of function pointer to object pointer" warning from ESP32 sys.c.

Fix "conversion of function pointer to object pointer" warning

---

src/platforms/generic_unix/lib/socket_driver.c

Remove unsued var from generic_unix/lib/socket_driver.c.

Fix unused var warning

---

src/libAtomVM/opcodesswitch.h

Use PRIuPTR instead of %d for printf.

Fix format warning

---

src/libAtomVM/opcodesswitch.h

Monitors are printed from parent -> monitored application.  If monitor is a link, then arrow is bidirectional.

Print monitors and links in crash reports

---

libs/eavmlib/src/network.erl

This allows the network module to play better in supervision trees.

Add start_link to network interface

---

src/platforms/esp32/components/avm_sys/platform_nifs.c

Fix ESP32 build

---

src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
src/libAtomVM/sys.h
src/platforms/esp32/components/avm_sys/sys.c
src/platforms/generic_unix/lib/sys.c
src/platforms/stm32/src/lib/sys.c
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_monotonic_time.erl
tests/libs/estdlib/test_timer.erl
tests/test.c

This PR supersedes #481 since we fixed the test using monotonic time.
Closes #481.

Implement erlang:monotonic_time/1 and fix timer test

---

libs/estdlib/src/gen_statem.erl
tests/libs/estdlib/test_gen_statem.erl

This PR adds support for the gen_statem start_link function, so that gen_statem implementations can work with supervisors.

Add start_link/3,4 to gen_statem

---

src/libAtomVM/externalterm.c
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/floatext.erl
tests/test.c

Add support for term_to_binary(Float)

---

src/libAtomVM/externalterm.c
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/small_big_ext.erl
tests/test.c

This PR adds support for the SMALL_BIG_EXT term encoding, supporting encoding and decoding of all integer sizes currently supported by AtomVM.

Add support for SMALL_BIG_EXT term encoding

---

src/libAtomVM/bif.c
src/libAtomVM/dictionary.c
src/libAtomVM/dictionary.h
src/libAtomVM/interop.c
src/libAtomVM/interop.h
src/libAtomVM/memory.c
src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h
src/libAtomVM/tempstack.h
src/libAtomVM/term.c
src/libAtomVM/term.h
src/libAtomVM/utils.h
src/platforms/esp32/components/avm_builtins/gpio_driver.c
src/platforms/esp32/components/avm_builtins/i2c_driver.c
src/platforms/esp32/components/avm_builtins/socket_driver.c
src/platforms/esp32/components/avm_builtins/spi_driver.c
src/platforms/esp32/components/avm_builtins/uart_driver.c
src/platforms/generic_unix/lib/socket_driver.c

Some temp_stack functions (such as init and push) were using malloc, that might fail under low memory conditions.
Rather than ignoring it, or using abort, try to propagate the error to the caller.
A lot of API changes have been made, since those functions were used quite everywhere.
Last but not least, remove dependency on Context and use GlobalContext while changing the API.

Propagate temp_stack errors

---

src/libAtomVM/bif.c
src/libAtomVM/dictionary.c
src/libAtomVM/opcodesswitch.h
src/libAtomVM/term.c
src/libAtomVM/term.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/exactly_eq.erl
tests/test.c

This PR adds an additional parameter that allows to perform an exact comparison (=:=) instead of a numeric comparison (regular ==).
Maps comparison semantic still needs to be fixed and there might be some other minor quirks that need to be handled.

Actual support for exact equal (=:= and =/=)

---

src/platforms/stm32/src/CMakeLists.txt

Fix CMakeLists.txt for STM32

---

.github/workflows/build-and-test.yaml

Ubuntu 18.04 stopped working, also add Ubuntu 22.04 to build and test.

Remove Ubuntu 18.04 and add Ubuntu 22.04 to GH workflows

---

src/libAtomVM/CMakeLists.txt
src/libAtomVM/context.c
src/libAtomVM/context.h
src/libAtomVM/globalcontext.h
src/libAtomVM/mailbox.c
src/libAtomVM/mailbox.h
src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h
src/libAtomVM/refc_binary.h
src/libAtomVM/smp.h
src/platforms/generic_unix/lib/sys.c

- Allow smp platforms to define their own spinlock structures
- Allow smp platforms to not provide stdatomic.h
- Allow platforms to define MIN and MAX macros

Prepare SMP code to support Pico

---

CHANGELOG.md
doc/src/network-programming-guide.md
examples/erlang/esp32/ap_sta_network.erl
examples/erlang/esp32/morse_server.erl
libs/eavmlib/src/network.erl

This PR fixes examples and documentation to reflect changes to the return value from the `network:start` function.
The release notes have been augmented to note that the change to the network interface is API-incompatible with previous releases of AtomVM.

Fixed examples and docs to reflect API changes

---

src/libAtomVM/opcodesswitch.h
src/libAtomVM/term.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_make_fun3.erl
tests/test.c

As reported by @muromec and with provided test case, fix a bug where a heap overflow would occur because allocation lists were poorly decoded.
Also remove unnecessary calls to `memory_ensure_free` for `make_fun3` and `update_record` opcodes that are marked as generating allocations (as opposed to gc) in
[beam_ssa_codegen](https://github.com/erlang/otp/blob/7022abd762883726cf33e616769aca3727ab0354/lib/compiler/src/beam_ssa_codegen.erl#L319).

Fix crash related to make_fun3 OTP24 opcode

---

src/libAtomVM/stacktrace.c

This bug could yield a crash yet was not observed with current GC/memory implementation

Fix allocation computation in `stacktrace_build`

---

src/libAtomVM/nifs.c

This bug did not yield any crash because `MIN_FREE_SPACE_SIZE` is not 0 and allocated memory is more than was is requested.

Fix allocation bug in `nif_binary_split_2`

---

src/libAtomVM/nifs.c

This bug currently cannot yield a crash because the miscalculation is preceded by an allocation which includes the MIN_FREE_SPACE_SIZE margin, larger than padding.

Fix memory allocation bug in `base64_encode`

---

src/libAtomVM/opcodesswitch.h

This bug could potentially yield a crash with current memory implementation, however it was not observed.

Add missing boxed integer allocation in `OP_BS_GET_INTEGER2`

---

src/platforms/generic_unix/lib/platform_nifs.c

Add missing memory_ensure_free in `nif_openssl_random`

---

src/libAtomVM/refc_binary.c
tests/erlang_tests/test_refc_binaries.erl

Also add new test based on refc_binary_info authored by @fadushin

Fix allocation issue in refc_binary_info

---

src/libAtomVM/opcodesswitch.h

This bug could potentially yield a crash with current GC/memory implementation, however it was not observed.
The crash can be observed with heap fragments, though.
The compiler puts allocate to allocate three y registers, registers 1 and 2 are filled with move opcode, register 0 is supposed to be filled by the recv_marker_reserve, and then GC is called and can find garbage (here 2B) and then crash.

Fix potential GC crash related to `OP_RECV_MARKER_RESERVE`

---

src/libAtomVM/nifs.c

If `MIN_FREE_SPACE_SIZE` is 0, or if allocation strategy is fixed, this crashes. Fix the crash with a hack that consists in using ctx->x[0] as a GC root.

Fix crash related to binary_to_term

---

src/libAtomVM/opcodesswitch.h

Fix TRACE line in bs_private_append

---

src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_throw_call_ext_last.erl
tests/test.c

BEAM's compiler and especially beam_trim optimization pass can generate an
incorrect deallocation `n_words` parameter for `call_ext_last/3`.
As a workaround, deallocate after the nif call, and before any error handling
that may need the stack to find catch handlers.
See:  https://github.com/erlang/otp/issues/7152
Add test that currently crashes on master without this change

Add workaround for crash related to `call_ext_last/3`

---

.github/workflows/build-and-test-other.yaml

This fixes CI on armel which requires Debian stretch distribution by using the archive URL.

Fix base_url for archived stretch

---

src/libAtomVM/CMakeLists.txt
src/libAtomVM/bitstring.c
src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h
src/libAtomVM/term.h

Also make incompatible pointer type warnings an error for both compilers

Enable clang warnings and fix some GCC/clang warnings

---

src/libAtomVM/bif.c
src/libAtomVM/bif.h
src/libAtomVM/bifs.gperf
src/libAtomVM/externalterm.c
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/test_binary_to_term.erl

Fix a bug where call of function references would fail Fix a warning related to encoding of function references Implement decoding of function references

Fix call and encoding/decoding of function references

---

.github/workflows/publish-docs.yaml

Adds checks before commiting or pushing the generated documentation. This will allow the workflow to run in forks to ensure that doxygen style comments for documentation can still be parsed, without actually atempting to publish the documentation from outside of the offical `atomvm/AtomVM` repo.

Prevent commit and push operations in Publish docs workflow in forks

---

.github/workflows/publish-docs.yaml

Fixes workflow to make sure it still publishes for the official atomvm/AtomVM repo.

Fix Publish docs workflow not committing

---

libs/alisp/src/sexp_parser.erl
libs/estdlib/src/gen_event.erl
libs/etest/src/etest.erl
tests/erlang_tests/test_types_ordering.erl
tests/libs/estdlib/test_io_lib.erl

This PR fixes some annoying Erlang compiler warnings.

Fix erlc compiler warnings

---

src/libAtomVM/opcodesswitch.h

Avoid unnecessary warning with Apple Clang 13.0.0

---

src/libAtomVM/bif.c
src/libAtomVM/mailbox.c
src/libAtomVM/memory.c
src/libAtomVM/memory.h
src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h

Update `memory_ensure_free` so it never reduces the amount of free memory.
Update `memory_gc` to optionally handle additional roots.
Introduce `memory_ensure_free_opt` that can shrink the heap a little bit
more aggressively (including when amount of free memory is higher than what
is required plus a margin) and use it instead where it is safe.
Replace usage of `memory_gc` with `memory_ensure_free_opt` and remove it
from `memory.h` header.

Clarify GC shrink strategy

---

src/libAtomVM/bif.c
src/libAtomVM/bif.h
src/libAtomVM/bifs.gperf

Add erlang:is_float/1 BIF

---

src/platforms/esp32/components/avm_builtins/gpio_driver.c
src/platforms/esp32/components/avm_builtins/i2c_driver.c
src/platforms/esp32/components/avm_builtins/spi_driver.c

This PR is a successor of #516
Replace the process dictionary trick in esp32 drivers with `memory_ensure_free_opt` which provides additional GC roots.

Replace process dictionary trick with `memory_ensure_free_opt`

---

src/libAtomVM/bif.c
tests/libs/estdlib/test_maps.erl

This PR is a successor of #516
Fix the following APIs, using new `memory_ensure_free_opt` roots arg:
- `erlang:is_map_key/2`
- `erlang:map_size/1`
- `erlang:map_get/2`

Fix API for several map BIFs

---

.github/workflows/publish-docs.yaml
doc/CMakeLists.txt

Changes the workflow to only checkout other branches if the documentation is being published by `atomvm/AtomVM` repository.
Changes the use of `sed` in CMakeLists.txt to be POSIX compliant.

Fixes publish-docs.yml for platfoms and forks

---

src/platforms/stm32/cmake/libopencm3.cmake

Libopencm3 disables support for floats in `printf` and `scanf` by default, this PR enables floats in `printf` and `scanf`.
Closes Issue #446

Enable support for printing floats on stm32

---

examples/elixir/esp32/SHT31.ex

Update to suppress compile warning and stop showing up at the bottom of the "Files changed" tab on GitHub for every pull request under the `Unchanged files with check annotations` section at the bottom of the page.

Fix compiler warning about SHT31.ex

---

src/libAtomVM/term.h

Remove unused `term_match_state_get_save_offset`

---

.github/workflows/build-and-test-macos.yaml
.github/workflows/build-and-test-other.yaml
.github/workflows/build-and-test.yaml
.github/workflows/check-formatting.yaml
.github/workflows/codeql-analysis.yaml
.github/workflows/esp32-build.yaml
.github/workflows/esp32-test.yaml
.github/workflows/publish-docs.yaml
.github/workflows/run-tests-with-beam.yaml
.github/workflows/stm32-build.yaml

These changes will skip running individual workflows if they do not utilize the changed files. The exception is the `esp32-build.yaml` workflow, which will also run on `push` if the only changes are to modules in the `libs` directory, so that the `esp32-mkimage.yaml` workflow will run and create a new esp32 binary image containing the updated modules.

Run workflows conditionally based on file changes

---

CHANGELOG.md
doc/src/programmers-guide.md
libs/eavmlib/src/gpio.erl
libs/exavmlib/lib/GPIO.ex
src/platforms/esp32/components/avm_builtins/gpio_driver.c

Adds support for both erlang and elixir to stop and free the resources of the gpio port driver on esp32.
Closes issue #277

Support for `gpio:close/1` on feature/smp branch

---

CHANGELOG.md
doc/src/programmers-guide.md
libs/estdlib/src/erlang.erl
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
src/libAtomVM/refc_binary.c
src/libAtomVM/refc_binary.h
tests/erlang_tests/test_refc_binaries.erl
tests/erlang_tests/test_sub_binaries.erl

This PR adds support for the `erlang:memory/1` function, with initial support only for the `binary` type.

Add support for erlang:memory(binary)

---

.github/workflows/build-and-test-other.yaml

Fix CI for armel

---

doc/CMakeLists.txt
doc/conf.py.in

Convert slash `/` in branch names to a `-` for URLs and file names in the published documentation.

Fix bug in publish-docs.yaml handling branch names containing slashes

---

src/libAtomVM/term.c
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/tuple_comparisons.erl
tests/test.c

Fix tuple comparison

---

src/libAtomVM/context.c
src/platforms/esp32/components/avm_builtins/socket_driver.c
src/platforms/esp32/test/main/test_main.c

- Fix a bug where the message was not &netconn but &&netconn
- Fix several cases of memory_ensure_free that may garbage collect terms
- Change logic to only call lwip send & receive from the native handler
- Factorize code
- Enable socket test that was disabled
- Modify context_destroy to free platform_data to avoid possible (unobserved) crashes

Fix socket driver in feature/smp branch

---

.clang-format-ignore
src/libAtomVM/memory.c

Fix and enforce `memory.c` format

---

src/libAtomVM/interop.c
src/libAtomVM/memory.c
src/libAtomVM/tempstack.h
src/libAtomVM/term.c

Fix typo s/temp_stack_destory/temp_stack_destroy/g

---

src/platforms/generic_unix/lib/sys.c

Fix warnings on some targets

---

src/libAtomVM/memory.c

Fix merge conflict resolution typo

---

.github/workflows/esp32-build.yaml

Build on latest IDF SDK 4.2, 4.3, and 4.4.

---

doc/release-notes.md.in
doc/src/build-instructions.md
doc/src/getting-started-guide.md

Udate new ESP-IDF support versions. Documentation fixes and updates.

Documentation updates

---

libs/eavmlib/src/spi.erl

Accumulator parameter was swapped, so it was crashing when using a proplist as device config.

SPI module: fix proplists handling

---

.github/workflows/codeql-analysis.yaml
code-queries/qlpack.yml
code-queries/term-to-non-term-func.ql

Start checking code with custom queries, starting from a new based on an observed error.

Add first CodeQL custom query

---

src/platforms/generic_unix/lib/socket_driver.c

Fix term usage bugs found by new CodeQL query

---

src/platforms/esp32/components/avm_builtins/socket_driver.c
src/platforms/esp32/components/avm_sys/include/esp32_sys.h
src/platforms/esp32/test/main/test_erl_sources/test_socket.erl

- Fix protocol issue with UDP (didn't return IP and port)
- Fix issue with UDP pid
- Fix potential blocking issue where callback would be called several times between reads of the socket
- Add workaround for a limitation of lwIP allowing for a server accepting connections to receive data (and invoke callback) before `netconn_accept` is called
- Fix concurrency issues
- Fix a memory corruption issue caused by a mis-allocation
- Add more tests

Further esp32 socket_driver fixes

---

examples/erlang/esp32/sx127x.erl

The example was still using `spi_mode` instead of `mode`.

Fix wrong sx127x SPI example

---

src/libAtomVM/timer_wheel.c

Add missing null check for malloc()

---

src/libAtomVM/globalcontext.c
src/libAtomVM/globalcontext.h
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
src/platforms/esp32/test/main/test_erl_sources/CMakeLists.txt
src/platforms/esp32/test/main/test_erl_sources/test_tz.erl
src/platforms/esp32/test/main/test_main.c
tests/erlang_tests/datetime.erl

Add support for `erlang:localtime/0` and introduce `erlang:localtime/1` to get the local time for a given timezone.
`erlang:localtime/1` takes a string conforming to [POSIX.1-2017](https://pubs.opengroup.org/onlinepubs/9699919799/) TZ environment variable.
See the conversation in ticket erlang/otp#7228

Add support for `erlang:localtime/0` and introduce `erlang:localtime/1`

---

src/platforms/esp32/components/avm_sys/platform_nifs.c
src/platforms/esp32/test/main/test_erl_sources/CMakeLists.txt
src/platforms/esp32/test/main/test_erl_sources/test_md5.erl
src/platforms/esp32/test/main/test_main.c

The missing call `memory_ensure_free` could yield a crash, yet it was not observed.

Add missing call to `memory_ensure_free` for `erlang:md5/1` nif

---

examples/erlang/esp32/morse_server.erl

Remove call to register/2 since the driver does this internally and the extra call now causes an error.

Update morse_server example

---

src/libAtomVM/interop.c
src/libAtomVM/interop.h

interop_kv_get_value_default wasn't working with maps, fix it.

Fix bug in interop_kv_get_value_default

---

src/libAtomVM/opcodesswitch.h
tests/erlang_tests/test_bs.erl

The test generates such a term with OTP21 compiler.
This is the current CI crash of #579

Fix bug in decoding of literals in DECODE_COMPACT_TERM

---

libs/eavmlib/src/gpio.erl
libs/exavmlib/lib/GPIO.ex
src/platforms/stm32/src/lib/gpiodriver.c

Restores functionality to the stm32 gpio driver by updating mailbox message parsing to match updates to the the erlang and elixir drivers. Modifies the `pin() type` in both versions of the gpio driver to accommodate tuples used in the stm32 port.
Signed-off-by: Winford <winford@object.stream>

Update stm32 gpio driver

---

src/platforms/esp32/components/avm_builtins/socket_driver.c
src/platforms/esp32/test/main/test_erl_sources/test_socket.erl

Fix format of gen_udp active packet on esp32 (fix #589)

---

libs/eavmlib/src/atomvm.erl
libs/eavmlib/src/console.erl
libs/eavmlib/src/esp.erl
libs/eavmlib/src/gpio.erl
libs/eavmlib/src/http_server.erl
libs/eavmlib/src/i2c.erl
libs/eavmlib/src/json_encoder.erl
libs/eavmlib/src/ledc.erl
libs/eavmlib/src/logger.erl
libs/eavmlib/src/network.erl
libs/eavmlib/src/network_fsm.erl
libs/eavmlib/src/port.erl
libs/eavmlib/src/spi.erl
libs/eavmlib/src/timestamp_util.erl
libs/estdlib/src/calendar.erl
libs/estdlib/src/erlang.erl
libs/estdlib/src/gen_server.erl
libs/estdlib/src/gen_statem.erl
libs/estdlib/src/gen_tcp.erl
libs/estdlib/src/gen_udp.erl
libs/estdlib/src/inet.erl
libs/estdlib/src/io.erl
libs/estdlib/src/io_lib.erl
libs/estdlib/src/lists.erl
libs/estdlib/src/maps.erl
libs/estdlib/src/proplists.erl
libs/estdlib/src/string.erl
libs/estdlib/src/timer.erl

Adds documentaion for several of the modules that lack it, and expands others that were missing entries for some functions. Fixes many incomple function specs, and typos. Removed duplicate coyright entries.

Erlang documentation additions and corrections

---

libs/estdlib/src/io_lib.erl
libs/include/etest.hrl
tests/libs/estdlib/test_io_lib.erl

Fix implementation of ~s format
Add ~w format
Fix tests

Further implement `io_lib:format/2` (fix #594)

---

src/libAtomVM/context.c
src/libAtomVM/globalcontext.c
src/libAtomVM/memory.c
src/libAtomVM/memory.h
src/libAtomVM/refc_binary.c
src/libAtomVM/refc_binary.h
src/platforms/esp32/components/avm_builtins/gpio_driver.c
src/platforms/esp32/components/avm_builtins/network_driver.c
src/platforms/esp32/components/avm_builtins/socket_driver.c
src/platforms/esp32/components/avm_builtins/uart_driver.c
src/platforms/generic_unix/lib/socket_driver.c

Also slightly change API for destroying heaps as we now need the global context

Fix synchronization issue with refc binaries

---

src/libAtomVM/port.h

Allow including errno.h before port.h

Fix a conflict in usage of errno

---

src/libAtomVM/mailbox.c
src/libAtomVM/mailbox.h

Return the message without disposing it. This can be useful for having full control on received messages.

Add mailbox_take_message function

---

src/platforms/esp32/components/avm_builtins/gpio_driver.c

Fixes a problem in the esp32 gpio driver where if a numeric level is used (`0` or `1`) rather than atoms (`low` or `high`) the numeric input would be silently ignored.
Closes issue #584

Fix esp32 gpio:set_level/3 and gpio:digital_write/2

---

src/platforms/generic_unix/lib/socket_driver.c

SocketDriverData.port is a uint16_t and cannot hold a term.
This bug was shown by test_gen_udp test.

Fix inet:port implementation

---

src/platforms/esp32/CMakeLists.txt

This should fix ci issue when building esp32 images.

Force non-SMP build with esp32 targets with no SMP primitive

---

src/libAtomVM/CMakeLists.txt
src/libAtomVM/globalcontext.c
src/libAtomVM/globalcontext.h
src/libAtomVM/listeners.h
src/libAtomVM/sys.h
src/platforms/esp32/components/avm_builtins/gpio_driver.c
src/platforms/esp32/components/avm_builtins/socket_driver.c
src/platforms/esp32/components/avm_builtins/uart_driver.c
src/platforms/esp32/components/avm_sys/include/esp32_sys.h
src/platforms/esp32/components/avm_sys/sys.c
src/platforms/generic_unix/lib/generic_unix_sys.h
src/platforms/generic_unix/lib/sys.c
src/platforms/stm32/src/lib/sys.c

Both generic_unix and esp32 platforms featured event listeners.
Factorize code adding a new header that is included by both, listeners.h.
stm32 platform currently does not implement any listener.
Also fix a potential concurrency bug in esp32 drivers that removed listeners
without locking the list.

Factorize event listeners

---

src/platforms/esp32/components/avm_builtins/gpio_driver.c
src/platforms/esp32/components/avm_builtins/i2c_driver.c
src/platforms/esp32/components/avm_builtins/ledc_nif.c
src/platforms/esp32/components/avm_builtins/network_driver.c
src/platforms/esp32/components/avm_builtins/nvs_nif.c
src/platforms/esp32/components/avm_builtins/rtc_slow_nif.c
src/platforms/esp32/components/avm_builtins/socket_driver.c
src/platforms/esp32/components/avm_builtins/spi_driver.c
src/platforms/esp32/components/avm_builtins/uart_driver.c
src/platforms/esp32/components/avm_sys/include/esp32_sys.h
src/platforms/esp32/components/avm_sys/sys.c
src/platforms/esp32/test/main/test_main.c

Required hygiene for qemu-based testing

Implement destruction of esp32 nifs/ports

---

.github/workflows/pico-build.yaml
CMakeLists.txt
CMakeModules/BuildErlang.cmake
README.Md
README.PICO.Md
examples/erlang/CMakeLists.txt
examples/erlang/rp2040/CMakeLists.txt
examples/erlang/rp2040/hello_pico.erl
examples/erlang/rp2040/pico_rtc.erl
libs/eavmlib/src/pico.erl
src/libAtomVM/memory.c
src/platforms/rp2040/.gitignore
src/platforms/rp2040/CMakeLists.txt
src/platforms/rp2040/pico_sdk_import.cmake
src/platforms/rp2040/src/CMakeLists.txt
src/platforms/rp2040/src/lib/CMakeLists.txt
src/platforms/rp2040/src/lib/platform_defaultatoms.c
src/platforms/rp2040/src/lib/platform_defaultatoms.h
src/platforms/rp2040/src/lib/platform_nifs.c
src/platforms/rp2040/src/lib/platform_smp.h
src/platforms/rp2040/src/lib/rp2040_sys.h
src/platforms/rp2040/src/lib/smp.c
src/platforms/rp2040/src/lib/sys.c
src/platforms/rp2040/src/main.c
tools/uf2tool/CMakeLists.txt
tools/uf2tool/uf2tool.erl

This PR provides minimal support for Raspberry Pi Pico.

Support for Raspberry Pi Pico (fix #197)

---

src/platforms/stm32/src/main.c

Fix loading of avm data on stm32

---

src/platforms/esp32/components/avm_sys/sys.c

This PR fixes a warning that is treated as an error on ESP32 builds that don't support SMP.

Fix no-smp ESP32* builds

---

.github/workflows/esp32-mkimage.yaml

Run the mkimage workflow on any push or PR

---

.github/workflows/build-and-test-other.yaml
tests/test.c

Fix 2 CI workflows that stopped working after #469.

Fix CI issues introduced with #469

---

src/platforms/esp32/test/main/test_main.c

Fix ESP32 test after #469

---

.github/workflows/codeql-analysis.yaml
code-queries/non-term-to-term-func.ql

Add new query based on Paul Guyot work for detecting when a non-term, such an integer is passed to a function expecting a term without using term_from_int(...).

Add CodeQL query for non-term to term problems

---

src/platforms/esp32/components/avm_builtins/network_driver.c
src/platforms/esp32/components/avm_builtins/socket_driver.c
src/platforms/esp32/components/avm_sys/platform_nifs.c

Reduce ESP32 compilation warnings

---

src/libAtomVM/debug.c
src/libAtomVM/module.c
src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h
src/libAtomVM/term.c
src/platforms/esp32/components/avm_builtins/network_driver.c

This change will be required for esp-idf 5.0 that has stricter compile options.

Use PRI(u/i)32 as format string for (u)int32_t instead of %i

---

src/libAtomVM/nifs.c
src/libAtomVM/scheduler.c
src/libAtomVM/sys.h
src/platforms/esp32/components/avm_sys/sys.c
src/platforms/generic_unix/lib/sys.c
src/platforms/rp2040/src/lib/sys.c
src/platforms/stm32/src/lib/sys.c
tests/erlang_tests/sleep.erl

Also rename `sys_millis` to `sys_monotonic_millis`, remove unused parameter and clarify its usage.
Also fix a potential overrun bug on STM32. The milliseconds timer was read twice to generate a timespec, so it could end with 999 when being read for seconds and be incremented by 1 before being read for nsecs, thus returning a timespec 1 second in the past.
This PR fixes flappiness on macOS CI builds.

Fix sleep test by reducing it to contract

---

src/platforms/esp32/CMakeLists.txt
src/platforms/esp32/test/CMakeLists.txt

Also fix issues with 5.x sdk by not requiring C11 if IDF selected C11 or higher.

Compile ESP32 tests with C11

---

libs/eavmlib/src/timer_manager.erl

test_timer_manager test would sometimes fail because of a race condition. The timer sent the timeout message, the client would then send a message to list timers before the timer sent a message to remove the timer fom the list.
The same issue existed with canceled timers.

Ensure timer is removed from list when it fires or it is canceled

---

.github/workflows/check-formatting.yaml

Updates the currently broken workflow, which emmits an error that rebarr3 is compiled for a later version.

Update check-formatting.yaml workflow

---

.github/workflows/esp32-build.yaml
src/libAtomVM/term.c
src/platforms/esp32/components/avm_builtins/CMakeLists.txt
src/platforms/esp32/components/avm_builtins/socket_driver.c
src/platforms/esp32/components/avm_builtins/uart_driver.c
src/platforms/esp32/components/avm_sys/CMakeLists.txt
src/platforms/esp32/components/avm_sys/include/esp32_sys.h
src/platforms/esp32/components/avm_sys/platform_nifs.c
src/platforms/esp32/components/avm_sys/sys.c
src/platforms/esp32/main/main.c

**WARNING: network driver is not available with esp-idf v5.x, so v5.x is not yet officially supported**

Add support to esp-idf 5.0

---

libs/eavmlib/src/gpio.erl

Add missing export to gpio module

---

.github/workflows/run-tests-with-beam.yaml
tests/erlang_tests/test_binary_to_term.erl
tests/erlang_tests/test_system_flag.erl
tests/erlang_tests/tuple_size0.erl
tests/erlang_tests/tuple_size5.erl
tests/erlang_tests/tuple_size6.erl
tests/erlang_tests/tuples_and_list_size0.erl
tests/libs/estdlib/test_gen_server.erl
tests/libs/estdlib/test_maps.erl
tests/test.c

- various size tests failed with OTP25+ following OTP-17608
- test_binary_to_term failed with OTP26 following OTP-18505
- test_gen_server failed with OTP24+ following OTP-16718
- test_maps failed with OTP24+ as badarg is preferred over bad_map when both exception would occur (passing not a function and not a map to map:filter/2)
- test_maps failed with OTP26 as iteration order changed following OTP-18414
Change fail-fast strategy
Update CI matrix to 21-26 on Ubuntu and 23-25 on macOS (versions currently supported by Homebrew)
Also update cache action version to 3 as 2 is deprecated
Also fix test_system_flag test for BEAM on AMD CPUs …

Fix tests to run on OTP24, 25 and 26

---

.github/workflows/esp32-build.yaml
src/platforms/esp32/components/avm_builtins/CMakeLists.txt

Some minor changes to build options are needed for v5.1, so WHOLE_ARCHIVE is used instead.

Add support to esp-idf v5.1

---

src/platforms/esp32/components/avm_sys/sys.c
src/platforms/esp32/test/main/test_erl_sources/CMakeLists.txt
src/platforms/esp32/test/main/test_erl_sources/test_monotonic_time.erl
src/platforms/esp32/test/main/test_main.c

Fix monotonic_time on esp32 (fix #597)

---

CHANGELOG.md
src/platforms/esp32/components/avm_builtins/CMakeLists.txt
src/platforms/esp32/components/avm_builtins/network_driver.c

Updates the network interface from the depreciated tcpip_adapter to the esp_netif component.
closes #633

Update esp32 network driver to use esp_netif

---

src/libAtomVM/context.c
src/libAtomVM/globalcontext.c
src/libAtomVM/globalcontext.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/whereis_dead_process.erl
tests/test.c

Adds the function `globalcontext_maybe_unregister_process_id` to globalcontext.c to allow removing the appropriate entry from the registered atoms table when the associated context is destroyed.

Unregister processes when they die

---

src/libAtomVM/externalterm.c
src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h
src/libAtomVM/term.h
src/platforms/esp32/components/avm_builtins/rtc_slow_nif.c
src/platforms/esp32/components/avm_builtins/socket_driver.c
src/platforms/esp32/components/avm_builtins/spi_driver.c
src/platforms/esp32/components/avm_builtins/uart_driver.c
src/platforms/esp32/components/avm_sys/platform_nifs.c
src/platforms/generic_unix/lib/platform_nifs.c
src/platforms/generic_unix/lib/socket_driver.c

This PR refactors uses of `term_binary_data_size_in_terms` into a new `term_binary_heap_size` function that encapsulates the number of terms needed in the heap to store a binary.  This change allows users to calculate needed heap sizes without having to remember to add the `BINARY_HEADER_SIZE` macro to the calculation.

Clean up binary heap size calculations

---

.github/workflows/run-tests-with-beam.yaml

Test weirdfully fails with binary provided by erlef/setup-beam.
Use [Erlang/OTP official docker image](https://registry.hub.docker.com/_/erlang/) instead.
See erlef/setup-beam#220

Fix test_gc on OTP26 on Linux using official docker image

---

tools/dev/flash.sh

The esptool.py resides in a different in ESP-IDF v5.x than it does in v4.x, and it can also be installed independantly from ESP-IDF. This updates the `flash.sh` tool to use whichever esptool.py is active in the users path. This is prepended to the `PATH` when the IDF is activated using `. ./export.sh`, so it will work with both major versions. This also allows the user to flash the most recent build again without having to first activate the ESP-IDF, if they have esptool.py installed independantly, which is quite likely as it simplifies working with rebar3.

Update esp32 `flash.sh` tool for IDF 5.x compatibility

---

CHANGELOG.md
src/libAtomVM/globalcontext.c
src/libAtomVM/globalcontext.h
src/libAtomVM/nifs.c
tests/erlang_tests/test_send.erl
tests/erlang_tests/test_send_nif_and_echo.erl
tests/test.c

Changes `erlang:send/2` to accept a pid or registered process name. Updates `tests/erlang_tests/test_send_nif_and_echo.erl` to also test sending directly to the registered name, and `tests/erlang_tests/test_send.erl` to test sending to an an unregistered `atom` name.
closes #98

Allow sending message to registered process name

---

src/platforms/esp32/components/avm_sys/sys.c

atomvm:add_avm_pack_file("/dev/partition/by-name/ ...) wasn't working due to a small bug.

ESP32: fix loading avm from partition when using add_avm_pack_file

---

src/platforms/esp32/components/avm_builtins/rtc_slow_nif.c

Remove unused declaration of `rtc_slow_nif_init`

---

CMakeModules/DefineIfExists.cmake
src/libAtomVM/CMakeLists.txt
src/libAtomVM/globalcontext.c
src/libAtomVM/globalcontext.h
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
src/libAtomVM/posix_nifs.c
src/libAtomVM/posix_nifs.h
src/libAtomVM/resources.c
src/libAtomVM/term.h
src/platforms/esp32/CMakeLists.txt
src/platforms/esp32/test/CMakeLists.txt
src/platforms/esp32/test/main/test_erl_sources/CMakeLists.txt
src/platforms/esp32/test/main/test_erl_sources/test_file.erl
src/platforms/esp32/test/main/test_main.c
src/platforms/esp32/test/test_atomvm.py
src/platforms/rp2040/CMakeLists.txt
src/platforms/stm32/CMakeLists.txt
src/platforms/stm32/cmake/libopencm3.cmake
tests/libs/eavmlib/CMakeLists.txt
tests/libs/eavmlib/test_file.erl
tests/libs/eavmlib/tests.erl

NIFs are compiled if platform features common POSIX functions `open`, `close`,
`read`, `write` and `unlink`.
Implementation is non-blocking and a more complete implementation of a file
module may require `enif_select`, at least to work with FIFO pipes and devices.
On ESP32, implementation depends on vfs_fat driver which is always blocking
(and does not support select). Qemu-based test writes to a (virtual) SD card.
However, support for SD card still requires C code to mount it which is not
the object of this PR.

Implement basic POSIX file functions as nifs

---

.github/workflows/check-formatting.yaml

Use setup-beam@v1 instead of a specific (old) version.

Fix check-formatting.yaml GitHub workflow

---

doc/src/programmers-guide.md
src/libAtomVM/nifs.c

Add support to name option to atomvm:add_avm_pack_file/2.

Allow registering .avm using name

---

examples/erlang/esp32/tcp_server_blink.erl
examples/erlang/network_console.erl
examples/erlang/tcp_server.erl

io_lib:format returns a iolist() so `~s` should be used instead of `~p`.

Fix messages printed from io:format

---

src/platforms/esp32/components/avm_builtins/socket_driver.c

These changes are made under both the "Apache 2.0" and the "GNU Lesser General Public License 2.1 or later" license terms (dual license).

Fix early return in the socket driver for esp32.

---

CHANGELOG.md
doc/src/programmers-guide.md
examples/elixir/esp32/SHT31.ex
examples/erlang/esp32/sht31.erl
libs/eavmlib/src/i2c.erl
libs/exavmlib/lib/I2C.ex
src/platforms/esp32/components/avm_builtins/i2c_driver.c
src/platforms/esp32/components/avm_sys/include/esp32_sys.h
src/platforms/esp32/components/avm_sys/sys.c

This change set makes the following breaking changes to the Erlang i2c driver API
* The return type of i2c functions that return an error has changed to a tuple including
the error atom as well as a mnemonic reason.
* The return type of i2c:read_bytes has changed to a tuple of the form {ok, Binary} when a binary
is successfully read from the device.

I2C driver API changes

---

libs/eavmlib/src/CMakeLists.txt

avm_pubsub wasn't built with eavmlib.

Fix missing module in eavmlib CMakeLists.txt

---

libs/estdlib/src/io_lib.erl
libs/estdlib/src/timer.erl
src/libAtomVM/bitstring.h

Fix compilation of documentation after 032a912
Fix warning in src/timer.erl
Fix content of documentation related to `bitstring_utf8_encode`

Fix documentation

---

src/libAtomVM/synclist.h

Fix warnings when building without SMP

---

.github/workflows/esp32-test.yaml
src/platforms/esp32/components/avm_builtins/socket_driver.c
src/platforms/esp32/test/test_atomvm.py

Also fix CI for esp32 test by bumping timeout to 120 secs

Fix esp32 default socket opts

---

doc/src/build-instructions.md

Also remove mention of -j which no longer applies to ninja-based idf.py build

Document ESP32 qemu tests

---

CHANGELOG.md
doc/src/programmers-guide.md
libs/estdlib/src/calendar.erl
tests/libs/estdlib/CMakeLists.txt
tests/libs/estdlib/test_calendar.erl
tests/libs/estdlib/tests.erl

Added support for `calendar:datetime_to_gregorian_seconds/1`

---

.github/workflows/wasm-build.yaml
CHANGELOG.md
README.Md
src/libAtomVM/CMakeLists.txt
src/platforms/emscripten/.gitignore
src/platforms/emscripten/CMakeLists.txt
src/platforms/emscripten/src/CMakeLists.txt
src/platforms/emscripten/src/lib/CMakeLists.txt
src/platforms/emscripten/src/lib/platform_defaultatoms.c
src/platforms/emscripten/src/lib/platform_defaultatoms.h
src/platforms/emscripten/src/lib/platform_nifs.c
src/platforms/emscripten/src/lib/sys.c
src/platforms/emscripten/src/main.c

Also improve detection of support of pragma STDC_FENV_ACCESS
This is a different approach than #30 : emscripten is created as a separate platform instead of patching generic_unix files.
Also, SMP is disabled on this platform (for now) as using pthreads create some serious constraint in browsers.
This PR is only for creating the platform, with tests using nodejs.
A continuation PR shall include adding an option to not use nodejs raw file system and adding a script to bundle avm files (mostly calling emscripten's file_package.py), so this can be used in the browser.

Initial support for wasm

---

src/libAtomVM/interop.c
src/libAtomVM/interop.h

Also change semantics of interop_term_to_string to work with iolist.

Add function interop_iolist_to_string

---

doc/src/build-instructions.md
tools/dev/flash.sh

Enhances the `flash.sh` tool to accept `-o` option to set the flash offset from option arguments, overriding any environment variable. Also adds the `-l` option to allow flashing `atomvmlib.avm` to the default `lib.avm` partition offset of `0x1D0000`. Allows for the use of independently installed `esptool.py`, either from OS packages, with `pip install esptool`, or from Espressif's [esptool github repo](https://github.com/espressif/esptool). Note: by default, if the ESP-IDF has been activated in the users environment, the esp-idf included version of the tool will appear first in the users environment PATH.
SPDX-License-Identifier: Apache-2.0 OR …

Improve esp32 `flash.sh` tool

---

src/libAtomVM/nifs.c
tests/erlang_tests/test_list_to_binary.erl
tests/test.c

Fix semantic of `list_to_binary/1`

---

libs/eavmlib/src/http_server.erl

Close TCP connection from http_server when reply/3 is used (as it used to do). Connection is not closed by users of reply/4 as they may pass a Content-Length header and let the client close the connection. This actually is a workaround for an issue in the gen_tcp implementation where the socket is closed before all data is sent.

Fix issue with http_server introduced in 474dea9

---

.github/workflows/wasm-build.yaml
README.WASM.Md
doc/src/atomvm-internals.md
doc/src/build-instructions.md
doc/src/getting-started-guide.md
examples/CMakeLists.txt
examples/emscripten/CMakeLists.txt
examples/emscripten/call_cast.erl
examples/emscripten/call_cast.html
examples/emscripten/hello_world_avm.html
examples/emscripten/hello_world_beam.html
examples/emscripten/index.html
examples/emscripten/run_script.erl
examples/emscripten/run_script.html
examples/emscripten/wasm_webserver.erl
src/platforms/emscripten/src/CMakeLists.txt
src/platforms/emscripten/src/atomvm.pre.js
src/platforms/emscripten/src/lib/emscripten_sys.h
src/platforms/emscripten/src/lib/platform_nifs.c
src/platforms/emscripten/src/lib/sys.c
src/platforms/emscripten/src/main.c
src/platforms/emscripten/tests/.gitignore
src/platforms/emscripten/tests/cypress.config.js
src/platforms/emscripten/tests/cypress/e2e/call.spec.cy.js
src/platforms/emscripten/tests/cypress/e2e/examples.spec.cy.js
src/platforms/emscripten/tests/src/CMakeLists.txt
src/platforms/emscripten/tests/src/test_call.erl
src/platforms/emscripten/tests/src/test_call.html

Update Emscripten port so that AtomVM can run in the browser
Add API to run Javascript from Erlang
Add API to call Erlang from Javascript
Add new web server to serve example files with proper headers

Further Wasm support

---

src/libAtomVM/memory.c
src/libAtomVM/term.h

Add cons size constant + fix typo

---

src/libAtomVM/memory.h

Fix comment documentation of `memory_init_heap*`

---

src/libAtomVM/nifs.c
src/platforms/esp32/test/main/test_erl_sources/CMakeLists.txt
src/platforms/esp32/test/main/test_erl_sources/test_list_to_binary.erl
src/platforms/esp32/test/main/test_main.c
tests/erlang_tests/test_list_to_binary.erl

malloc(0) returns NULL on ESP32, which results in an OUT_OF_MEMORY error.  This PR checks handles the case where the size of the input list is 0 specially.

Fixed a bug in list_to_binary

---

.github/workflows/esp32-build.yaml
CHANGELOG.md
doc/src/programmers-guide.md
libs/eavmlib/src/esp.erl
src/platforms/esp32/components/avm_sys/platform_nifs.c
src/platforms/esp32/test/main/test_erl_sources/CMakeLists.txt
src/platforms/esp32/test/main/test_erl_sources/test_esp_partition.erl
src/platforms/esp32/test/main/test_main.c
src/platforms/esp32/test/partitions.csv

Add function for listing all available partitions.

ESP32: add `esp:partition_list/0` function

---

src/platforms/emscripten/src/lib/platform_nifs.c
src/platforms/emscripten/tests/cypress/e2e/atomvm.spec.cy.js
src/platforms/emscripten/tests/src/CMakeLists.txt
src/platforms/emscripten/tests/src/test_atomvm.erl
src/platforms/emscripten/tests/src/test_atomvm.html

Implement atomvm:random/0 on emscripten

---

src/libAtomVM/nifs.c
src/libAtomVM/sys.h
src/platforms/emscripten/src/lib/sys.c
src/platforms/emscripten/src/main.c
src/platforms/esp32/components/avm_sys/sys.c
src/platforms/generic_unix/lib/sys.c
src/platforms/generic_unix/main.c
src/platforms/rp2040/src/lib/sys.c
src/platforms/stm32/src/lib/sys.c

This change is required for #657.

Make atomvm:add_avm_pack_file/2 return a meaningful error

---

src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf

This change is required in order to implement #657.

NIFs: add atomvm:get_start_beam/1

---

src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h
src/libAtomVM/utils.h

utils: add UNREACHABLE() macro

---

.github/workflows/esp32-build.yaml

CI ESP32 build: update esp-idf versions

---

.github/workflows/esp32-build.yaml
doc/release-notes.md.in
src/platforms/esp32/components/avm_builtins/network_driver.c

ESP-IDF < v4.4 wasn't already supported since #679, however it was still mentioned in documentation, and previous releases were mentioned in few other places.

Completely remove idf < 4.4

---

.github/workflows/build-and-test-macos.yaml

Linux builds rely on setup-beam which is broken for OTP26.

Build and test on macos with OTP24-26

---

libs/estdlib/src/erlang.erl
src/libAtomVM/bif.c
src/libAtomVM/bif.h
src/libAtomVM/bifs.gperf
src/libAtomVM/exportedfunction.h
src/libAtomVM/module.c
src/libAtomVM/module.h
src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_min_max_guard.erl
tests/test.c

Fix compatibility with OTP26 (fix #712)
Also change the way BIFs are imported, so min/2 and max/2 BIFs can be called from code compiled with OTP<26

Implement `min/2` and `max/2` as bifs

---

libs/estdlib/src/gen_server.erl
tests/libs/estdlib/test_gen_server.erl

This PR adds monitoring to `gen_server:call` and `gen_server:stop` to properly handle error and race conditions.

Added monitoring to gen_server:call and gen_server:stop

---

src/libAtomVM/context.c
src/libAtomVM/opcodesswitch.h

Keep lock on processes table when sending monitor messages.
Also acquire lock when printing crash dump, fixing random segfaults.

Fix demonitor flush #716

---

doc/src/programmers-guide.md
src/platforms/esp32/components/avm_builtins/spi_driver.c

Erlang `spi` module was using `mode` as key, but the driver was looking for `spi_mode`, hence it wasn't working (and default value was used).
Also update documentation that was still mentioning `spi_mode`.

SPI: fix `mode` that wasn't working

---

src/libAtomVM/atom.c
src/libAtomVM/atom.h

Fix warnings in atom.c

---

src/libAtomVM/context.c
src/libAtomVM/globalcontext.c
src/libAtomVM/globalcontext.h
tests/erlang_tests/whereis_dead_process.erl

- Unregister before sending DOWN messages
- Unregister all names

Fix unregistration

---

.github/workflows/esp32-build.yaml
src/platforms/esp32/test/esp_ipc_isr_5.1.patch

Fix of bug
https://github.com/espressif/esp-idf/issues/11433 is in v5.0.3 but not in v5.1.

Fix flappiness of tests with esp-idf 5.1

---

src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h
src/libAtomVM/stacktrace.c
src/libAtomVM/stacktrace.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_exception_classes.erl
tests/test.c

* Fix lost class issue when exception is rethrown (fix #713)
* Fix semantic of first parameter of `erlang:raise/3`

Fix handling of exception class

---

tests/erlang_tests/test_sub_binaries.erl

See #723 and #724
We need to garbage collect at the end of each test to make sure ref counted binaries are disposed before `erlang:memory(binary)` is called in next test.
We cannot rely on monitors because the DOWN message is currently sent before the mso list is processed and references are decremented.

Fix flappiness of test_sub_binaries

---

README.Md

- Fix link to wasm readme
- Mention AtomVM runs in browsers

Fix README.Md

---

tests/erlang_tests/test_refc_binaries.erl

In some circumstances, `erlang:memory(binary)` returns the space used by a refc binary from the previous test. Ensure everything is cleaned up by calling gc before sending result.
Monitor wouldn’t help because monitor message is sent before mso is swept.
Also remove useless gc before the test as the process was freshly spawned.

Fix flappiness of test_refc_binaries

---

.github/workflows/build-and-test-macos.yaml
.github/workflows/build-and-test.yaml
.github/workflows/check-formatting.yaml
.github/workflows/codeql-analysis.yaml
.github/workflows/esp32-build.yaml
.github/workflows/esp32-mkimage.yaml
.github/workflows/reuse-lint.yaml

v2 versions are deprecated and GH CI warns about it

Bump actions versions

---

src/platforms/generic_unix/CMakeLists.txt

Enable ENABLE_EXPORTS executable target option which exports all executable symbols, so dlopen doesn't fail when loading a plugin. ENABLE_EXPORTS uses -export-dynamic/-rdynamic.

generic_unix: exports symbols in order to make plugins work

---

src/libAtomVM/context.c

Fix warning introduced in 007d3786c

---

doc/src/atomvm-internals.md
src/platforms/emscripten/CMakeLists.txt
src/platforms/emscripten/src/lib/CMakeLists.txt
src/platforms/emscripten/src/lib/emscripten_sys.h
src/platforms/emscripten/src/lib/smp.c
src/platforms/emscripten/src/lib/sys.c

Enable SMP for emscripten

---

libs/estdlib/src/erlang.erl
tests/erlang_tests/test_dict.erl

Document and add specifications of many nifs and bifs used in standard libraries.
See #701 

Document and add specifications for several nifs and bifs

---

src/libAtomVM/erl_nif.h
src/platforms/esp32/components/avm_sys/CMakeLists.txt
src/platforms/esp32/components/avm_sys/include/esp32_sys.h
src/platforms/esp32/components/avm_sys/sys.c
src/platforms/esp32/test/main/test_erl_sources/CMakeLists.txt
src/platforms/esp32/test/main/test_erl_sources/test_select.erl
src/platforms/esp32/test/main/test_main.c

This is based on a specific select thread loop using esp-idf's `poll(2)`.
Qemu-based test uses a custom simple vfs pipe implementation to demonstrate usage.

Add enif_select support to esp32

---

examples/erlang/esp32/ap_sta_network.erl
examples/erlang/hello_world_server.erl
examples/erlang/system_info_server.erl
libs/eavmlib/src/atomvm.erl
libs/eavmlib/src/console.erl
libs/eavmlib/src/emscripten.erl
libs/eavmlib/src/esp.erl
libs/eavmlib/src/gpio.erl
libs/eavmlib/src/ledc.erl
libs/eavmlib/src/network.erl
libs/eavmlib/src/pico.erl
libs/eavmlib/src/port.erl
libs/estdlib/src/base64.erl
libs/estdlib/src/calendar.erl
libs/estdlib/src/erlang.erl
libs/estdlib/src/gen_server.erl
libs/estdlib/src/gen_statem.erl
libs/estdlib/src/gen_tcp.erl
libs/estdlib/src/gen_udp.erl
libs/estdlib/src/inet.erl
libs/estdlib/src/maps.erl
libs/estdlib/src/math.erl
libs/estdlib/src/timer.erl

Running dialyzer on atomvmlib and examples revealed issues with several types It also revealed bugs in three examples

Fix more types and few examples

---

src/libAtomVM/globalcontext.c

This fixes esp32 tests CI failure

Fix GlobalContext destroy order

---

src/libAtomVM/interop.c
src/libAtomVM/interop.h

This PR adds a function that supports traversal of values (integers and binaries) in an IO list.

Added interop_iolist_fold

---

CMakeModules/BuildErlang.cmake

Add debug info in beams for Dialyzer

---

libs/exavmlib/lib/CMakeLists.txt
libs/exavmlib/lib/Integer.ex
libs/exavmlib/lib/Kernel.ex

closes #426 
closes #427
There is no testing framework setup for elixir so I added the code to examples folder

Add Elixir Integer module

---

libs/eavmlib/src/spi.erl
src/platforms/esp32/components/avm_builtins/spi_driver.c

Return meaningful tagged tuples instead of just `error` atom.
Fixes #656 

ESP32/SPI: informative errors

---

CHANGELOG.md
doc/src/network-programming-guide.md
libs/eavmlib/src/esp.erl
src/platforms/esp32/components/avm_builtins/nvs_nif.c

Return either `{ok, result}` or `error`, instead of `binary()` or `undefined`.

ESP32/NVS: return tagged tuples instead of just the result

---

CHANGELOG.md
doc/src/programmers-guide.md
libs/estdlib/src/crypto.erl
libs/estdlib/src/erlang.erl
src/platforms/esp32/components/avm_sys/CMakeLists.txt
src/platforms/esp32/components/avm_sys/platform_nifs.c
src/platforms/esp32/test/main/test_erl_sources/CMakeLists.txt
src/platforms/esp32/test/main/test_erl_sources/test_crypto.erl
src/platforms/esp32/test/main/test_main.c
src/platforms/generic_unix/lib/platform_nifs.c
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_crypto.erl
tests/test.c

Add support for `crypto:hash/2`

---

examples/erlang/CMakeLists.txt
examples/erlang/hello_world.erl

Hello world example doesn't depend on any library so do not pack it with other avm files.

examples: do not pack any library with hello world

---

libs/CMakeLists.txt

Building plt also checks that current erlang libraries are correct.
The plt is installed but depends on some installed Erlang/OTP beams.

Build and install plt

---

src/platforms/esp32/components/avm_sys/platform_nifs.c

Fix issue related to hash of non iolists

---

libs/estdlib/src/CMakeLists.txt

Compile crypto module

---

doc/src/example-programs.md
src/platforms/emscripten/tests/cypress/e2e/examples.spec.cy.js

Fix cypress test and update doc

---

.gitignore
CMakeLists.txt
CMakeModules/FindDialyzer.cmake
libs/CMakeLists.txt

Do not require dialyzer, skip PLT build in case dialyzer has not been found.

Make dialyzer optional

---

libs/estdlib/src/erlang.erl

Document three missing functions

---

libs/eavmlib/src/esp.erl
src/platforms/esp32/components/avm_builtins/nvs_nif.c

ESP32/NVS: fix typos and other smaller issues

---

README.Md
tests/test-enif.c

As explained in comment, scheduler_terminate should be preferred to context_destroy Also list tests in README

Fix enif test

---

libs/eavmlib/src/esp.erl

Fixes `nvs_get_binary/2` so it can work on devices with a completely erased NVS area.
namespace not found is quite common in a newly flash device, for consistency reasons it should be returned as undefined.

ESP32/NVS: return `namespace_not_found` as `undefined` in get function

---

version.cmake

Bump version to v0.6.0-alpha.1, and set dev to true.
Version number will be something like `v0.6.0-alpha.1+git.abcdef12`.
This is the first maintenance operation just after the tagging.

Prepare v0.6.0-alpha.1 dev cycle

---

CHANGELOG.md
libs/eavmlib/src/esp.erl
version.cmake

In order to execute the NIF, an extern call must be done.

ESP32/NVS: fix nvs_set_binary

---

libs/eavmlib/src/esp.erl
libs/estdlib/src/CMakeLists.txt
libs/estdlib/src/binary.erl
libs/estdlib/src/erlang.erl

Add functions used by examples and more.
Also fix name of `esp:sleep_get_wakeup_cause/0`

Add more missing function stubs

---

src/libAtomVM/resources.c
src/libAtomVM/resources.h
src/platforms/esp32/components/avm_sys/sys.c
src/platforms/generic_unix/lib/sys.c

List of select events could be modified while building or rebuilding the set of poll fd.

Fix concurrency issue with poll and select events

---

src/libAtomVM/nifs.c
src/libAtomVM/synclist.h

This PR prepends the AVM data to the list of AVMs when using the `atomvm: add_avm_pack_file` function.  In so doing, modules in AVM files that are so added are searched first when loading, allowing users to over-ride module definitions in applications (for testing/debugging)

Prepend AVM files that are loaded via add_avm_pack_file

---

.github/workflows/build-and-test-macos.yaml
.github/workflows/build-and-test.yaml
CMakeLists.txt
CMakeModules/BuildErlang.cmake
examples/emscripten/wasm_webserver.erl
libs/CMakeLists.txt
libs/eavmlib/src/atomvm.erl
libs/eavmlib/src/console.erl
libs/esp32boot/esp32init.erl
libs/estdlib/src/binary.erl
libs/estdlib/src/erlang.erl
libs/estdlib/src/lists.erl

Document the following functions:
- atomvm:get_start_beam/1
- atomvm:posix_open/2
- atomvm:posix_open/3
- atomvm:posix_close/1
- atomvm:posix_read/2
- atomvm:posix_write/2
- binary:part/3
- erlang:binary_to_atom/2
- erlang:binary_to_integer/1
Also fix specifications of the following functions:
- wasm_webserver:start/0
- atomvm:add_avm_pack_binary/2
- atomvm:add_avm_pack_file/2
- console:puts/1
- console:puts/2
- console:print/1
- erlang:list_to_binary/1
- lists:join/2
Also fix esp32init
Also make dialyzer a separate target and build plt of libs if dialyzer is found and the plt is needed
Also run dialyzer on runnables if target is built
Also fix rules in BuildErlang.cmake
Public License 2.1 or later" license …

Dialyzer-related fixes and improvements

---

libs/estdlib/src/CMakeLists.txt
libs/estdlib/src/binary.erl
libs/estdlib/src/code.erl
libs/estdlib/src/erlang.erl
libs/estdlib/src/erts_debug.erl
libs/estdlib/src/unicode.erl

Add documentation for:
- code:load_abs/1
- code:load_binary/3
- erlang:is_process_alive/1
- erlang:garbage_collect/0
- erlang:garbage_collect/1
- erlang:link/1
- erlang:unlink/1
Fix specifications for:
- erlang:spawn_opt/2
- erlang:spawn_opt/3
- unicode:characters_to_list/1
- unicode:characters_to_list/2
- unicode:characters_to_binary/1
- unicode:characters_to_binary/2
- unicode:characters_to_binary/3

Document more nifs

---

.github/workflows/esp32-build.yaml

Fix esp32 CI by installing dialyzer

---

CMakeLists.txt

Set AVM_RELEASE to OFF on master branch

---

src/libAtomVM/externalterm.c
src/libAtomVM/nifs.c
src/libAtomVM/posix_nifs.c

- Add a missing handling of errors in external terms when decoding MFA
- Fixed a potential leak in case of errors in nif_atomvm_add_avm_pack_binary
- Fixed a potential leak in case of errors in nif_atomvm_read_priv
- Fixed a potential leak in case of errors in base64_decode
- Raise a badarg if users call atomvm:posix_open/2 with o_creat as open(3) needs three arguments if O_CREAT is passed

Fix few bugs detected by Xcode static analyzer

---

.github/workflows/build-and-test-macos.yaml
.github/workflows/build-and-test-other.yaml
.github/workflows/build-and-test.yaml
.github/workflows/run-tests-with-beam.yaml

Certain build and test workflows are triggered by changes to top level markdown files, like `CHANGELOG.Md` that do not need to run when a feture for another platform is added to the change log, or a README is edited. These changes reduce the number of unnecessary workflow runs.

Prevent certain workflows when top level markdown is changed

---

src/libAtomVM/nifs.c

This could yield a crash with MinimumGrowthHeap strategy

Fix a memory allocation bug in erlang:monitor/2

---

src/libAtomVM/nifs.c

Fix a memory allocation bug in erlang:get_module_info/1

---

libs/estdlib/src/unicode.erl
src/libAtomVM/bitstring.c
src/libAtomVM/bitstring.h
src/libAtomVM/interop.c
src/libAtomVM/term_typedef.h
tests/erlang_tests/test_unicode.erl

Also fix implementation of unicode:characters_to_list/2 with latin1 encoding and non-latin1 characters

Fix compiler warnings around unicode functions

---

doc/src/build-instructions.md

Small fix in ESP32 build instructions

---

src/platforms/stm32/src/main.c

Fixes a depreciation warning for `rcc_clock_setup`, changes some configuration setting to correct for clock drift in `sys_monotonic_millis()`.

Update clock setup on stm32 platform

---

src/platforms/rp2040/CMakeLists.txt
src/platforms/rp2040/src/CMakeLists.txt

Pico SDK doesn't have idf.py monitor which allows to be connected from the boot. Instead, it has an option that waits for an USB serial connection before starting. Add a built-time setting to enable this feature.

Add build-time option for Pico to wait for a USB connection

---

.github/workflows/publish-docs.yaml

Also remove useless second installation of Erlang/OTP in documentation workflow

Bump OTP and Elixir versions in documentation workflow

---

.gitignore

Add entries to gitignore

---

libs/eavmlib/src/emscripten.erl

Fix small typo in documentation

---

CHANGELOG.md
doc/src/build-instructions.md
src/platforms/stm32/CMakeLists.txt
src/platforms/stm32/cmake/libopencm3.cmake
src/platforms/stm32/src/lib/CMakeLists.txt
src/platforms/stm32/src/lib/avm_log.h
src/platforms/stm32/src/lib/sys.c
src/platforms/stm32/src/main.c

Introduces configureable logging with maximum log level, optional colorization by level, and optional source file and line numers with log messages (always on for `ERROR` messages), as described in stm32 section of `Build Instructions`.

Improved logging on stm32 platform

---

src/libAtomVM/globalcontext.c
src/libAtomVM/module.c
src/libAtomVM/module.h
src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h
src/libAtomVM/stacktrace.c
src/platforms/emscripten/src/main.c

Cache last module in scheduler loop to reduce lookups of modules by index
Also fix a bug in stacktraces where the lock was not held
Also remove pointer to GlobalContext from modules
This optimization, in addition to PRs #766, #770, #771 and #772, brings an additional gain of 2-3% on Sudoku benchmark

Reduce lock contention on GlobalContext.module_locks

---

CHANGELOG.md
libs/estdlib/src/lists.erl
tests/libs/estdlib/test_lists.erl

Also add specification for lists:sort/2.

Add lists:usort/2,3

---

.github/workflows/build-and-test-macos.yaml
.github/workflows/build-and-test-other.yaml
.github/workflows/build-and-test.yaml
.github/workflows/check-formatting.yaml
.github/workflows/codeql-analysis.yaml
.github/workflows/esp32-build.yaml
.github/workflows/esp32-mkimage.yaml
.github/workflows/pico-build.yaml
.github/workflows/publish-docs.yaml
.github/workflows/reuse-lint.yaml
.github/workflows/run-tests-with-beam.yaml
.github/workflows/stm32-build.yaml
.github/workflows/wasm-build.yaml

This cancels workflows on successive pushes except on master branch. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency

Setup concurrency group for workflows

---

.github/workflows/pico-build.yaml
CHANGELOG.md
doc/src/build-instructions.md
src/platforms/esp32/test/main/test_erl_sources/CMakeLists.txt
src/platforms/rp2040/src/lib/platform_nifs.c
src/platforms/rp2040/src/lib/smp.c
src/platforms/rp2040/src/lib/sys.c
src/platforms/rp2040/src/main.c
src/platforms/rp2040/tests/CMakeLists.txt
src/platforms/rp2040/tests/test_erl_sources/CMakeLists.txt
src/platforms/rp2040/tests/test_erl_sources/test_clocks.erl
src/platforms/rp2040/tests/test_erl_sources/test_smp.erl
src/platforms/rp2040/tests/test_main.c

Fix a bug where setting the time with RTC wouldn't set system time.
Also fix a bug with avm_data revealed by new tests.
Also skip unused install step when building host AtomVM for esp32 tests.

Fix `monotonic_time/1` and `system_time/1` with pico (fix #786)

---

CHANGELOG.md
libs/eavmlib/src/esp.erl
src/platforms/esp32/components/avm_sys/platform_nifs.c

Also add esp:deep_sleep/0 that deep sleeps with no timer

Add esp:sleep_enable_ulp_wakeup/0

---

src/libAtomVM/opcodesswitch.h

FP and X registers are currenltly limited to MAX_REG which is 16. Enforce limitation while decoding and take advantage of this to optimize execution.
This brings a 6% speed increase on pi_test benchmark (with esp32 idf 4.4)

Optimize decoding of registers

---

CHANGELOG.md
doc/src/programmers-guide.md
libs/estdlib/src/crypto.erl
src/libAtomVM/interop.h
src/platforms/esp32/components/avm_sys/platform_nifs.c
src/platforms/esp32/test/main/test_erl_sources/test_crypto.erl

This PR introduce `crypto:crypto_one_time/4,5` for handling AES with ECB/CBC/CTR/CFB.

ESP32: add support for `crypto:crypto_one_time/4,5` (using mbedtls)

---

src/platforms/rp2040/tests/CMakeLists.txt

Fix pico build (fix #819)

---

libs/estdlib/src/crypto.erl

Fix crypto_one_time compiler warnings

---

doc/src/memory-management.md
doc/src/programmers-guide.md

Fix name of heap growth option, add links

---

doc/src/programmers-guide.md

Fixes a formatting error in the options table of the `Spawning Processes` section of the `Programmers Guide`.

Documentation fix for spawn options table

---

CHANGELOG.md
src/platforms/stm32/src/lib/CMakeLists.txt
src/platforms/stm32/src/lib/platform_nifs.c
src/platforms/stm32/src/lib/stm_sys.h
src/platforms/stm32/src/lib/sys.c
src/platforms/stm32/src/main.c

Adds support for `REGISTER_PORT_DRIVER` and `REGISTER_NIF_COLLECTION` macros to stm32 platform.

Improve nif and port support for stm32

---

.github/workflows/build-docs.yaml
.github/workflows/publish-docs.yaml
doc/CMakeLists.txt
doc/conf.py.in

Changes the documentation publishing CI to create documentaion trees based on tags, rather than the old method based on branches.

Publish documentation for tag releases

---

CHANGELOG.md
doc/src/programmers-guide.md
libs/eavmlib/src/atomvm.erl
src/libAtomVM/CMakeLists.txt
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf

Add support for `atomvm:posix_clock_settime/2`

---

CHANGELOG.md
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/int64_build_binary.erl
tests/test.c

Just replace `avm_int_t` with `avm_int64_t` which is always a 64-bit integer.
Fixes #827 

Fix bug in bs_create_bin

---

CHANGELOG.md

Fix entries in CHANGELOG that were wrongly under 0.6.0-alpha.0

---

src/libAtomVM/posix_nifs.c

Fix posix errno conditionals

---

src/libAtomVM/nifs.c

Fix warning introduced in 74e68af

---

.github/workflows/build-and-test-macos.yaml
.github/workflows/build-and-test.yaml
CHANGELOG.md
doc/src/getting-started-guide.md
src/platforms/generic_unix/atomvm
src/platforms/generic_unix/main.c

This PR adds help and version support for the AtomVM command on the generic unix platform.
This PR addresses Issue #842 

Add `-h` and `-v` flags to generic_unix AtomVM command

---

examples/erlang/rp2040/CMakeLists.txt

The modules are already included in atomvmlib.uf2

Remove duplicated dependencies in pico examples

---

.github/workflows/esp32-build.yaml
.github/workflows/esp32-mkimage.yaml
.github/workflows/pico-build.yaml
.github/workflows/publish-docs.yaml
.github/workflows/stm32-build.yaml
.github/workflows/wasm-build.yaml

There is no need to run esp32-mkimage when pico-build.yaml is changed and so on.

CI: avoid running all workflows for just one changed

---

.github/workflows/pico-build.yaml

Use ${{ ... }} for expressions and single quotes.

Fix pico-build workflow

---

CHANGELOG.md
UPDATING.md
doc/src/network-programming-guide.md
libs/eavmlib/src/network.erl

Remove esp32 specific code from network

---

UPDATING.md
src/platforms/esp32/main/main.c

This PR removes the check for the `lib.avm` partition on the ESP32.  The `lib.avm` partition no longer exists, so there is no need for this check.  Moreover, without this fix, potentially misleading information is printed to the console, e.g.,
```
W (894) sys: AVM partition not found for lib.avm
I (894) AtomVM: Unable to mount lib.avm partition. Hopefully the AtomVM core libraries are included in your application.
```

Remove check for lib.avm in esp32 main

---

CHANGELOG.md
src/platforms/esp32/components/avm_builtins/spi_driver.c

Use SPI_DMA_CH_AUTO instead of 1 if model != ESP32. This might be a temporary workaround and a proper fix should be investigated.
Fixes #831 

ESP32: fix SPI on all other ESP32 models, such as ESP32S3

---

doc/src/getting-started-guide.md

Update and improve documentation for WebAssembly port

---

.github/workflows/wasm-build.yaml

Publish missing wasm file

---

libs/esp32boot/esp32init.erl

Fix handling of application loading failure.
It was failing due to a missing case clause for `{app_fail,_}`.

ESP32 init: fix devmode

---

src/platforms/esp32/components/avm_builtins/network_driver.c

Fix a leak that only happened when provided PSK was too short.

Fix memory leak in esp32 network driver

---

src/platforms/rp2040/src/lib/networkdriver.c

Fix Pico (non-W) build

---

CHANGELOG.md
src/platforms/rp2040/src/lib/CMakeLists.txt
src/platforms/rp2040/src/lib/networkdriver.c

Use a DHCP server that is bundled with Pico SDK (btstack)
The DHCP server unfortunatley has no callback so we cannot implement the network driver callback yet.
There still is no DNS server and no router.
Also fix a bug where the default SSID name was atomvm-000000000000 because the MAC address wasn't set. Workaround consists in always enabling STA mode.

Add DHCP server to Pico-W in AP mode

---

.github/workflows/build-and-test-on-freebsd.yaml

Add build-and-test CI for FreeBSD

---

.github/workflows/esp32-mkimage.yaml

Matching CI version in #871. Previously the CI/mkimage versions were out of sync.

Update to esp-idf 4.4.6 in mkimage

---

src/libAtomVM/context.c
tests/test-enif.c

When monitors down handlers were called, the processes table was locked. Yet, monitor down handler might uncarefully need to lock this table, for example to decrement a refc-binary that would be a resource with a down handler.

Fix a bug in resource monitors yielding a deadlock-caused abort

---

.github/workflows/build-and-test-on-freebsd.yaml

Add a timeout to the freebsd CI, to prevent runaway jobs

---

src/platforms/esp32/components/avm_sys/include/esp32_sys.h
src/platforms/esp32/components/avm_sys/sys.c
src/platforms/rp2040/src/lib/rp2040_sys.h
src/platforms/rp2040/src/lib/sys.c
src/platforms/stm32/src/lib/stm_sys.h
src/platforms/stm32/src/lib/sys.c

This fixes the typo resove -> resolve across all platforms.

Fix typo in function name `nif_collection_resove_nif_cb`

---

src/libAtomVM/module.c
src/libAtomVM/module.h
src/libAtomVM/opcodesswitch.h
src/libAtomVM/stacktrace.c

Also mark code in modules as const.
This optimization brings an additional 20% speed upgrade to the Sudoku
benchmark.

Use a pointer for PC instead of an instruction counter 

---

src/libAtomVM/opcodesswitch.h

Define sets of opcodes per versions of OTP compiler

---

CHANGELOG.md
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_guards_do_not_raise.erl
tests/erlang_tests/test_map.erl
tests/test.c

Fix bug where guards would raise exceptions (fix #779)

---

.github/workflows/build-and-test-macos.yaml
.github/workflows/build-and-test-other.yaml
.github/workflows/build-and-test.yaml
.github/workflows/codeql-analysis.yaml
.github/workflows/run-tests-with-beam.yaml

Updates several workflows to accomodate the file decriptor change in markdown files from `.Md` to `.md`.

Update workflow restictions

---

src/libAtomVM/opcodesswitch.h

Remove dead code loading code

---

.github/workflows/build-and-test-other.yaml
CHANGELOG.md
src/libAtomVM/iff.c
src/libAtomVM/utils.h

Make big endian archs work

---

doc/src/programmers-guide.md

current code anchor links #./build-instructions.html, and thus doesn't work.
see https://www.atomvm.net/doc/master/programmers-guide.html#rtc-memory
this fixes that.

Doc fix broken link .html->.md

---

CHANGELOG.md
src/platforms/stm32/src/lib/stm_sys.h
src/platforms/stm32/src/lib/sys.c
src/platforms/stm32/src/main.c

Enables flash cache and i-cache with branch prediction for modest to significant boosts in performance, depending on workloads.

Enable STM32 flash and instruction caches

---

.github/workflows/pico-build.yaml
src/platforms/rp2040/src/lib/platform_smp.h
src/platforms/rp2040/src/lib/rp2040_sys.h
src/platforms/rp2040/src/lib/sys.c
src/platforms/rp2040/tests/package-lock.json
src/platforms/rp2040/tests/package.json
src/platforms/rp2040/tests/run-tests.ts
src/platforms/rp2040/tests/test_erl_sources/CMakeLists.txt

Fix a bug in the implementation where the spinlock was allocated and released within smp_atomic_compare_exchange_weak, thus implementation was effectively only disabling interrupts on the executing core

Fix implementation of smp_atomic_compare_exchange_weak on Pico

---

.github/workflows/stm32-build.yaml

This will speed up the test process for stm32 by caching the ARM toolchain and cloned and compiled `libopencm3` build dependencies.

STM32 CI workflow improvement: cache toolchian and compiled libopencm3

---

.github/workflows/build-docs.yaml
.github/workflows/publish-docs.yaml

Fixes incorrect conditional checks for downloading the extra tools to build the documentation. Previously the tools were always downloaded, even when they were restored from a valid cache.

Fix broken cache in documentation workflows

---

src/libAtomVM/opcodesswitch.h

It brings a significant speed improvement by avoiding processing label opcodes during execution.

Optimize by registering labels to the instruction that follows the label

---

doc/src/atomvm-tooling.md
doc/src/index.rst

This PR adds a chapter on various tools used by developers for building and flashing AtomVM applications.

Added tooling documentation

---

src/libAtomVM/opcodesswitch.h

Abort on a decode we dont support

---

src/platforms/stm32/src/lib/gpio_driver.c
src/platforms/stm32/src/lib/sys.c

This PR fixes few issues introduced with #836.

STM32 GPIO driver fixes

---

src/libAtomVM/externalterm.c
src/libAtomVM/globalcontext.c
src/libAtomVM/opcodesswitch.h
src/platforms/esp32/components/avm_builtins/network_driver.c
src/platforms/esp32/components/avm_sys/platform_nifs.c
src/platforms/generic_unix/lib/platform_nifs.c
src/platforms/stm32/src/lib/gpio_driver.c

`IS_NULL_PTR(ptr)` is already defined as `UNLIKELY(x == NULL)`.

`UNLIKELY(IS_NULL_PTR(ptr))` -> `IS_NULL_PTR(ptr)`

---

src/platforms/rp2040/tests/test_erl_sources/test_clocks.erl

Add a sleep to fix an issue where, supposedly, emulator was synchronizing system time with RTC and the test randomly failed.
The test was successfully ran 8 times (4 x 2), including 2 triggered by this PR.

Fix flappiness of Pico clock test on CI

---

src/libAtomVM/term.h
tests/erlang_tests/test_sub_binaries.erl

Fix a bug where sub-binaries of sub-binaries were reallocated, thus wasting memory.

Make sub-binaries of sub-binaries sub-binaries

---

.github/workflows/build-docs.yaml
.github/workflows/build-libraries.yaml
.github/workflows/build-linux-artifacts.yaml
.github/workflows/esp32-mkimage.yaml
.github/workflows/pico-build.yaml
.github/workflows/publish-docs.yaml
.github/workflows/wasm-build.yaml

Tag filter in several workflows meant any tag that doesn't contain a /. We probably wanted every tag.
And if we have a filter on a tag but no filter on branches, the workflow is only executed when a tag matches, regardless of path filtering which are always ignored on tags.
Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-branches-and-tags

Fix logic of workflows on push

---

CHANGELOG.md
libs/eavmlib/src/gpio.erl
src/platforms/rp2040/src/lib/gpiodriver.c

Modifies the Pico gpio dirver to accept atoms for the special wl_gpio pins present in the Pico-W.
- Adds support for `{wl, 0..1}` as output pins in `gpio:digital_write/2`.
- Adds support for `{wl, 2}` as an input pin in `gpio:digital_read/1`.
- Raises error `badarg` instead of returning `error`

Enhancements to Pico(W) gpio driver

---

src/libAtomVM/otp_socket.c

Add missing comments on otp_socket function

---

src/libAtomVM/otp_socket.c
src/libAtomVM/otp_socket.h

const ip_addr_t * passed to udp_recv callback is not valid after the callback returns. Store the IPv4 address accordingly.

Fix a bug where recvfrom would eventually return address 0.0.0.0

---

src/libAtomVM/otp_socket.c

Fix a bug where connect wouldn't work because the socket state was not updated Also cleanup code to replace a large series of if with a switch

OTP Socket lwIP: fix TCP connect

---

src/platforms/stm32/src/lib/sys.c

During the PR review and snd subsequent bug fixes the code required for `sys_platform_init` was inadvertantly dropped.
Closes #915

Fix STM32 GPIO driver Issue #915

---

libs/estdlib/src/socket.erl
src/libAtomVM/otp_socket.c
src/libAtomVM/otp_socket.h
src/platforms/rp2040/src/lib/lwipopts.h
tests/libs/estdlib/test_tcp_socket.erl

Fix logic as apparently lwIP doesn't allow for delaying accept (SYN-ACK), so accept_cb is treated like recv_cb, incoming connections are enqueued
Also simplify nif_select_read as we're always selecting for ourselves

Fix listen backlog with OTP Socket lwIP

---

libs/eavmlib/src/logger_manager.erl
tests/libs/estdlib/test_logger.erl

This change set allows users to use logging macros and functions in code, but for those calls not to fail with an error if the logger manager has not been instantiated.
Users must still instantiate the logger manager (or it is instantiated automatically as part of the kernel application, TBD) in order for logs to pass the initial allow phase, but all logs will be silently dropped until the EAVMLib logger manager is instaniated.

Allow use of logging macros without instantiating the logger manager

---

.github/workflows/build-and-test-on-freebsd.yaml

cc @fadushin - uses https://github.com/cross-platform-actions/action

Freebsd CI fix

---

CHANGELOG.md
doc/src/programmers-guide.md
libs/estdlib/src/CMakeLists.txt
libs/estdlib/src/net.erl
src/libAtomVM/interop.c
src/libAtomVM/interop.h
src/libAtomVM/otp_net.c
src/libAtomVM/otp_net.h
src/libAtomVM/term.h
src/platforms/esp32/components/avm_builtins/CMakeLists.txt
src/platforms/esp32/components/avm_builtins/Kconfig
src/platforms/esp32/components/avm_builtins/otp_net_platform.c
src/platforms/esp32/components/avm_sys/CMakeLists.txt
src/platforms/generic_unix/lib/CMakeLists.txt
src/platforms/generic_unix/lib/platform_nifs.c
src/platforms/generic_unix/lib/sys.c
tests/libs/estdlib/CMakeLists.txt
tests/libs/estdlib/test_net.erl
tests/libs/estdlib/tests.erl

This PR adds support for the `net:getaddrinfo/1,2` family of functions.
Addresses Issue #902 

Add support for net:getaddrinfo/1,2

---

src/libAtomVM/inet.c
src/libAtomVM/inet.h
src/libAtomVM/otp_net.c
src/libAtomVM/otp_socket.c
src/libAtomVM/otp_socket.h
src/libAtomVM/term.h
src/platforms/esp32/components/avm_sys/CMakeLists.txt
src/platforms/generic_unix/lib/CMakeLists.txt
src/platforms/rp2040/src/lib/CMakeLists.txt
src/platforms/rp2040/src/lib/otp_net_lwip_raw.c
src/platforms/rp2040/src/lib/otp_net_lwip_raw.h

Add support for net:getaddrinfo/1,2 on Pico-W

---

src/libAtomVM/otp_net.c

Fixes FreeBSD build due to missing include

Fix for broken FreeBSD build

---

.github/workflows/check-formatting.yaml
src/libAtomVM/memory.c
src/libAtomVM/refc_binary.c
src/platforms/emscripten/src/lib/platform_nifs.c
src/platforms/rp2040/src/lib/platform_nifs.c
tests/test.c

Also updated files with format violations.
Addresses issue #848 

Update clang format to version 16

---

src/libAtomVM/otp_net.c
src/platforms/esp32/test/main/test_erl_sources/CMakeLists.txt
src/platforms/esp32/test/main/test_erl_sources/test_net.erl
src/platforms/esp32/test/main/test_main.c

Fix a memory allocation bug
Optimize memory allocation by using shared maps
Work around an issue of esp-idf's implementation of getaddrinfo that does not fill protocol and socket type and returns a larger address record
Add an esp32 qemu test for net:getaddrinfo/1,2

Fix `net:getaddrinfo/1,2` on ESP32

---

examples/erlang/esp32/tcp_client_esp32.erl
examples/erlang/esp32/tcp_server_blink.erl
examples/erlang/esp32/udp_server_blink.erl
examples/erlang/tcp_client.erl
examples/erlang/tcp_server.erl
examples/erlang/udp_client.erl
examples/erlang/udp_server.erl

This change set makes the following improvements to the example programs:
* Fixes formatting of peer and local addresses so that strings are properly displayed
* Removed some old code that used NVS credentials (no longer supported)
* Removes use of `localhost` as an address, which is technically not supported by the spec
* Replaced unicode packet <<":アトムＶＭ">> with <<"AtomVM">> so that it renders properly on the console

Clean up example programs

---

.github/workflows/build-and-test-on-freebsd.yaml

Bump cross-platform-actions/action to v0.21.1.
Use qemu hypervisor, for improved stability, but less speed.
Proper mem config + minor improvements.

CI improve FreeBSD

---

libs/estdlib/src/lists.erl
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
src/libAtomVM/opcodesswitch.h
src/libAtomVM/term.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_lists_reverse.erl
tests/libs/estdlib/test_lists.erl
tests/test.c

This nif does not need to be updated after #795 is merged.
Also rewrite several lists module functions to not use this nif, either because
it was not necessary (`lists:seq/2,3`) or because a non-tail recursive loop
is more efficient memory-wise. 

Implement `lists:reverse/1,2` as nif

---

libs/estdlib/src/lists.erl

Fixed doc build

---

CHANGELOG.md
src/platforms/generic_unix/lib/sys.c
tests/libs/eavmlib/test_file.erl

On platforms with poll (Linux), the list of fds was not properly built and as a result, the VM could loop without processing selected fds

Fix a bug in handling listeners and sockets on platforms with poll

---

src/libAtomVM/opcodesswitch.h

Fix trace with bs_create_bin/6

---

src/libAtomVM/otp_crypto.c
src/platforms/esp32/test/main/test_erl_sources/test_crypto.erl

Follow Erlang/OTP and allow calling ciphers that do not require an IV with an IV.

Simplify crypto code and fix compatibility issue with Erlang/OTP

---

.github/workflows/stm32-build.yaml
CHANGELOG.md
doc/release-notes.md.in
doc/src/atomvm-tooling.md
doc/src/build-instructions.md
doc/src/getting-started-guide.md
src/platforms/stm32/CMakeLists.txt
src/platforms/stm32/cmake/arm-toolchain.cmake
src/platforms/stm32/cmake/atomvm_dev_config.cmake
src/platforms/stm32/cmake/compile-flags.cmake
src/platforms/stm32/cmake/libopencm3.cmake
src/platforms/stm32/src/lib/CMakeLists.txt
src/platforms/stm32/src/lib/avm_devcfg.h
src/platforms/stm32/src/main.c
src/platforms/stm32/tools/atomvm_stm32_config_query.erl
src/platforms/stm32/tools/device_config.hrl

Configures main system clock and flash size based on the target device.
The console uart may be configured by using the `-DAVM_CFG_CONSOLE=` option, or
for Nucleo devices the on board TTL->USB-COM can be configured with the
`-DBOARD=nucleo` cmake option. Previously these values were hard coded in the C
sources and needed to be changed manually if a device other than the default
target was used.
Closes #454

Correctly configure STM32 devices from cmake options

---

libs/estdlib/src/logger_std_h.erl

Turns out we had forgotten to include file and line information in the standard logger.  This adds it in, which can be helpful in locating log information.

Log file and line numbers when available in the standard logger

---

src/libAtomVM/otp_crypto.c

Use term_binary_heap_size for exact size calculation before ensuring memory.

otp_crypto: make sure ensure heap size includes binary header

---

CHANGELOG.md
src/platforms/esp32/components/avm_builtins/uart_driver.c

Include `source_clk` field in the `uart_config_t` struct for ESP-IDF >= 5.0 to address compatibility error.
The issue arises due to a missing `source_clk` field in the `uart_config_t` struct in `uart_driver_create_port`.
In versions prior to ESP-IDF 5.0, this field was not required (tested against 4.4.6), but its absence in later versions leads to the following error at runtime : `uart: uart_param_config(748): Invalid src_clk`.
The choice of UART_SCLK_DEFAULT was made to allow for automatic selection of the appropriate clock source.
Open to feedback or suggestions for any improvements or alternative approaches.
SPDX-License-Identifier: Apache-2.0 OR …

Fix ESP32 UART configuration for ESP-IDF >= 5.0

---

CHANGELOG.md
src/platforms/stm32/CMakeLists.txt

The FPU on stm32f4 and stm32f7 devices is single precision, changing the default to `AVM_USE_32BIT_FLOAT=on` enables the use of accelerated floating point calculations on these devices.  When we can extend support to the stm32h7 series those devices should have `AVM_USE_32BIT_FLOAT=off` by defalt, as they have an on board FPU with double precision support.
For reference, the times for the `pi_test` from atomvm_benchmarks can clearly show the benefits of making this change. (times are measured in uSecs, tested on Nucleo-f429zi - 180Mhz)
`AVM_USE_32BIT_FLOAT=off`
pi_test: 26410000
`AVM_USE_32BIT_FLOAT=on`
pi_test: 17922000
SPDX-License-Identifier: …

Enable STM32 FPU for floating point calculations

---

CHANGELOG.md
src/platforms/emscripten/src/lib/platform_nifs.c

Fix an issue where second argument (x[1]) was incorrectly processed when register_callback/1 was called

Fix emscripten register callback crash

---

libs/estdlib/src/io_lib.erl
tests/libs/estdlib/test_io_lib.erl

Fix encoding of atoms with format

---

CHANGELOG.md
src/libAtomVM/scheduler.c
src/libAtomVM/sys.h
src/platforms/emscripten/src/lib/sys.c
src/platforms/esp32/components/avm_sys/sys.c
src/platforms/generic_unix/lib/sys.c
src/platforms/rp2040/src/lib/sys.c
src/platforms/rp2040/tests/package-lock.json
src/platforms/rp2040/tests/package.json
src/platforms/rp2040/tests/test_erl_sources/test_clocks.erl
src/platforms/stm32/src/lib/avm_log.h
src/platforms/stm32/src/lib/sys.c

Fix a bug where truncation of system time would yield incoherent time measurement, as seen in flappy CI test with Pico.
Also fix a bug where late timers would eventually be ignored.
Eventually clean up promotion of integers in timers by using stdint.h uint_least64_t type instead of suffixes on constants.
List in #724 is old, yet this probably fixes the time out issue we had with several platforms.

Fix precision of time used in timers

---

src/libAtomVM/CMakeLists.txt
src/libAtomVM/nifs.c
src/platforms/emscripten/src/main.c
src/platforms/esp32/main/main.c
src/platforms/generic_unix/main.c
src/platforms/rp2040/src/main.c
src/platforms/stm32/src/main.c

In order to allow building Zepher OS ports the `version.h` file needs to be renamed to avoid a collision with the `version.h` header file that part of the zepher core libraries included in all zephyr builds.

Rename version.h to avm_version.h

---

.github/workflows/build-and-test-macos.yaml

Due to the outdated OS version, Homebrew ends up having to build most of the dependencies instead of installing them from bottles.
This change cuts the build time of dependencies from around 40 minutes to around 4 minutes.

Update macos CI to run on Ventura and trim updates on Homebrew dependencies

---

.github/workflows/esp32-build.yaml

CI: update esp-idf 5.1.x to 5.1.2

---

src/libAtomVM/interop.h

Fix a C++ illegal pointer cast ESP IDF 5.1 doesn't like

---

src/libAtomVM/externalterm.c

`size_t < uint8_t + constant` causes a warning due to promotion of `uint8_t + constant` to int.

externalterm: fix a warning related to integer promotion

---

src/libAtomVM/externalterm.c

Just fix one more sign with `?` operator related warning, and rename macro for clarity.

externalterm: fix SIGNED_INT_TO_UNSIGNED warning

---

src/libAtomVM/debug.c
src/libAtomVM/term.h

Fix signed/unsigned warnings and use a better type for function returning bytes or terms.

Fix some warnings by using size_t where it makes sense

---

src/libAtomVM/CMakeLists.txt
src/platforms/esp32/components/libatomvm/CMakeLists.txt

Introduce new `AVM_PEDANTIC_WARNINGS` cmake option and set it to ON on ESP32.

Allow disabling pedantic GCC flag

---

.github/workflows/build-and-test-macos.yaml
.github/workflows/build-and-test-other.yaml
.github/workflows/build-and-test.yaml
.github/workflows/build-libraries.yaml
.github/workflows/build-linux-artifacts.yaml
.github/workflows/run-tests-with-beam.yaml
CHANGELOG.md
libs/eavmlib/src/atomvm.erl
src/libAtomVM/otp_crypto.c
src/libAtomVM/sys_mbedtls.h
src/platforms/esp32/components/avm_sys/include/esp32_sys.h
src/platforms/esp32/components/avm_sys/sys.c
src/platforms/generic_unix/lib/CMakeLists.txt
src/platforms/generic_unix/lib/platform_nifs.c
src/platforms/generic_unix/lib/sys.c
src/platforms/rp2040/src/lib/rp2040_sys.h
src/platforms/rp2040/src/lib/sys.c
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_atomvm_random.erl
tests/erlang_tests/test_crypto_strong_rand_bytes.erl
tests/test.c

Do not depend both on Mbed-TLS and OpenSSL at the same time, just use Mbed-TLS.
Also now the  same code base can be both used on generic unix and MCUs.
Closes #950 

Remove OpenSSL

---

.github/workflows/build-linux-artifacts.yaml
CMakeModules/MbedTLS.cmake

Also build x86_64 artifact with builtin (static linked) mbedtls.

Static mbedtls x86_64 build

---

src/platforms/esp32/components/avm_builtins/i2c_driver.c

Fix a crash related to i2c close

---

.github/workflows/esp32-build.yaml
.github/workflows/esp32-mkimage.yaml
src/platforms/esp32/components/avm_builtins/gpio_driver.c
src/platforms/esp32/components/avm_builtins/spi_driver.c

Add support for esp32c6

---

doc/src/programmers-guide.md
libs/estdlib/src/crypto.erl

Document `crypto:strong_rand_bytes/1`

---

.github/workflows/esp32-mkimage.yaml

Fix esp32 mkimage matrix by only generating 5.1.2 images

---

libs/estdlib/src/CMakeLists.txt
libs/estdlib/src/gen_tcp.erl
libs/estdlib/src/gen_tcp_inet.erl
libs/estdlib/src/gen_tcp_socket.erl
libs/estdlib/src/gen_udp.erl
libs/estdlib/src/gen_udp_inet.erl
libs/estdlib/src/gen_udp_socket.erl
libs/estdlib/src/inet-priv.hrl
libs/estdlib/src/inet.erl
src/platforms/esp32/components/avm_builtins/socket_driver.c
src/platforms/esp32/components/avm_sys/include/otp_socket_platform.h
src/platforms/esp32/test/main/test_erl_sources/test_socket.erl
src/platforms/generic_unix/lib/otp_socket_platform.h
src/platforms/generic_unix/lib/socket_driver.c
src/platforms/rp2040/src/lib/otp_socket_platform.h
tests/libs/estdlib/test_gen_tcp.erl
tests/libs/estdlib/test_gen_udp.erl

This PR adds the ability to use the `gen_tcp` and `gen_udp` interfaces using the OTP socket interface as a "back-end", eliminating the need for the native C drivers on generic_unix and ESP32.
Using the feature also allows use of the `gen_tcp` and `gen_udp` interfaces on the rp2040 platform.
This feature is still considered "experimental" and therefore is not currently documented.  However, the configuration APIs follow the OTP `inet_backend` configuration option introduced in OTP-23.
This PR addresses issue #893 

Opt-in purerlang implementation of gen_tcp and gen_udp using socket API

---

libs/eavmlib/src/esp.erl
src/platforms/esp32/components/avm_sys/platform_nifs.c
src/platforms/esp32/test/main/test_erl_sources/CMakeLists.txt
src/platforms/esp32/test/main/test_erl_sources/test_twdt.erl
src/platforms/esp32/test/main/test_main.c

Add support for esp_task_wdt API

---

CHANGELOG.md
version.cmake

Prepare v0.6.0-beta.0 dev cycle

---

CHANGELOG.md
libs/eavmlib/src/esp.erl
src/platforms/esp32/components/avm_sys/platform_nifs.c

Add `get_default_mac` function to retrieve the default MAC address from the EFUSE block of the ESP32 chip. This function utilizes the `esp_efuse_mac_get_default` API to access the factory-programmed MAC address.

Implement `esp:get_default_mac/0` based on `esp_efuse_mac_get_default`

---

tests/test.c

Fix "error: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’".

tests: check chdir return value in order to fix a warning

---

src/libAtomVM/bif.c
src/libAtomVM/term_typedef.h

clang was reporting:
`error: implicit conversion from 'long' to 'double' changes value from 9223372036854775807 to 9223372036854775808
[-Werror,-Wimplicit-const-int-float-conversion]`
This change fixes that warning.
Also, there was an (unlikely) overflow with functions such as `erlang:ceil/1`, since the check was wrong due to that precision loss.

Fix clang warning and potential overflow

---

src/platforms/stm32/cmake/compile-flags.cmake

They make too much noise, making hard to spot relevant issues.

STM32: remove all additional warning switches

---

.github/workflows/build-and-test-macos.yaml
.github/workflows/build-and-test-on-freebsd.yaml
.github/workflows/build-and-test-other.yaml
.github/workflows/build-and-test.yaml
.github/workflows/pico-build.yaml
.github/workflows/stm32-build.yaml
.github/workflows/wasm-build.yaml
src/libAtomVM/CMakeLists.txt

Enable `-Werror` when safe

---

CHANGELOG.md
doc/src/programmers-guide.md
examples/erlang/esp32/sx127x.erl
libs/eavmlib/src/spi.erl
src/platforms/esp32/components/avm_builtins/spi_driver.c

Make names shorter and clearer, with no additional clutter.
Closes #651 

SPI: API renames

---

CHANGELOG.md
doc/src/programmers-guide.md
examples/elixir/esp32/SHT31.ex
examples/erlang/esp32/sht31.erl
libs/eavmlib/src/i2c.erl
libs/exavmlib/lib/I2C.ex
src/platforms/esp32/components/avm_builtins/i2c_driver.c

I2C API renames
