atomvm/AtomVM

examples/elixir/stm32/Blink.ex
examples/elixir/stm32/Blinker.ex
examples/elixir/stm32/README.md
examples/elixir/stm32/build.sh
src/platforms/stm32/.gitignore
src/platforms/stm32/CMakeLists.txt
src/platforms/stm32/README.md
src/platforms/stm32/cmake/arm-toolchain.cmake
src/platforms/stm32/cmake/compile-flags.cmake
src/platforms/stm32/cmake/libopencm3.cmake
src/platforms/stm32/src/gpiodriver.c
src/platforms/stm32/src/gpiodriver.h
src/platforms/stm32/src/main.c
src/platforms/stm32/src/platform.c
src/platforms/stm32/src/sys.c

Add STM32 to platforms

---

libs/estdlib/console.erl

Missed a change from previous commit.

Fixed documentation for console module

---

doc/atomvm-memory.md
src/libAtomVM/debug.c
src/libAtomVM/debug.h
src/libAtomVM/nifs.c
src/libAtomVM/term.c
src/libAtomVM/term.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_list_gc.erl
tests/test.c

This change set includes the following changes:
* Added functionality for debugging (stderr) heap and registers, in addition to the stack
* Added documentation of AtomVM memory management
* Added test case for garbage collection in list handling

Documentation and debugging improvements.

---

src/libAtomVM/context.c
src/libAtomVM/context.h
src/libAtomVM/defaultatoms.c
src/libAtomVM/defaultatoms.h
src/libAtomVM/nifs.c
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_min_heap_size.erl
tests/erlang_tests/test_process_info.erl
tests/test.c

Allow applications to spawn a process with a minimum heap size.

---

src/libAtomVM/opcodesswitch.h

memory_heap_alloc can fail without sufficient guaranteed space in the heap.

Ensure enough free space before allocating space for a fun in the heap.

---

.travis.yml
docker/Dockerfile

.travis.yml: add CI for ESP32 and STM32

---

src/libAtomVM/nifs.c

This change fixes a bug in the new erlang:list_processes/0 function, by allocating the list in the calling process heap, instead of allocating each element of the list in each listed process!

Fix bug in erlang:list_processes/0

---

src/libAtomVM/memory.c

This change set limits the size of the heap after a GC event, so that the allocations for the heap and stack do not grow without bound, after a GC.

Limit the size of the new heap after GC.

---

examples/erlang/esp32/blink.erl

Fix blink example per https://github.com/bettio/AtomVM/issues/99

---

src/libAtomVM/linkedlist.h

Made list pointer passed to linkedlist_length const.

---

src/libAtomVM/exportedfunction.h
src/libAtomVM/opcodes.h
src/libAtomVM/opcodesswitch.h

Added support for gc_bif3 opcode

---

.travis.yml
src/platforms/stm32/src/lib/sys.c

Adapt STM32 platform to the new scheduler and make it compile again

Make STM32 Great Again, Again

---

doc/atomvm-packbeam.md

Added packbeam format documentation

---

libs/estdlib/src/CMakeLists.txt
libs/estdlib/src/base64.erl
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_base64.erl
tests/test.c

Added base64 encoding and decoding nifs and Erlang wrappers

---

.gitignore
doc/atomvm-esp32.md
src/platforms/esp32/main/component.mk
src/platforms/esp32/main/component_nifs.h.in
src/platforms/esp32/main/component_nifs.py
src/platforms/esp32/main/platform_nifs.c

Added make rules, scripts, and templates for adding third-party components and nifs as an optional build.

Component Nifs

---

doc/atomvm-esp.md
examples/erlang/esp32/CMakeLists.txt
examples/erlang/esp32/deep_sleep.erl
src/platforms/esp32/main/platform_nifs.c

Added support for timer-based deep sleep.

---

src/libAtomVM/opcodesswitch.h

Instead, re-initialize src binary which may have moved during GC.

Removes unecessary mallocs when creating binaries in binary matches

---

src/libAtomVM/opcodes.h
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_raise.erl
tests/test.c

Support for (legacy) raise/2 (108) opcode

---

libs/estdlib/src/lists.erl
tests/libs/estdlib/test_lists.erl
tests/libs/estdlib/test_maps.erl

Added lists:seq and lists:sort

---

src/libAtomVM/opcodesswitch.h
src/libAtomVM/term.h

This change set optimizes memory when "modifying" existing entries by re-using the keys tuple if the resulting map has the same keys.

Maps optimization

---

libs/estdlib/src/gen_server.erl
tests/libs/estdlib/test_gen_server.erl

* Graceful exit when gen_server:init raises an exception
* Fixes a memory leak in the process mailbox for messages that arrive after the client has timed out.

Fixes to the gen_server implementation discovered in testing.

---

examples/elixir/esp32/Blink.ex
examples/elixir/stm32/MultiBlink.ex
libs/exavmlib/lib/GPIO.ex

This closes issue #351.
Adds documentation and enhancements to the elixir gpio driver.

Elixir gpio updates

---

libs/eavmlib/src/timer_manager.erl
libs/estdlib/src/gen_server.erl

These files were in a PR before the check on all files.

Fix formatting of recent files

---

.github/workflows/build-and-test-macos.yaml

Faster macOS build

---

libs/estdlib/src/gen_tcp.erl
src/platforms/generic_unix/socket_driver.c
tests/libs/estdlib/test_gen_tcp.erl

Fix #401
Fix problems with passive receive
Fix gen_tcp test

Fix issues with gen_tcp

---

src/libAtomVM/interop.c
src/libAtomVM/interop.h
src/platforms/esp32/components/avm_builtins/gpio_driver.c
src/platforms/esp32/components/avm_builtins/i2c_driver.c
src/platforms/esp32/components/avm_builtins/spi_driver.c
src/platforms/esp32/components/avm_builtins/uart_driver.c

Use updated interop atom term select int

---

libs/estdlib/src/gen_server.erl
tests/libs/estdlib/test_gen_server.erl

Add gen_server timeout

---

.github/workflows/build-and-test-other.yaml
.github/workflows/codeql-analysis.yaml
.github/workflows/run-tests-with-beam.yaml

Fix CI issues after ubuntu-latest image upgrade

---

src/libAtomVM/context.c
src/libAtomVM/context.h
src/libAtomVM/memory.c
src/libAtomVM/opcodesswitch.h

Number of registers was not modified, make it a constant

---

CHANGELOG.md
doc/src/programmers-guide.md
libs/eavmlib/src/esp.erl
src/platforms/esp32/components/avm_sys/platform_nifs.c

Add esp:sleep_enable_ext0_wakeup/2 and esp:sleep_enable_ext1_wakeup/2

---

src/libAtomVM/opcodesswitch.h

Also simplify macros by getting rid of the duplicate last parameter.

Assert types of operands at load time and ignore them at execution time.

---

libs/estdlib/src/CMakeLists.txt
libs/estdlib/src/gen_event.erl
libs/etest/src/etest.erl
tests/libs/estdlib/CMakeLists.txt
tests/libs/estdlib/test_gen_event.erl
tests/libs/estdlib/tests.erl

Added an implementation of the gen_event OTP interface

---

libs/estdlib/src/gen_server.erl

Otherwise, information about what caused the crash is lost and is extremely difficult to debug.

Prints a crash report to the console if a gen_server crashes in init

---

src/libAtomVM/globalcontext.h
src/libAtomVM/term.c
src/libAtomVM/term.h
src/libAtomVM/utils.h

Add new term print function

---

src/libAtomVM/context.c

This problem is solved differently in feature/smp branch.
The exit reason was in ctx instead of target here, which creates a problem when target runs the garbage collector as the exit reason will be copied but will not be accounted for in the used memory, thus a future memory_ensure_free may fail if the exit_reason is larger than `MIN_FREE_SPACE_SIZE`.

Fix handling of exit reason in non-SMP builds

---

src/libAtomVM/bif.c
src/libAtomVM/context.h
src/libAtomVM/externalterm.c
src/libAtomVM/memory.c
src/libAtomVM/memory.h
src/libAtomVM/opcodesswitch.h

Fix some clang warnings

---

src/platforms/esp32/components/avm_builtins/uart_driver.c

make `read:uart` work again, tested by running it for a hour.
Fixes #565 

ESP32: fix UART driver

---

src/libAtomVM/scheduler.c

When a process is signaled, it is executed to process the signal, but the mailbox may be empty after the signal is processed. This would yield a crash on native handlers that expect `mailbox_first` to always return the message to consume.
Also work around native ports that only process one message by rescheduling them if there is another message.

Fix a bug where native ports would be executed with no message

---

examples/erlang/esp32/tcp_client_esp32.erl

The example crashed on feature/smp branch (this is #592) because it called `inet:peername/1` on a closed socket and received `{error, einval}` and did not expect this return value. Yet this is the correct behavior.
Fix the example by calling `inet:peername/1` only once.
Also change the format strings so the packet will be printed properly once bug #594 is fixed.

Fix a bug in ESP32 TCP client example (fix #592)

---

doc/src/atomvm-internals.md

Further document feature/smp internals

---

examples/erlang/rp2040/CMakeLists.txt
examples/erlang/rp2040/pico_blink.erl
libs/eavmlib/src/gpio.erl
libs/exavmlib/lib/GPIO.ex
src/platforms/rp2040/src/lib/CMakeLists.txt
src/platforms/rp2040/src/lib/gpiodriver.c
src/platforms/rp2040/src/lib/gpiodriver.h
src/platforms/rp2040/src/lib/platform_nifs.c
src/platforms/rp2040/src/lib/rp2040_sys.h
src/platforms/rp2040/src/lib/sys.c
src/platforms/rp2040/src/main.c

Add basic GPIO support for Pico

---

.github/workflows/build-and-test-other.yaml

Use multiarch debian docker images

---

src/platforms/esp32/tools/flashimage.sh.in
tools/dev/flash.sh

Added -p and -b options to flash scripts

---

libs/eavmlib/src/http_server.erl

Also fix issue where connection would be closed before all data is sent Also send data by chunks if it's passed as a list, allowing sending larger amount of data

Update http_server API to allow passing headers

---

src/libAtomVM/posix_nifs.c
tests/libs/eavmlib/test_file.erl

Monitor selecting process to avoid leaks.
Add tests

Add monitor to posix_select

---

libs/estdlib/src/calendar.erl
libs/estdlib/src/erlang.erl
libs/estdlib/src/gen_tcp.erl
libs/estdlib/src/gen_udp.erl

Fix some types and add missing nifs to erlang module

---

src/libAtomVM/tempstack.h

This change, combined with a Fibonacci heap growth strategy (#771), approximatively divides execution time by two with the Sudoku benchmark.

Optimize usage of temporary stack by allocating first words on C stack

---

.github/workflows/pico-build.yaml
CMakeModules/FetchUnity.cmake
doc/src/build-instructions.md
src/platforms/rp2040/CMakeLists.txt
src/platforms/rp2040/src/lib/CMakeLists.txt
src/platforms/rp2040/tests/.gitignore
src/platforms/rp2040/tests/CMakeLists.txt
src/platforms/rp2040/tests/package-lock.json
src/platforms/rp2040/tests/package-lock.json.license
src/platforms/rp2040/tests/package.json
src/platforms/rp2040/tests/package.json.license
src/platforms/rp2040/tests/run-tests.ts
src/platforms/rp2040/tests/test_main.c
src/platforms/rp2040/tests/tsconfig.json
src/platforms/rp2040/tests/tsconfig.json.license

Add tests for rp2040 powered by rp2040js emulator

---

src/libAtomVM/opcodesswitch.h

Also reduce stack usage a little bit when decoding. Impact on Sudoku benchmark is measurable but less than 1%.

Optimize usage of x registers

---

UPDATING.md

Instructions that I added to `UPDATING.md` might be obvious, but might be useful in order to address some frustrating situations or to providing a synthetic source of information with useful steps in order to upgrade.

Add UPDATING.md

---

src/libAtomVM/globalcontext.c

Previous fix (see #812) didn't fix an important corner case. This was causing a number of odd looking behaviors (see #822).
Closes #822.

Fix race condition in atom table for real

---

examples/erlang/esp32/ap_sta_network.erl

Fix redundant callback in ap_sta sample code

---

examples/erlang/rp2040/picow_wifi_sta.erl
src/platforms/rp2040/src/lib/CMakeLists.txt
src/platforms/rp2040/src/lib/lwipopts.h
src/platforms/rp2040/src/lib/networkdriver.c

Add SNTP support on Pico-W in STA mode

---

src/platforms/rp2040/src/lib/sys.c

Fix a bug where sys_poll_events would return immediately if there is nothing to do.
Also extend this wait logic on non-SMP builds as we now process interrupts and queued elements should wake up the scheduler.
Also fix a concurrency bug with enqueue where a message could not be processed until the scheduler is woken by something else.

Fix sys_poll/enqueue SMP logic on Pico

---

src/libAtomVM/otp_socket.c

Fix memory allocation in OTP Socket BSD recv/recvfrom

---

libs/estdlib/src/maps.erl
tests/libs/estdlib/test_maps.erl

Implement `maps:foreach/2`

---

libs/eavmlib/src/logger_manager.erl

This PR uses the process dictionary to cache log level decisions, in order to improve performance of logging subsystem.
Because logger configuration is immutable, this caching is “safe”, in that the logger configuration for a given logger manager instance cannot change (as a current design limitation).  Once we support ETS tables, we can make equivalent performance improvements while also being able to support mutable state in the logging subsystem.

Cache calls to logger_manager in process dictionary

---

CHANGELOG.md
SECURITY.md
src/platforms/esp32/components/avm_builtins/socket_driver.c

Add v0.6 to SECURITY.md

---

CHANGELOG.md
libs/estdlib/src/proplists.erl

Import proplists functions from OTP

---

libs/eavmlib/src/logger_manager.erl

Fix a case where logging may crash if it happens while logger_manager is being terminated. Unfortunately, this does not fix the flappiness of test_logger.

Fix race condition of logger_manager

---

.github/workflows/build-and-test-macos.yaml
.github/workflows/build-and-test-other.yaml
.github/workflows/build-and-test.yaml
.github/workflows/build-docs.yaml
.github/workflows/build-libraries.yaml
.github/workflows/build-linux-artifacts.yaml
.github/workflows/check-formatting.yaml
.github/workflows/codeql-analysis.yaml
.github/workflows/esp32-mkimage.yaml
.github/workflows/pico-build.yaml
.github/workflows/publish-docs.yaml
.github/workflows/reuse-lint.yaml
.github/workflows/run-tests-with-beam.yaml
.github/workflows/stm32-build.yaml
.github/workflows/wasm-build.yaml

Bump versions of Github actions

---

CHANGELOG.md
libs/estdlib/src/code.erl
src/libAtomVM/globalcontext.h
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_code_all_available_loaded.erl
tests/test.c

Add code:all_loaded/0 and code:all_available/0

---

CHANGELOG.md
libs/estdlib/src/CMakeLists.txt
libs/estdlib/src/lists.erl
libs/estdlib/src/queue.erl
tests/libs/estdlib/CMakeLists.txt
tests/libs/estdlib/test_lists.erl
tests/libs/estdlib/test_queue.erl
tests/libs/estdlib/tests.erl

Add queue module

---

CHANGELOG.md
libs/exavmlib/lib/Enum.ex
tests/libs/exavmlib/Tests.ex

Add some missing Enum functions and make find functions compatible with Enumerable protocol.

Add more Enum functions

---

CHANGELOG.md
libs/estdlib/src/lists.erl
tests/libs/estdlib/test_lists.erl

Add `lists:last/1` and `lists:mapfoldl/3`

---

CHANGELOG.md
libs/estdlib/src/gen_server.erl

Fix gen server internal messages

---

CHANGELOG.md
src/libAtomVM/otp_socket.c

Add missing lock on socket resource

---

CHANGELOG.md
src/libAtomVM/externalterm.c
src/libAtomVM/externalterm.h
src/libAtomVM/term.h

Add externalterm to term with roots

---

.github/workflows/esp32-build.yaml
.github/workflows/reuse-lint.yaml
.github/workflows/wasm-build.yaml

Switch latest to ubuntu 24.04

---

src/platforms/esp32/components/avm_sys/sys.c

Fix dubious logic revealed by esp idf 5.4 warning

---

CHANGELOG.md
libs/estdlib/src/socket.erl
src/libAtomVM/context.c
src/libAtomVM/otp_socket.c
src/libAtomVM/refc_binary.c
src/libAtomVM/resources.c
src/libAtomVM/resources.h
tests/libs/estdlib/test_tcp_socket.erl
tests/test-enif.c

Add asynchronous `socket:accept/2`

---

CHANGELOG.md
libs/estdlib/src/socket.erl
src/libAtomVM/otp_socket.c
tests/libs/estdlib/test_udp_socket.erl

Add support for udp multicast

---

libs/eavmlib/src/CMakeLists.txt
libs/eavmlib/src/mdns.erl
libs/eavmlib/src/network.erl
tests/libs/eavmlib/CMakeLists.txt
tests/libs/eavmlib/test_mdns.erl
tests/libs/eavmlib/tests.erl

Add support for mdns name resolution

---

CHANGELOG.md
src/libAtomVM/opcodesswitch.h

Add memory info to OOM crash logs

---

CHANGELOG.md
libs/eavmlib/src/esp.erl
libs/estdlib/src/lists.erl
tests/erlang_tests/unary_plus.erl
tests/libs/estdlib/test_lists.erl

Add lists:dropwhile, fix lists:duplicate/2

---

src/libAtomVM/scheduler.c

Ensure that `scheduler_make_ready` and `scheduler_set_timeout` calls `sys_signal`. As `global->waiting_scheduler` was cached or read without holding `global->schedulers_mutex`, in some cases `sys_signal` was not called yielding a timeout bug where a message is in the queue but the process is not awaken.

Fix a concurrency issue yielding a timeout bug

---

CHANGELOG.md
libs/estdlib/src/erlang.erl
src/libAtomVM/bif.c
src/libAtomVM/bif.h
src/libAtomVM/bifs.gperf
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/unique.erl
tests/test.c

Continue "add erlang:unique_integer (#1519)"

---

src/libAtomVM/dist_nifs.c

- Fix reference count on `DistConnection` resource
- Initialize `selecting_process_id` field in new `DistConnection` object
- Add resource object to gc roots to prevent the resource to be destroyed before `nif_erlang_dist_ctrl_get_data` returns

Fix three issues with `dist_nifs` found while debugging valgrind errors

---

CHANGELOG.md
libs/estdlib/src/io.erl

Also add few io functions required by remote shell
See also #1509 

Add `io:fwrite/1,2,3` and `io:format/3`

---

.github/workflows/build-and-test-other.yaml
CHANGELOG.md
CMakeModules/BuildElixir.cmake
src/libAtomVM/context.c
src/libAtomVM/context.h
src/libAtomVM/globalcontext.c
src/libAtomVM/globalcontext.h
src/libAtomVM/iff.c
src/libAtomVM/mailbox.c
src/libAtomVM/mailbox.h
src/libAtomVM/module.c
src/libAtomVM/module.h
src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h
src/libAtomVM/scheduler.c
src/platforms/esp32/test/sim_boards/diagram.esp32.json
src/platforms/esp32/test/sim_boards/diagram.esp32c6.json
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_link_port.erl
tests/libs/estdlib/test_epmd.erl
tests/libs/exavmlib/Some.Submodule.ex
tests/libs/exavmlib/Tests.ex
tests/test.c
tools/packbeam/packbeam.c

Merge main into feature/distributed-erlang

---

src/libAtomVM/nifs.c

`erlang:group_leader/2` must be synchronous when called on the process itself, otherwise always use signals.

Fix `erlang:group_leader/2` corner case

---

src/libAtomVM/context.c

Just a small helper for readability.

Context: add `term_pid_or_port_from_context` helper

---

src/libAtomVM/nifs.c

Add a type and arity check before calling `term_get_tuple_element`.

NIFs: `do_spawn`: check if is tuple and arity before accessing it

---

src/libAtomVM/ets_hashtable.c
tests/erlang_tests/test_ets.erl

Since 0870d0af3 ports are not encoded as pid, so code has been updated accordingly to handle also ports (using term_is_local_port / term_is_external_port).

Fix ets (handle ports since they are not pids anymore)

---

src/libAtomVM/context.c
src/libAtomVM/context.h
src/libAtomVM/dist_nifs.c
src/libAtomVM/dist_nifs.h
src/libAtomVM/externalterm.c
src/libAtomVM/externalterm.h
src/libAtomVM/mailbox.c
src/libAtomVM/mailbox.h
src/libAtomVM/module.c
src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h
src/libAtomVM/scheduler.c
tests/libs/estdlib/test_net_kernel.erl

Add support for distributed links

---

.github/workflows/build-and-test-macos.yaml

Fix macOS compilation with OTP 28 and new rebar

---

tests/erlang_tests/test_funs12.erl
tests/erlang_tests/unique.erl
tests/libs/exavmlib/Tests.ex

Fix tests warnings

---

.clang-format-ignore
src/libAtomVM/nifs.c

clang-format nifs.c

---

src/libAtomVM/posix_nifs.c

Fix integer conversion compiler warnings in posix file nifs

---

tests/libs/estdlib/test_tcp_socket.erl

Improve test_tcp_socket robustness by using dynamic port
