atomvm/AtomVM

src/platforms/stm32/src/lib/gpio_driver.c
src/platforms/stm32/src/lib/stm_sys.h
src/platforms/stm32/src/lib/sys.c
src/platforms/stm32/src/main.c

This set of changes fixes the remaining warnings on the STM32 platform.

Fix remaining warnings for STM32 platform

---

CHANGELOG.md
doc/src/programmers-guide.md
libs/eavmlib/src/i2c.erl
libs/eavmlib/src/spi.erl
libs/eavmlib/src/uart.erl

New peripheral names are strings now, such as `uart1`, `spi2` or `i2c1`.

Add support to new I2C, SPI and UART peripheral names

---

src/platforms/stm32/src/lib/sys.c

Adds memory allocation check for the `STM32PlatformData` struct before use.

Fix missing memory allocation check in STM32 platorm

---

.github/workflows/build-and-test-macos.yaml
.github/workflows/build-and-test-on-freebsd.yaml
.github/workflows/build-and-test-other.yaml
.github/workflows/build-and-test.yaml
.github/workflows/codeql-analysis.yaml
.github/workflows/run-tests-with-beam.yaml

Fixes several of the workflow files to prevent them from running on changes to other platforms. Specifically, changes to the `emscripten` and `rp2040` platforms no longer trigger the following workflows:
- `build-and-test-macos`
- `build-and-test-on-freebsd`
- `build-and-test-other`
- `build-and-test`
- `codeql-analysis`
- `run-tests-with-beam`

Tune some workflows to not run on changes to other platforms

---

src/platforms/stm32/src/lib/gpio_driver.c

These changes add memory checks before creating error tuples, and fixes the error handling in the nif implementation. Previously nifs would end up using `RAISE_ERROR({error, Reason})` rather than just `RAISE_ERROR(Reason)`.

STM32 gpio driver bug fixes

---

CHANGELOG.md
libs/eavmlib/src/gpio.erl
src/platforms/esp32/components/avm_builtins/gpio_driver.c
src/platforms/stm32/src/lib/gpio_driver.c

Allows setting the `pid()` or registered name of the process to receive `gpio_interrupt` messages as the fourth parameter of `gpio:set_int/4`, with both ESP32 and STM32 GPIO port drivers.

Add `gpio:set_int/4` for ESP32 and STM32

---

CHANGELOG.md
src/libAtomVM/CMakeLists.txt
src/libAtomVM/atom.c
src/libAtomVM/atom_table.c
src/libAtomVM/atom_table.h
src/libAtomVM/externalterm.c
src/libAtomVM/globalcontext.c
src/libAtomVM/globalcontext.h
src/libAtomVM/interop.c
src/libAtomVM/module.c
src/libAtomVM/module.h
src/libAtomVM/nifs.c
src/libAtomVM/term.c
src/platforms/esp32/components/avm_builtins/gpio_driver.c
tests/test-structs.c

Implement new atom table that overcomes previous implementation shortcomings.
Some further improvements are not part of this PR and they will be addressed with further PRs, such as:
- Using gperf for default atoms
- Removing `atom_table_get_atom_string`
- Coalescing together atom strings that are allocated on the heap (instead of using `strdup`)
Memory benchmark:
With atom table:
```
[...]
Heap summary for capabilities 0x00000004:
At 0x3ffb70e8 len 167704 free 104160 allocated 58664 min_free 102252
largest_free_block 102400 alloc_blocks 814 free_blocks 2 total_blocks 816
[...]
```
without:
```
[...]
Heap summary for capabilities 0x00000004:
At 0x3ffb70e8 len 167704 free 96076 allocated 63096 min_free 94252
largest_free_block 94208 alloc_blocks 1727 free_blocks 2 total_blocks 1729
[...] …
```

New atom table implementation

---

doc/src/apidocs/libatomvm/functions.rst
src/libAtomVM/nifs.c
src/libAtomVM/port.c
src/libAtomVM/port.h
src/platforms/esp32/components/avm_builtins/gpio_driver.c
src/platforms/esp32/components/avm_builtins/i2c_driver.c
src/platforms/esp32/components/avm_builtins/network_driver.c
src/platforms/esp32/components/avm_builtins/socket_driver.c
src/platforms/esp32/components/avm_builtins/spi_driver.c
src/platforms/esp32/components/avm_builtins/uart_driver.c
src/platforms/generic_unix/lib/socket_driver.c
src/platforms/stm32/src/lib/gpio_driver.c

Add function for hiding port message tuple format details, so code doesn't need to hardcode indexes or repeat always the same checks, that can be instead shared across different port drivers.

port: add helper function for parsing message tuple

---

CHANGELOG.md
src/libAtomVM/module.c
src/libAtomVM/nifs.c
src/libAtomVM/resources.c

Adds missing checks for `NULL` after memory allocations, and fix potential memory leaks in libAtomVM.

Fix memory bugs in libAtomVM

---

libs/exavmlib/lib/Access.ex
libs/exavmlib/lib/Kernel.ex

Add missing map versions of fetch and get, and support in inspect() for maps too.

Elixir library: add support for maps to Access and inspect/2

---

libs/exavmlib/lib/IO.ex

Add super minimal IO module implementation.

Elixir library: add support for IO.puts/1 and IO.inspect/1

---

src/libAtomVM/interop.c

Avoid crashes with improper lists.

Fix interop: use term_is_nonempty_list instead of term_is_nil

---

.github/workflows/run-tests-with-beam.yaml

This change addresses a CI test failure on the `master` branch, due to (mistaken?) assumptions about how the OTP garbage collector works.

Fix CI failure of test_gc test on OTP-26

---

CHANGELOG.md
libs/eavmlib/src/spi.erl
src/platforms/esp32/components/avm_builtins/spi_driver.c

Instead of using `-1` magic value, just omit the config entry.
`%{miso: -1, mosi: 25, sclk: 26, peripheral: "spi2"}` -> `%{mosi: 25, sclk: 26, peripheral: "spi2"}`

MOSI or MISO can be optional

---

CHANGELOG.md
UPDATING.md
src/libAtomVM/bif.c
src/libAtomVM/memory.c
src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h
src/libAtomVM/stacktrace.c
src/libAtomVM/stacktrace.h
src/platforms/esp32/components/avm_sys/platform_nifs.c

Many opcodes have a live parameter which is the number of registers that should
be preserved by GC operations. Take this into account and conversely stop
preserving registers by default.
This affects significantly the safety of `memory_ensure_free` when writing nifs.
Indeed, arguments (which come from registers) are no longer preserved.
However, no platform-specific nif was found that needed to be fixed. If
required, calls to `memory_ensure_free` or `memory_ensure_free_opt` should be
replaced with calls to `memory_ensure_free_with_roots`.

Fix usage of live in opcodes and no longer preserve registers by default

---

libs/estdlib/src/erlang.erl

Fix typo and rename guard for consistency with OTP

---

CHANGELOG.md
libs/estdlib/src/lists.erl
tests/libs/estdlib/test_lists.erl

As implemented in lists: module in OTP https://github.com/erlang/otp/blob/0e66b88db447954e1de70ec1fa0822d3a7e6133d/lib/stdlib/src/lists.erl#L1808
Unsure where the line goes for functions to be implemented by estdlib, so feel free to close PR.
Use case: 
Using https://github.com/discord/limited_queue/ on top of the erlang queue: module (copy pasted), and the only missing lists function needed was the split/2 - so would be nice to have it out of the box.

Implement lists:split/2

---

CHANGELOG.md
src/platforms/esp32/components/avm_sys/sys.c
src/platforms/rp2040/src/lib/sys.c

entropy and random mutexes were initialized only on generic_unix.

Fix: add missing mutex init/destroy

---

libs/exavmlib/lib/Code.ex

fixes https://github.com/atomvm/AtomVM/issues/1022 - tested on device (esp32)

Fix: Elixir 1.16 Protocols

---

.github/workflows/build-libraries.yaml

This PR adds the `hello_world` AVM file to the release.  This is useful for producing a releasable Homebrew Formula, as the Homebrew team requires at least one meaningful test in order to commit to their repository.
More information can be found in https://docs.brew.sh/Adding-Software-to-Homebrew

Add hello_world AVM to release (for testing Homebrew Formula)

---

CHANGELOG.md

Due to a merge mistake the same section was duplicated.

CHANGELOG.md: merge "Fixed" sections for beta.0

---

CHANGELOG.md
src/platforms/esp32/components/avm_builtins/i2c_driver.c
src/platforms/esp32/components/avm_builtins/include/i2c_driver.h

Using i2c_driver_acquire and i2c_driver_release it is possible to implement native I2C drivers that coexist with erlang ones, without corruptions or race conditions.
This API has been designed on top of deprecated I2C API, so a new one might be needed.
Note: I2C API (the legacy one) from v4.4 until v5.1 is thread safe, new API is not, but we are not using it.

ESP32: allow coexistence of native I2C drivers and Erlang ones

---

CHANGELOG.md
version.cmake

Prepare v0.6.0-beta.0 release

---

.github/workflows/build-libraries.yaml

Fix for missing files: https://github.com/atomvm/AtomVM/actions/runs/7831738913/job/21368781913

Fix: build-libraries CI

---

CHANGELOG.md
README.Md
version.cmake

Prepare v0.7.0-dev dev cycle

---

CHANGELOG.md
src/platforms/esp32/components/avm_builtins/i2c_driver.c

Fix I2C release function and improve logs

---

CHANGELOG.md
version.cmake

Prepare v0.6.0-beta.1 dev cycle

---

doc/edoc/edown_dep/rebar.config

The fix in uwiger/edown#30 has been merged upstream, so we should now return to using the upstream tool available from hex.
Removes unnecessary `ex_doc` plugin.

Revert to upstream `edown` for Erlang documentation

---

src/libAtomVM/context.h
src/libAtomVM/erl_nif.h
src/libAtomVM/externalterm.c
src/libAtomVM/globalcontext.h
src/libAtomVM/inet.h
src/libAtomVM/module.h
src/libAtomVM/otp_net.c
src/libAtomVM/otp_socket.h
src/libAtomVM/resources.h

Fixes missing and miss matched parameter names in libAtomVM doxygen comments.

Corrections to libAtomVM doxgen comments

---

libs/eavmlib/src/atomvm.erl
libs/eavmlib/src/emscripten.erl
libs/eavmlib/src/esp.erl
libs/eavmlib/src/gpio.erl
libs/eavmlib/src/pico.erl
libs/eavmlib/src/port.erl
libs/estdlib/src/calendar.erl
libs/estdlib/src/erlang.erl
libs/estdlib/src/gen_statem.erl
libs/estdlib/src/gen_tcp.erl
libs/estdlib/src/gen_udp.erl
libs/estdlib/src/lists.erl
libs/estdlib/src/socket.erl
libs/estdlib/src/unicode.erl
libs/etest/src/etest.erl

Fixes missing parameters and miss matched parameters in specs that left many functions not having these included in the documentation. Corrects typos and incorrect information. Adds documentation for a few undocumented functions in modules that are otherwise fully documented.

Corrections to edocs

---

doc/Doxyfile.in
src/libAtomVM/opcodesswitch.h

Since no doxygen documentation is included in `src/libAtomVM/opcodesswitch.h`, and processing the files causes build warnings and rendering errors, the file is now omitted when generating the documentation. This allows removing old doxygen macros added in PR #678, and will prevent needing to pollute the file with more macros to fix new rendering errors.

Resolve doxygen problems processing opcodesswitch.h

---

doc/CMakeLists.txt
doc/edoc/gendoc.erl.in

These changes clean up the documentation build system, and fix some broken links in the generated html content.

Cleanup docs build system

---

.github/workflows/build-docs.yaml
.github/workflows/publish-docs.yaml

Fixes two bugs in the documentation workflows that prevented them from running in some cases where they should be run.

Documentation workflows fix

---

.github/workflows/run-tests-with-beam.yaml

Fix beam CI on macOS

---

CHANGELOG.md
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/send_receive.erl

Enables sending messages to registered processes using the shorthand `!` operator. If a message is sent to an atom name that is not registered using the `!` operator a `badarg` run-time error occurs, matching OTP behaviour.
Closes #1011
Closes #98

Allow sending messages to registered process with `!`

---

CHANGELOG.md
src/platforms/rp2040/CMakeLists.txt
src/platforms/rp2040/src/CMakeLists.txt
src/platforms/rp2040/src/main.c

After main() exits with a return, the CPU of the pico is put into a hung state, (from the raspberry-pi-pico-c-sdk page 8, Introduction 1.1 section) which prevents triggering the device into `BOOTSEL` mode to copy a new application.
These changes introduce the cmake `AVM_WAIT_BOOTSEL_ON_EXIT` option; which is enabled by default, will have the cpu spin (if `AVM_REBOOT_ON_NOT_OK` is not enabled) while a console monitoring application is still attached, allowing users to read the console output. If no console monitor is attached (or the attached monitor closes) the pico will be reset into a mode that will allow if to be put into `BOOTSEL` mode by the atomvm_rebar3_plugin `pico_flash` task (or other tools using automated `BOOTSEL` mode solutions), so a new application (or version) can be …

Allow Pico tools to use automated `BOOTSEL` mode after application exits

---

.github/workflows/pico-build.yaml
.github/workflows/stm32-build.yaml

Fix Pico and STM32 CI

---

CHANGELOG.md
src/libAtomVM/externalterm.c
src/libAtomVM/unicode.c
src/libAtomVM/unicode.h
tests/erlang_tests/test_binary_to_term.erl

Make sure atoms are encoded using valid UTF-8 (for `SMALL_ATOM_UTF8_EXT`), and also fix latin1 support (for  `ATOM_EXT`).

Check atom validity when decoding external term and fix latin1 support

---

CHANGELOG.md
src/platforms/esp32/components/avm_builtins/gpio_driver.c

Fixes a bug that caused the driver to silently accept any atom as a valid mode parameter, and return `ok` without causing an error.
closes #1064

Fix ESP32 `gpio:set_pin_mode/2` input validation

---

src/platforms/esp32/CMakeLists.txt

This change brings the build of the ESP32c6 image in-line with other uni-processor ESP32 class MCUs, making
* the ESP32c6 consistent with other builds
* Benefitting from a small performance improvement (1.3x) in the ping pong speed test, with negligible improvement in other perf tests.

Disable SMP on ESP32-C6

---

CHANGELOG.md
src/platforms/esp32/components/avm_builtins/gpio_driver.c

These changes fix several bug found in the ESP32 GPIO driver input validation.  An invalid `pull` mode atom will now result in an error.  Pin parameters are validated to prevent crashing the VM.
closes #1071

Fix missing ESP32 gpio parameter validation issues

---

CHANGELOG.md
src/platforms/rp2040/src/CMakeLists.txt

Adds Pico `cmake` configuration option `AVM_USB_WAIT_SECONDS` to set a timeout to wait for USB serial connection before starting the application.
This will allow for release builds that will wait for a console connection, but eventually timeout and run the aplication.  This allows testing `blinky` and network applications without requiring opening a console connection to the device, while still waiting a reasonable ammount of time for the user to make a console connection to the serial to see the output of applications like `hello_world`.

Make rp2040 wait for usb serial timeout configurable

---

src/platforms/esp32/components/avm_builtins/spi_driver.c
src/platforms/esp32/components/avm_sys/sys.c

Return the right model number and define HSPI macro also for it.

Improve ESP32-C6 support

---

CHANGELOG.md
src/platforms/rp2040/src/lib/gpiodriver.c

Fixes a bug in `gpio:set_pin_pull/2` that would accept any parameter as a valid `pull` mode.
Closes #1069

Fix missing validation in rp2040 gpio driver `pull` mode

---

.github/workflows/esp32-build.yaml
.github/workflows/esp32-mkimage.yaml
CHANGELOG.md
doc/src/build-instructions.md

CI: ESP32: update 5.0.4 to 5.0.6, 5.1.2 to 5.1.3

---

doc/src/api-reference-documentation.rst

One file was missed during the recent documentation updates. This fixes the table of contents to match links changed in other updates, including the link to the no longer duplicated doxygen html content.

Fix error in documentation table of contents

---

CHANGELOG.md
src/libAtomVM/atom.c
src/libAtomVM/context.c
src/libAtomVM/context.h
src/libAtomVM/memory.c
src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/complex_list_match_xregs.erl
tests/erlang_tests/twentyone_param_fun.erl
tests/erlang_tests/twentyone_param_function.erl
tests/test.c

This PR is focused into removing 2 main limitations:
1. Functions can have any number of parameters
2. Up to 1023 live x registers are supported
This restriction has been easily workarounded so far, but removing this limitation closes a gap that makes development smoother.
Since so far everything worked nicely with just 16 registers, this implementation threats "extended x registers" as an uncommon case, so using them is way slower, but still possible, while reducing memory footprint to bare minimum.
There is still a limitation: NIFs with more than 16 parameters are still not allowed, but this limitation will be likely stay unnoticed.
This PR also fixes an unlikely corruption when having exactly 16 live registers, and enables support of more than > 16 typed y registers (I never observed …

Support "extended" x registers (16-1023)

---

doc/src/atomvm-tooling.md
doc/src/build-instructions.md
doc/src/getting-started-guide.md

Adds documentation about Pico `AVM_WAIT_BOOTSEL_ON_EXIT` and `AVM_USB_WAIT_SECONDS` configuration options to "Build Instruction" and their effects in the "AtomVM Tooling" chapter.

Add documentation about Pico build configuration

---

CHANGELOG.md
version.cmake

This PR prepares v0.6.0-beta.1 release.
Following devices have been tested:
- ESP32: OK
- ESP32-S3: VM crash with default dev mode app
- ESP32-C3: default dev mod app fails (likely a manual testing issue)
- ESP32-C6: OK
- RPi2040 Wireless: OK

Prepare v0.6.0 beta.1 release

---

doc/conf.py.in

I missed a configuration option when reworking the recent documentation PRs. This setting is needed to propery render doxygen content in the published html documentation.

Fix missing configuration in `doc/conf.py.in`

---

CHANGELOG.md
src/platforms/esp32/tools/CMakeLists.txt

Decided to add all BOOTLOADER_OFFSET - and not only correcting the incorrect S2 one..
Obviously the conditional could be refactored, but seems preferably to explicitly list/config the various devices.
Release image didn't boot Esp32-S2.
`"Bootloader is located at the address 0x1000 in the flash."`
https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-guides/bootloader.html

Add all Esp32-xx BOOTLOADER_OFFSET

---

src/platforms/esp32/components/avm_builtins/network_driver.c

This fixes deprication warnings for `sntp_setoperatingmode`, `esp_sntp_setservername` and `esp_sntp_init` by updating to the new replacement functions. This will hopefully get `sntp` callbacks working on esp32c6, but I don't have the hardware to test that model yet.

Update ESP32 platform sntp API calls

---

CHANGELOG.md
src/platforms/esp32/components/avm_builtins/network_driver.c

This PR fixes a bug that would cause the DHCP hostname to not get properly set when the device is configured in STA+AP mode.  As a consequence, the default DHCP hostname (`espressif`) would be used, which would obviously be problematic on a network running multiple IoT devices.
With this fix, the DCHP hostname is properly set, both in AP and STA modes, and in fact can be set differently in config, if desired.
Closes #1084.

Fixed setting DHCP hostname in STA+AP mode.

---

src/libAtomVM/context.c
src/libAtomVM/otp_socket.c

Memory leaks in case of errors and unused variables.

Implement few fixes suggested by clang static analyzer

---

src/platforms/esp32/test/main/test_main.c

Move assert of result of erlang test code after tearing down networking.

Fix isolation of esp32 networking tests

---

CHANGELOG.md
src/platforms/esp32/components/avm_builtins/gpio_driver.c

This fixes the bug that causes the VM to crash when the GPIO port driver is stopped on the ESP32 platform (issue #816). Also adds missing `NULL` check when the `GPIOData` struct is malloc'd.

Fix bug in ESP32 gpio:stop/0 and gpio:close/1

---

CHANGELOG.md
version.cmake

Prepare v0.6.0-rc.0 release

---

libs/eavmlib/src/network.erl

User-supplied callback functions should be called in their own spawned processes, so that if they don't terminate or take too long to run, they do not block the network gen_server.

Prevent user-supplied callbacks from blocking network gen_server

---

src/libAtomVM/scheduler.c
src/platforms/esp32/components/avm_builtins/socket_driver.c

Posting messages from a listener did not break out of the sys_poll_events loop on non-SMP builds. Pico is not affected because sys_poll_events doesn't loop.

Fix scheduler issues with non-SMP builds for Esp32 platform

---

.github/workflows/build-linux-artifacts.yaml

Fix arm32v5 build-linux-artifacts

---

src/libAtomVM/CMakeLists.txt
src/libAtomVM/resources.c
src/libAtomVM/resources.h
src/platforms/esp32/CMakeLists.txt
src/platforms/esp32/test/CMakeLists.txt

On Esp32, select is implemented with a FreeRTOS task. It should use the new task API to properly signal the scheduler on non-SMP builds.

Fix select on non-SMP Esp32 builds

---

doc/src/atomvm-internals.md

Remove a stray block indent that prevented two function in the same
"````{only} html" block to be left out of the rendered documentation.
When multiple :::{doxygen} directives are given in the same
"````{only} html" block they need to be separated by an empty newline.

Fix documentation typo that casues functions to not be rendered

---

CHANGELOG.md
version.cmake

Prepare v0.6.0

---

CHANGELOG.md
src/platforms/esp32/components/avm_builtins/socket_driver.c

Fix avail_bytes that was not initialized
Fix handling of read condition messages (netconn with NETCONN_EVT_RCVPLUS and len == 0)
Fix a race condition where two netconn_evt would be processed by a single netconn_recv and the second netconn_recv would block
This makes test_socket work much more reliably on a physical esp32c3

Fix several issues in esp32 socket_driver (default gen_* implementation)

---

CHANGELOG.md
src/libAtomVM/nifs.c
src/libAtomVM/term.c
src/libAtomVM/term.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_fun_to_list.erl
tests/test.c

Remove code duplication that there was between `pid`/`ref`/`fun_to_list` and fix `erlang:display/1`.
Also fix `erlang:display/1` with refs and funs too.
This PR makes also some code deduplication, introducing a couple of heleprs useful when converting a buffer of characters to a list. So `atom`/`integer`/`float_to_list` have been changed to make use of it.
This change is related to #1112 and #1113 (the fix merged with #1113 was not enough due to some duplicated code having the same issue).

Refactor pid/ref/fun_to_list and fix erlang:display/1

---

libs/eavmlib/src/i2c.erl
src/platforms/esp32/components/avm_builtins/CMakeLists.txt
src/platforms/esp32/components/avm_builtins/Kconfig
src/platforms/esp32/components/avm_builtins/i2c_resource.c

This PR adds an optional Nif-based resource for use with the I2C interface.  Using a Nif-based resource has several advantages, including:
* More predictable (and less) latency between the I2C client and IDF calls, since Nifs are not as beholden to the whims of the scheduler as ports/processes;
* One less process needed (as opposed to the port-based implementation), so has less memory overhead;
* Automated resource reclamation when resource is GC’d (after ref count goes to 0), so users can call close, but in cases where they do not, the i2c driver will be removed (eventually).
This implementation is currently opt-in.  Set `use_nif` to true in the initialization parameter when creating an I2C instance, to use it.  Otherwise, the port-based implementation will be used.
These changes are …

Add optional I2C Nif-based resource driver

---

CHANGELOG.md
doc/src/atomvm-internals.md
doc/src/programmers-guide.md
libs/estdlib/src/CMakeLists.txt
libs/estdlib/src/ets.erl
src/libAtomVM/CMakeLists.txt
src/libAtomVM/context.c
src/libAtomVM/ets.c
src/libAtomVM/ets.h
src/libAtomVM/ets_hashtable.c
src/libAtomVM/ets_hashtable.h
src/libAtomVM/globalcontext.c
src/libAtomVM/globalcontext.h
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_ets.erl
tests/test.c

This PR implements a small subset of the OTP `ets` interface.
The following `ets` functions are supported:
* `ets:new/2`
* `ets:insert/2`
* `ets:lookup/2`
* `ets:delete/2`
The following parameters to `ets:new/2` are supported:
* `is_named`
* `{keypos, I :: non_neg_integer()}`
* `private` | `protected` | `public` access types
Only the `set` table type is supported.
This limited functionality allows users to define ETS tables and share term data between processes in a manner that is more efficient than using message passing with a process.  The likely initial users of this feature will be the logging subsystem, as well as parts of the (forthcoming) application support, for storing application environment settings.
This PR provides a partial implementation of issue #887.  Subsequent PRs can …

Added a limited implementation of the OTP ets interface

---

src/libAtomVM/sys_mbedtls.h
src/platforms/esp32/components/avm_sys/sys.c

There is no lock on non-SMP builds.

Simplify conditional macros and clarify mbedtls entropy locks

---

CHANGELOG.md
src/platforms/stm32/cmake/libopencm3.cmake

The cmake file /src/platforms/stm32/cmake/libopencm3.cmake had the `arm_objcopy` dependency incorrect. This could lead to build failures if enough parallel build jobs we given, allowing the job to run before the elf file was created.

Fix STM32 cmake bug

---

src/libAtomVM/memory.c

For build that do not have `ENABLE_REALLOC_GC` defined the function `memory_realloc_heap_root` is unused, which emmits warnings, that elevate to build failures in the build and test on MacOS workflow.

Conditionally include `memory_realloc_heap_root` in build

---

src/libAtomVM/otp_ssl.c

Fixes at least the test crash on macOS reported in #1129

Add required call to psa_crypto_init for TLS 1.3

---

.github/workflows/pico-build.yaml
src/platforms/esp32/test/main/test_erl_sources/test_crypto.erl

Fixes the pico test part reported in #1129

Fix incompatibility of test_crypto test with Pico

---

src/platforms/esp32/tools/CMakeLists.txt

To help users avoid problems using ./build/mkimage.sh from the esp32 directory a warning is emitted if esp32boot.avm cannot be found from a previous generic_unix build during configuration. This warning contains a link to the complete Build Instructions. This easy to miss step was responsible for some confusion that was recently discussed and solved on erlangforums.com.

Warn during ESP32 builds if esp32boot.avm is not found

---

CHANGELOG.md
version.cmake

Prepare v0.6.1 release

---

src/libAtomVM/otp_ssl.c

Documentation specifies that mbedtls_ssl_config_free and mbedtls_entropy_free should be called after mbedtls_ssl_free and mbedtsl_ctr_drbg_free.
Fixes #1115.

Fix order of free functions for ssl context/drbg

---

CHANGELOG.md
CMakeLists.txt
README.Md
doc/src/build-instructions.md
src/libAtomVM/CMakeLists.txt
tests/CMakeLists.txt
tools/packbeam/CMakeLists.txt

All tests pass given cmake is configured with
-DMBEDTLS_ROOT_DIR=/usr/local.
Likely, to support the two other BSDs NetBSD and OpenBSD, their respective identifiers would have to be added there as well.

Support DragonFly BSD

---

libs/estdlib/src/ets.erl
src/libAtomVM/ets.c
src/libAtomVM/ets.h
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/test_ets.erl

Mentioned in #887, required to port gleam/mist.
Implementation is in C as initially designed by @fadushin, which saves a little bit memory as we don't need to copy the whole entry.

Implement ets:lookup_element/3

---

.github/workflows/build-and-test-macos.yaml
.github/workflows/run-tests-with-beam.yaml

Also extend matrix to test on both macos-13 (amd64) and macos-14 (arm64)

Fix CI failures related to macos-latest starting to be macos-14 (arm64)

---

CHANGELOG.md
libs/exavmlib/lib/Integer.ex

Adds guards `is_even` and `is_odd` to `Integer` using `Bitwise`
Fixes #428.

Adds guards `is_even` and `is_odd` to `Integer`

---

CHANGELOG.md
src/platforms/rp2040/CMakeLists.txt

Adds stacktraces to the rp2040 port by default. Like other ports they may be excluded by the cmake option `-DAVM_CREATE_STACKTRACES=off`.
Closes #1107

Include stacktraces on rp2040 port

---

CHANGELOG.md
libs/estdlib/src/ssl.erl
tests/libs/estdlib/test_ssl.erl

This matches OTP behavior.
Fix #1147

Fix semantic of `ssl:recv(Socket, 0)` to return all available bytes

---

CHANGELOG.md
libs/estdlib/src/ssl.erl

Make it closer to OTP default behavior.

ssl options handling fixes

---

src/libAtomVM/opcodesswitch.h

PC is now offset by 1 and unknown opcode error string should report the unimplemented opcode. Most known is 149 which is on_load (see #995)
Also fix trace code so it compiles.

Fix unknown opcode report

---

CHANGELOG.md
src/libAtomVM/opcodesswitch.h
src/platforms/esp32/components/avm_sys/include/esp32_sys.h

Fixes #1150 
Also remove prototype for a function that does not exist.

Fix scheduling of trapped processes

---

CHANGELOG.md
libs/estdlib/src/gen_tcp.erl
libs/estdlib/src/ssl.erl

Fix `gen_tcp` and `ssl` types

---

CHANGELOG.md
examples/erlang/esp32/deep_sleep.erl
libs/eavmlib/src/esp.erl
src/platforms/esp32/components/avm_sys/platform_nifs.c

Fix specification of `esp:sleep_enable_ext0_wakeup/2`
Fix documentation and specification of `esp:sleep_enable_ext1_wakeup/2`
Fix availability of `esp:sleep_enable_ext1_wakeup/2` on ESP32C6 and ESP32H2
Add `esp:deep_sleep_enable_gpio_wakeup/2` to offer the feature on more SOCs and upcoming `esp:sleep_enable_ext1_wakeup_io/2`, `esp:sleep_disable_ext1_wakeup_io/1`.
Improve deep_sleep example, making it easier to use and adding GPIO-based wakeup.

Fix and extend deep sleep GPIO wakeup APIs

---

src/platforms/esp32/components/avm_builtins/gpio_driver.c
src/platforms/esp32/components/avm_builtins/i2c_driver.c

Fix two warnings on esp32

---

src/libAtomVM/otp_ssl.c
tests/libs/estdlib/test_ssl.erl

There is a limitation in current versions of mbed-tls where verify none is not compatible with TLS 1.3. As a workaround, downgrade TLS to 1.2 shall the user specify verify none.
Also improve ssl test by using a TLS 1.3 server (www.atomvm.net).

Workaround issue with verify_none and TLS 1.3

---

tests/erlang_tests/whereis_dead_process.erl

Fix a case where spawned process is already gone, thus making the test flappy.
See https://github.com/atomvm/AtomVM/actions/runs/9075615955/job/24936583233?pr=1156#step:13:1318

Fix race condition in whereis_dead_process test

---

CHANGELOG.md
doc/src/network-programming-guide.md
libs/eavmlib/src/network.erl
src/platforms/esp32/components/avm_builtins/network_driver.c
src/platforms/rp2040/src/lib/gpiodriver.c
src/platforms/rp2040/src/lib/networkdriver.c

These changes add support for both ESP32 and Pico-W to obtain the current signal strength (in decibels) of the connection to the associated access point using `network:sta_rssi/0`.

Add new function to obtain connection RSSI info

---

.github/workflows/esp32-mkimage.yaml
src/platforms/esp32/CMakeLists.txt
src/platforms/esp32/components/avm_builtins/spi_driver.c
src/platforms/esp32/components/avm_sys/sys.c

Add support for esp32c2

---

CHANGELOG.md
version.cmake

Prepare v0.6.2 release

---

src/libAtomVM/ets.h
src/libAtomVM/ets_hashtable.h

Fix C++ compilation for ets headers

---

.gitignore

in src/platforms/esp32/ using:
idf.py add-dependency "espressif/esp32-camera"
or similar will use a managed_components folder for the downloaded dependencies.

.gitignore esp32/managed_components

---

doc/release-notes.md.in

This PR tries to include the subminor number of ESP-IDF supported versions because it is sensitive to build firmware for the ESP32 family. Also, v5.2 (v5.2.1) is covered at this time, so this has been added.
Moreover, I added link to target `idf-version` on [esp32-build.yaml](https://github.com/atomvm/AtomVM/blob/main/.github/workflows/esp32-build.yaml#L38). As future development progresses, the information in this table may diverge from the CI build target numbers, but I expect that users can follow this link to the latest status.
This will close #1168
---

Improve release notes for ESP32 support

---

CHANGELOG.md
src/libAtomVM/opcodesswitch.h

Binary pattern matching was not working properly due to a bug in `bs_context_to_binary` implementation.

Fix binary pattern matching with OTP-21 compiled code

---

src/libAtomVM/portnifloader.c
src/libAtomVM/portnifloader.h
src/platforms/esp32/components/avm_sys/CMakeLists.txt
src/platforms/esp32/components/avm_sys/include/esp32_sys.h
src/platforms/esp32/components/avm_sys/sys.c
src/platforms/rp2040/src/lib/CMakeLists.txt
src/platforms/rp2040/src/lib/rp2040_sys.h
src/platforms/stm32/src/lib/CMakeLists.txt
src/platforms/stm32/src/lib/stm_sys.h
src/platforms/stm32/src/lib/sys.c

esp32, rp2040 and stm32 all use the same logic to use .ctor runtime to register drivers and nifs collections.
Also use the smaller constructor name for nifs of RP2040 on other platforms to maintain compatibility as RP2040 builds have to explicitely list nifs so they are not gc'd. EPS32 is unaffected as enabling of nifs is done through menuconfig.

Factorize REGISTER_* macros and logic for ports and nifs

---

doc/release-notes.md.in

Adds ESP32-C2 and ESP32-H2 to the supported esp32 SOCs in the Release Notes.

Update Release Notes with newly supported esp32 chipsets

---

CHANGELOG.md
src/platforms/esp32/components/avm_builtins/network_driver.c

ESP-IDF version 5.2 introdued a new event (40), which indicates a home channel change when devices are connected in station mode. These informational events are not very useful for applications to act on, as this is expected when a station connects to a new access point, or when the access point instructs connected devices to change to a different channel. Rather than confuse application developers with log messages for an unhandled event 40, by default these events now do nothing, but if debug level logging is enabled in ESP-IDF Kconfig setting an informative debug log entry will be printed on the console.
SPDX-License-Identifier: Apache-2.0 OR …

Handle wifi event 40 on ESP-IDF v5.2 builds

---

.github/workflows/esp32-build.yaml

Start testing against the 5.3-beta2 release, as suggested on telegram.

Add esp-idf 5.3-beta2 to CI

---

doc/release-notes.md.in

missed landing it with https://github.com/atomvm/AtomVM/pull/1184

release-notes: add esp32-C6 as supported soc

---

CHANGELOG.md
libs/exavmlib/lib/Keyword.ex

Keyword.pop is needed for Elixir.GenServer.
rest of the functions is often used for config/starting genservers in elixir land - and minimum needed for running eg https://github.com/elixir-circuits on atomvm (when Elixir.GenServer is available).

Keyword.ex: merge/2 take/2 pop/pop! and helper fns

---

src/libAtomVM/avmpack.c
src/libAtomVM/avmpack.h
src/libAtomVM/iff.c
src/libAtomVM/iff.h
src/libAtomVM/list.h
src/libAtomVM/memory.c
src/libAtomVM/nifs.c
src/libAtomVM/synclist.h
src/libAtomVM/tempstack.h
src/libAtomVM/term.h
tools/packbeam/packbeam.c

Signed-off-by: Davide Bettio <davide@uninstall.it>

Use bool for predicates

---

.github/workflows/esp32-build.yaml
src/platforms/esp32/test/main/test_main.c

QEMU was updated upstream: https://github.com/espressif/qemu/releases/tag/esp-develop-9.0.0-20240606
Resolves the sd card test issue for 5.2.x - and rtc_slow test for c3.
Enables future work on esp32s3 testing - though it currently seems to lack an openeth implementation, thus requiring multiple test to be disabled and fragmenting code. So esp32s3 support slated for future work.

ESP32 CI: Bump QEMU to 9.0.0 & bump pytest(-embedded)

---

CHANGELOG.md

Combines `Added` and `Changed` sections for the `[0.6.3] - Unreleased` section, which had split these sections into two separate sections for each.

Consolidate "Unreleased" sections of CHANGELOG.md

---

CHANGELOG.md
libs/estdlib/src/lists.erl
tests/libs/estdlib/test_lists.erl

Closes https://github.com/atomvm/AtomVM/issues/1159.
Carbon copy from https://github.com/erlang/otp/blob/0b1bab25dbabb6c19319f3373c5a6dfa74667210/lib/stdlib/src/lists.erl#L1252

Implement lists:keytake/3

---

CHANGELOG.md
doc/src/network-programming-guide.md
libs/eavmlib/src/network.erl
src/platforms/esp32/components/avm_builtins/network_driver.c
src/platforms/rp2040/src/lib/networkdriver.c

These changes add support for setting the channel used in access point mode, for both esp32 and rp2040 network drivers.

Add support for setting network AP channel

---

.github/workflows/build-and-test-other.yaml

CI: switch arm64 to Debian bookworm

---

src/platforms/esp32/test/CMakeLists.txt

Missed it in https://github.com/atomvm/AtomVM/pull/1164
No CI supports the c2 currently, so absolutely no hurry - just for good measure.

Fix missing AVM_DISABLE_SMP for esp32c2 in test

---

CHANGELOG.md
src/libAtomVM/bif.c
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/bs_context_byte_size.erl
tests/test.c

Update `byte_size/1` and `bit_size/1` so they accept a match context as a parameter to implement an optimization introduced with OTP 27.0 as OTP-18987.

Update `byte_size/1` and `bit_size/1` bifs to implement OTP-18987

---

libs/eavmlib/src/esp.erl

Export missing types in esp module

---

src/platforms/esp32/components/avm_builtins/gpio_driver.c

See failing build https://github.com/pguyot/la_machine/actions/runs/9597407895/job/26466398807

Fix compilation with CONFIG_AVM_ENABLE_GPIO_PORT_DRIVER=n

---

CHANGELOG.md
src/libAtomVM/context.c
tests/erlang_tests/trap_exit_flag.erl

Fix for issue https://github.com/atomvm/AtomVM/issues/1193
If link is called several times for the same pid, multiple links are created.
Also remove link if a process exits and a linked process traps the EXIT message.

Fix issue with multiple links creation (#1193)

---

doc/src/programmers-guide.md
libs/estdlib/src/erlang.erl

The docs were incorrect for system_info usage see atoms here: https://github.com/atomvm/AtomVM/blob/cddb5fc0ba6e01a26c5ed9d744f6367ba3b8619c/src/platforms/esp32/components/avm_sys/sys.c#L75

Docfix system_info esp32

---

.github/workflows/build-and-test-other.yaml
.github/workflows/build-and-test.yaml
.github/workflows/run-tests-with-beam.yaml
src/platforms/generic_unix/lib/sys.c
tests/libs/estdlib/test_io_lib.erl

* Update Linux Build matrix to favor more compilers, three latest OTP versions, while maintaining builds from 21 to master, reducing combinations from 46 to 39
* Update Run tests on BEAM workflow to include OTP27
* Update build and test on other Linuxes to use OTP27
* Fix test_io_lib for OTP27 (including workaround for https://github.com/erlang/otp/issues/8606)
* Fix compilation with gcc-14

Update build matrices and set OTP27 as the default

---

CHANGELOG.md
libs/estdlib/src/io_lib.erl
libs/estdlib/src/maps.erl
src/libAtomVM/nifs.c
tests/libs/estdlib/test_io_lib.erl
tests/libs/estdlib/test_maps.erl

These were introduced with OTP26 that made iteration order non-deterministic across VM executions

Add support for `maps:iterator/2` and ~kp with `io_lib:format/2`

---

CHANGELOG.md
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_undef.erl
tests/test.c

Fix undef error when a function is undefined

---

tests/erlang_tests/test_heap_growth.erl

This will reduce (slightly) the flappiness of our tests

Bump test_heap_growth timeout

---

CHANGELOG.md
libs/estdlib/src/erlang.erl
tests/libs/estdlib/CMakeLists.txt
tests/libs/estdlib/test_apply.erl
tests/libs/estdlib/tests.erl

Add erlang:apply/2

---

src/libAtomVM/globalcontext.c
src/libAtomVM/globalcontext.h
src/libAtomVM/sys.h
src/platforms/emscripten/src/lib/sys.c
src/platforms/esp32/components/avm_sys/sys.c
src/platforms/esp32/test/main/test_main.c
src/platforms/generic_unix/lib/sys.c
src/platforms/rp2040/src/lib/sys.c
src/platforms/rp2040/tests/test_main.c
src/platforms/stm32/src/lib/sys.c

The same function was duplicated across platforms.

Factorize sys_load_module function

---

.github/workflows/build-and-test.yaml

* Bump timeout of test-erlang which can take more than 10 minutes on slow GitHub runners
* Reduce timeout of test-estdlib.avm which is definitely broken when it takes more than 5 minutes

Adjust test timeouts

---

CHANGELOG.md
src/libAtomVM/memory.c
tests/erlang_tests/test_make_fun3.erl

Functions created with make_fun* opcodes are boxed terms containing terms that are copied. However, `memory_estimate_usage` did not take them into account. As a consequence, a crash could occur when such functions were sent in messages as the copy would overflow a heap allocated with the estimate.

Fix a crash caused by `memory_estimate_usage` failing with some funcs

---

libs/estdlib/src/gen_server.erl

Export missing types in gen_server module

---

tests/erlang_tests/test_exit2.erl

Test sometimes fails on GitHub with a 500ms timeout. This could be reproduced locally by running test 200 times in parallel within multipass. Bumping timeout to 1 second makes the problem disappear locally and hopefully will also fix it on GitHub CI.

Bump test_exit2 timeout

---

CHANGELOG.md
libs/estdlib/src/lists.erl
src/libAtomVM/bif.c
src/libAtomVM/bif.h
src/libAtomVM/exportedfunction.h
src/libAtomVM/opcodesswitch.h
tests/libs/estdlib/test_lists.erl

* Also simplify implementation of `lists:keyreplace/4` (which this bug affects)
* Also add `lists:keystore/4`

Fix a bug where x0 and x1 were corrupted by failing guards

---

.github/workflows/build-and-test-other.yaml
.github/workflows/build-and-test.yaml
.github/workflows/build-docs.yaml
.github/workflows/build-libraries.yaml
.github/workflows/build-linux-artifacts.yaml
.github/workflows/check-formatting.yaml
.github/workflows/esp32-mkimage.yaml
.github/workflows/publish-docs.yaml
.github/workflows/run-tests-with-beam.yaml
.github/workflows/stm32-build.yaml
.github/workflows/wasm-build.yaml
libs/exavmlib/lib/Bitwise.ex
libs/exavmlib/lib/Process.ex

* Use Erlang Docker container where possible
* Add hexpm mirrors to remaining setup-beam invocations
* Bump OTP version to 17 and Elixir to 1.17
* Split check formatting build in three jobs with different containers
* Use elixir 1.17.1 container for mix format and reformat files accordingly

Work around recent setup-beam action failures

---

.github/workflows/run-tests-with-beam.yaml
tests/erlang_tests/test_gc.erl

`test_gc` was disabled because it failed more or less randomly with OTP26. It seems to be related to a change in how the eval string from the command line is processed by OTP, allocating more memory and therefore making the effect of garbage collector less obvious. Fix it by spawning a fresh process for the test.
Special thanks to @karlsson for investigating this.
Fixes #1219

Fix test_gc test with BEAM

---

src/libAtomVM/nifs.c

Crash was triggered with eunit tests and gcc-13 on ubuntu-24.04.

Fix buffer overflow in code:all_available/0 implementation

---

.github/workflows/build-and-test-macos.yaml
.github/workflows/build-and-test-on-freebsd.yaml
.github/workflows/build-and-test-other.yaml
.github/workflows/build-and-test.yaml
.github/workflows/build-libraries.yaml
.github/workflows/build-linux-artifacts.yaml
.github/workflows/esp32-build.yaml
.github/workflows/pico-build.yaml
.github/workflows/run-tests-with-beam.yaml
.github/workflows/wasm-build.yaml
CMakeModules/BuildErlang.cmake
libs/etest/src/eunit.erl
tests/CMakeLists.txt
tests/libs/etest/CMakeLists.txt
tests/libs/etest/test_eunit.erl

Add a simplified implementation of eunit interface, with an output compatible
with unity test as parsed by Python dut module for qemu-based eunit testing.
Eunit can be used on rebar3 projects on generic_unix on both BEAM and AtomVM
with:
```shell
rebar3 eunit
rebar3 as test atomvm packbeam
atomvm ${ATOMVMDIR}/build/libs/etest/src/beams/eunit.beam \
${ATOMVMDIR}/build/libs/atomvmlib.avm \
_build/test/lib/*.avm
```

Add support for eunit module

---

tests/erlang_tests/whereis_dead_process.erl

CI crash shows the message in the mailbox, so bumping timeout might help

Bump timeout of whereis_dead_process test

---

CHANGELOG.md
src/libAtomVM/bif.c
src/libAtomVM/bif.h
src/libAtomVM/bifs.gperf
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_size.erl
tests/test.c

The BIF was missing and it would yield a crash.

Add support for `erlang:size/1` bif

---

src/libAtomVM/opcodesswitch.h

Add missing DEBUG_FAIL_NULL for gcbifs

---

CHANGELOG.md
src/platforms/esp32/main/main.c

This PR just add USB serial output on ESP32, that should be manually enabled.
There will be one more PR in main branch that will enable pre-built images, menu entries, etc...

ESP32: USB serial output

---

src/platforms/rp2040/CMakeLists.txt

Current pico github builds is failing due to cmake 3.30 having made changes to their private api:
https://discourse.cmake.org/t/cmakedeterminecompilerfeatures-cmake-is-no-more-in-3-30-bug-or-not/11176/2

Fix pico builds (cmake 3.30)

---

CHANGELOG.md
libs/estdlib/src/CMakeLists.txt
libs/estdlib/src/maps.erl
libs/estdlib/src/sets.erl
src/libAtomVM/memory.h
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
src/libAtomVM/opcodesswitch.h
src/libAtomVM/term.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/maps_nifs.erl
tests/libs/estdlib/CMakeLists.txt
tests/libs/estdlib/test_sets.erl
tests/libs/estdlib/tests.erl
tests/test.c

Add sets module and required functions to make it work.

Add `sets` module and `maps:from_keys/2`

---

.gitignore

When running pytest in esp32/test it will create files eg: `src/platforms/esp32/test/__pycache__/test_atomvm.cpython-312-pytest-8.2.2.pyc` this git_ignores that folder.

Add .git_ignore esp32/test/__pycache__/**

---

.github/workflows/esp32-build.yaml

Bump CI esp-idf 5.3 beta2 -> rc1

---

CHANGELOG.md
version.cmake

Prepare v0.6.3

---

.github/workflows/build-libraries.yaml
.github/workflows/build-linux-artifacts.yaml

Revert 85ca4ce078f7d1e18e373998836b18087b40f196 for the mentioned files.

Fix release workflows

---

CHANGELOG.md
libs/eavmlib/src/gpio.erl
src/platforms/esp32/components/avm_builtins/gpio_driver.c

Some GPIO pins require initialization as gpio pins to work, for example GPIO 4 on ESP32C3. This is achieved by calling esp-idf `gpio_config`. Implement this within `gpio:init/1` which is used on rp2040.

Implement `gpio:init/1` on esp32

---

doc/CMakeLists.txt
doc/conf.py.in

These changes will allow publishing documentation for branches (in addition to `main`, which is already published), while continuing to support publishing for release tags. The menu listing for `main` has been enhanced to show the link as `main branch (unstable)`, other branch names will appear as (unreleased), like: `release-0.6 branch (unreleased)`. The appearance of links to (tagged) released versions of the documentation are unchanged. This should make it easy for users to identify the correct version of the documentation, and not mistake `release-0.6` for a stable 0.6 release version of the documentation, and easily identify the docs version that matches a branch they are interested in working on, by differentiating branch versions of the documentation.
These changes are made under …

Publish documentation for branches and tags

---

doc/src/atomvm-internals.md

This fixed the formatting of /doc/src/atomvm-internals.md for better html rendering, and more importantly excludes some graphs from the PDF version of the documentation that prevent the PDF from successfully being assembled.

Correction to atomvm-internals.md formatting

---

doc/src/atomvm-internals.md
doc/src/getting-started-guide.md

Fix several mistakes with misplaced markdown and comment notation that lead to mistakes in the rendered documentation.

Documentation typo corrections

---

src/libAtomVM/memory.h
src/libAtomVM/module.h
src/libAtomVM/otp_net.c
src/libAtomVM/otp_socket.c
src/libAtomVM/otp_socket.h

Fixes several warning by removing occourences of the unrecocognisied `@end` directive, and typos in direcive names. Adds missing parameters.

Fix several Doxygen documentation entries in source files

---

doc/_templates/versions.html
doc/src/apidocs/libatomvm/data_structures.rst
doc/src/apidocs/libatomvm/functions.rst
doc/src/apidocs/libatomvm/index.rst
doc/src/apidocs/libatomvm/types.rst

Updates the documentation restructured text skeleton files with missing functions and other elements that have been documented in source files. Some structs, functions, and types that Doxygen cannot parse correctly now have manually created entries added to the restructured text files. Minor enhancement to the way the downloads and versions menu is displayed.

Docs API updates

---

.github/workflows/build-docs.yaml
.github/workflows/publish-docs.yaml
doc/CMakeLists.txt

There was a bug in the tests for GitHub environment variables that led to the documentation build system using an undefined environment variable which resulted in an empty branch name. Determining the correct branch or tag name from within cmake using GitHub environment variables is unreliable, so instead the correct name is determined by the workflows, which set an environment variable that can be used by cmake.

Fix publish docs for branches

---

CHANGELOG.md
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf

Stub function used from certain Elixir versions.

Stub `erlang:error/3` for Elixir support

---

tests/libs/exavmlib/Tests.ex

Fix Elixir warning

---

tests/erlang_tests/test_raw_raise.erl

Accept `undefined` as stacktrace value. This might be changed in the future.
See also #1247

Make `test_raw_raise` pass

---

CHANGELOG.md
version.cmake

Prepare v0.6.4

---

.github/workflows/build-docs.yaml
.github/workflows/publish-docs.yaml
doc/conf.py.in

The github `actions/checkout@v4` only tracks the current branch, even when
`fetch-depth: 0` is used, this causes branch names other than the current one
to be missed when creating the html navigation menus. This is solved by adding
a step to track all of the remote branches that were fetched during checkout.

Correction to publish_docs workflow for branches

---

.github/workflows/esp32-mkimage.yaml
CHANGELOG.md
UPDATING.md
libs/esp32boot/CMakeLists.txt
src/platforms/esp32/partitions-elixir.csv
src/platforms/esp32/tools/mkimage.config.in
src/platforms/esp32/tools/mkimage.erl

**BREAKING CHANGE**:
Starting with this PR, Elixir support is only available in Elixir images with bigger boot.avm partition.
Fixes #1262 

ESP32: move Elixir support to new Elixir images

---

CHANGELOG.md
libs/exavmlib/lib/CMakeLists.txt
libs/exavmlib/lib/Enum.ex
libs/exavmlib/lib/Enumerable.MapSet.ex
libs/exavmlib/lib/String.Chars.Atom.ex
libs/exavmlib/lib/String.Chars.BitString.ex
libs/exavmlib/lib/String.Chars.Float.ex
libs/exavmlib/lib/String.Chars.Integer.ex
libs/exavmlib/lib/String.Chars.List.ex
libs/exavmlib/lib/String.Chars.ex
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/libs/exavmlib/Tests.ex

This PR introduces a number of important Elixir features, such as `String.Chars` protocol
and wider support to `Enumerable` in `Enum` module.

Increase Elixir support (part 2)

---

src/platforms/esp32/tools/mkimage.erl

Code format

---

CHANGELOG.md
src/platforms/esp32/components/avm_builtins/gpio_driver.c

Cast Pin number to integer after checking if it is integer.

fix: ESP32 gpiodriver_set_int - pin number handling

---

CHANGELOG.md
src/libAtomVM/bifs.gperf
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_is_bitstring_is_binary.erl
tests/test.c

This construct is used in Elixir protocols runtime (*.BitString).

Add support for `is_bistring/1` construct

---

CHANGELOG.md
src/libAtomVM/nifs.c

This PR fixes a memory corruption.

Fix `unicode:characters_to_binary`

---

CHANGELOG.md
src/libAtomVM/nifs.c
tests/test.c

`unicode:characters_to_list(<<>>)` was failing with (a bogus) out_of_memory error.

Fix unicode bogus oom

---

.github/workflows/esp32-build.yaml
.github/workflows/esp32-mkimage.yaml
doc/release-notes.md.in

Updates the esp32 workflows to versions currently supported by Espressif, and updates the supported versions table in the release notes to match the CI.

Update ESP32 workflows and supported versions in release notes

---

CHANGELOG.md
libs/estdlib/src/maps.erl
tests/libs/estdlib/test_maps.erl

Add support for `maps:merge_with/3`

---

CHANGELOG.md
libs/exavmlib/lib/Process.ex

send_after is stubbed for /4 and abs option is ignored. Believe those are related to time warping. See https://hexdocs.pm/elixir/1.17.3/Process.html#send_after/4

Process.ex send/2 send_after/3 and /4 cancel_timer/1

---

CHANGELOG.md
libs/estdlib/src/gen_server.erl
tests/libs/estdlib/test_gen_server.erl

Adds gen_server support for handle_continue (https://www.erlang.org/doc/apps/stdlib/gen_server.html#c:handle_continue/2), tests are carbon copy from upstream test suite https://github.com/erlang/otp/blob/141120ab9de7e6069ee45280dc7f6a251f89e081/lib/stdlib/test/gen_server_SUITE.erl#L1012
Added to otp back in 2017: https://github.com/erlang/otp/pull/1490 - often used in elixir land.

Support handle_continue in gen_server.erl

---

CHANGELOG.md
libs/exavmlib/lib/CMakeLists.txt
libs/exavmlib/lib/List.Chars.Atom.ex
libs/exavmlib/lib/List.Chars.BitString.ex
libs/exavmlib/lib/List.Chars.Float.ex
libs/exavmlib/lib/List.Chars.Integer.ex
libs/exavmlib/lib/List.Chars.List.ex
libs/exavmlib/lib/List.Chars.ex

https://github.com/elixir-lang/elixir/blob/v1.17.2/lib/elixir/lib/list/chars.ex
Split into several source files because of how our CMakeLists.txt is built

Add Elixir List.Chars protocol.

---

CHANGELOG.md
libs/estdlib/src/gen_server.erl
tests/libs/estdlib/test_gen_server.erl

Similar to start_link but with `monitor` option.
Code for all "start with name" functions has been refactored to avoid duplication.

Add support for `gen_server:start_monitor/3,4`

---

libs/exavmlib/lib/CMakeLists.txt
libs/exavmlib/lib/System.ex

Carbon copy from elixir with :native time unit removed, as it's not supported by current erlang implementation.

System.ex monotonic_time/1 system_time/1

---

CHANGELOG.md
libs/exavmlib/lib/Kernel.ex
tests/libs/exavmlib/Tests.ex

Closer to Elixir one (and more reliable), but not yet perfect.
e.g. structs are still printed as maps.

Fix Elixir `inspect()`

---

CHANGELOG.md
libs/alisp/src/CMakeLists.txt
libs/eavmlib/src/CMakeLists.txt
libs/esp32devmode/src/CMakeLists.txt
libs/estdlib/src/CMakeLists.txt
libs/etest/src/CMakeLists.txt
libs/exavmlib/lib/CMakeLists.txt

This allows users to create dialyzer plt for their version of dialyzer
Until we manage versions of application, these are installed under PREFIX/lib/atomvm/lib/APP-ATOMVM_VERSION

Install AtomVM applications with beams, source code and avm package

---

CHANGELOG.md
libs/estdlib/src/code.erl
libs/exavmlib/lib/Code.ex
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_code_ensure_loaded.erl
tests/erlang_tests/test_code_load_binary.erl
tests/test.c

Add `code:ensure_loaded/1`

---

CHANGELOG.md
libs/estdlib/src/io_lib.erl
tests/libs/estdlib/test_io_lib.erl

Add support for `io_lib:latin1_char_list/1`

---

CHANGELOG.md
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_extended_literal_large.erl
tests/test.c

Fix a bug where the VM could crash if an extended literal with a large index was encountered.

Fix crash when decoding extended literals with a large index

---

CHANGELOG.md
libs/exavmlib/lib/Keyword.ex

Add Keyword.ex split/2

---

CHANGELOG.md
libs/exavmlib/lib/List.ex

Add support for Elixir `List.duplicate/2`

---

CHANGELOG.md
libs/exavmlib/lib/IO.ex

Add support for Elixir `IO.chardata_to_string/1`

---

CHANGELOG.md
libs/estdlib/src/lists.erl
tests/libs/estdlib/test_lists.erl

Add support for `lists:nthtail/2`

---

CHANGELOG.md
libs/estdlib/src/io.erl

Add support for `io:put_chars/2`

---

CHANGELOG.md
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_binary_copy.erl
tests/test.c

Add support for `binary:copy/1,2`

---

CHANGELOG.md
doc/src/programmers-guide.md
libs/eavmlib/src/spi.erl

currently it's a required param, even in a scenario where it's meant to be empty (nif c code handles device_config: [] already)
eg device_config: [] is currently required:
```
spi_settings = [
bus_config: [
miso: 19,
mosi: 23,
sclk: 18,
peripheral: "spi3"
],
device_config: []
]
spi = :spi.open(spi_settings)
:ok = :esp.mount("sdspi", "/test", :fat, spi_host: spi, cs: 5)
```
PR allows leaving out 'device_config: []' - for simpler/better DX. 
(I wasted a ton of time figuring out the empty device_config array requirement)

Make SPI device_config optional

---

.github/workflows/build-and-test-other.yaml
CHANGELOG.md
libs/eavmlib/src/atomvm.erl
src/libAtomVM/CMakeLists.txt
src/libAtomVM/globalcontext.c
src/libAtomVM/globalcontext.h
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
src/libAtomVM/posix_nifs.c
src/libAtomVM/posix_nifs.h
src/platforms/esp32/CMakeLists.txt
tests/libs/eavmlib/CMakeLists.txt
tests/libs/eavmlib/test_dir.erl

Directory listing using POSIX functions. Beware of 32 bit ARM and other 32 bit architectures, where `ino_t ` is 32 bit while inodes are frequently 64 bit.

POSIX directory functions (opendir, closedir and readdir)

---

CHANGELOG.md
doc/src/programmers-guide.md
examples/elixir/esp32/Adc_nifs.ex
examples/erlang/esp32/adc_example.erl
examples/erlang/esp32/adc_nif_example.erl
libs/eavmlib/src/CMakeLists.txt
libs/eavmlib/src/esp_adc.erl
src/platforms/esp32/components/avm_builtins/CMakeLists.txt
src/platforms/esp32/components/avm_builtins/Kconfig
src/platforms/esp32/components/avm_builtins/adc_driver.c

This set of changes adds support for the ESP32 ADC peripheral, with documentation and examples.
Closes #250

Introduce ESP32 ADC driver

---

CHANGELOG.md
doc/src/network-programming-guide.md
libs/eavmlib/src/network.erl
src/platforms/esp32/components/avm_builtins/network_driver.c

These changes close the following issues for the ESP32 network driver:
* [#643] When network:stop/0 is used the driver is now completely stopped and all resources are freed.
* [#1100] Adds a configurable event handler for STA beacon timeouts (Event: 21).
* Fixes several possible cases of double free() when using network:start/1.

Address several ESP32 network driver issues

---

.github/workflows/build-docs.yaml
.github/workflows/publish-docs.yaml

`edown` is only tested up to OTP-25. It seems to work fine with OTP-26, but fails to parse many of our modules using OTP-27. This change reverts to OTP-26 until an update or alternative makes it possible to build with OTP-27.

Fix broken docs workflows

---

.github/workflows/build-docs.yaml
.github/workflows/publish-docs.yaml

The Doxygen install cache needs to be kept in sync with the runner image used for the workflow, otherwise builds may unexpectedly fail. This will prevent future updates to the runner image from using an out of sync Doygen install cache.

Fix documentation workflow caches

---

CHANGELOG.md
libs/eavmlib/src/uart.erl
src/platforms/esp32/components/avm_builtins/uart_driver.c

`uart` module for ESP32 is broken. This PR fixes it.
* In the current code, `uart:open/1,2` takes `uart0`, `uart1` or `uart2` as `peripheral` option. However, Nif takes either one of `UART0`, `UART1` or `UART2`. This PR corrects the behaviour of `uart:open` to match that of Nif.
* The Nif of `uart` module does not send a reply parsable by `port:call`, which stops the process from executing further codes. This PR fixes that by using `port_send_reply` function.

Fix broken `uart` module

---

CHANGELOG.md
libs/estdlib/src/binary.erl
libs/estdlib/src/erlang.erl
libs/exavmlib/lib/Base.ex
libs/exavmlib/lib/CMakeLists.txt
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_binary_to_integer_2.erl
tests/libs/estdlib/test_binary.erl
tests/test.c

Add functions to load and dump hex string

---

CHANGELOG.md
src/libAtomVM/externalterm.c
src/libAtomVM/externalterm.h

While there was a `externalterm_to_term` function that was taking a buffer and returning a term, there wasn't the exact opposite, since it was returning a binary.
These new functions can be useful for any NIF or function that manipulates just the buffer and not the whole binary.
This will allow to implement later both support for compressed format or to optimize/cleanup the `erlang:term_to_binary` NIF.

Add support for term serialize (as external term) to buffer

---

CHANGELOG.md
libs/estdlib/src/erlang.erl
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/test_list_to_integer.erl

Tested on unix port of AtomVM, some interactive testing and `./test-erlang test_list_to_integer`.

Add support for list_to_integer/2

---

doc/src/programmers-guide.md

Adds a Storage section to the Programmers guide Esp section https://www.atomvm.net/doc/main/programmers-guide.html#esp32-specific-apis , with the recently added esp:mount/umount https://github.com/atomvm/AtomVM/pull/1289
Bit unsure of the Internal flash part, but should be good.

Add esp:mount/umount to programmers-guide.md

---

src/platforms/esp32/components/avm_builtins/uart_driver.c

Remove UART compile time warnings

---

.github/workflows/esp32-mkimage.yaml
src/platforms/esp32/tools/mkimage.erl

It was making Elixir images without Elixir.
Also add an additional debug message to mkimage.erl.

CI: fix `esp32-mkimage` GH workflow

---

.github/workflows/build-docs.yaml
.github/workflows/publish-docs.yaml

Recent CI updates bumped to the latest OTP-26 which has led to documentation build faulures. These changes temporarily revert to OTP-25 for building docs.

Emergengy documentation build fix

---

examples/elixir/HelloWorld.ex
libs/exavmlib/lib/AVMPort.ex

Fix AVMPort, and remove warning from HelloWorld.ex.

Fix `AVMPort`

---

.github/workflows/build-and-test.yaml

A recent change made impossible to use beam files compiled with OTP master, so let's disable it.
See also #1321 and https://github.com/erlang/otp/pull/8913

CI: build-and-test: disable OTP master

---

doc/src/getting-started-guide.md

It seems like the code snippets reference the wrong file format for the Pi Pico

Update code example to use .uf2 files for Pi Pico

---

CHANGELOG.md
src/libAtomVM/externalterm.c
src/libAtomVM/externalterm.h

This goes in pair with the recent addition for storing a term into a buffer.

externalterm: add externalterm_to_term_copy

---

.github/workflows/build-docs.yaml
.github/workflows/publish-docs.yaml

Building and publishing documentation is failing again, let's try pinning to a specific OTP version known to be capable of building the documentation.

Pin OTP to specific version for documentation workflows

---

libs/esp32devmode/src/esp32devmode.erl

I got confused as nothing was happening.
I assumed device was restarting and configuration going into use.
This makes it clear for a beginner and improves DX.

Better message after wifi config (esp32devmode)

---

.github/workflows/publish-docs.yaml

Adds a check to make sure there are acutally changes to be commited and pushed. This is needed to address a situation where the publish docs workflow is triggered, but there are no changes to the documentation content.
Changes `cancel-in-progress` to false, to avoid missing publishing documentation, when another publish workflow is triggerd by a commit that might not have any changes to the documentation to add.

Check for content change before publishing

---

doc/src/build-instructions.md

Changes the device names to lowercase, to match how the deivce name should be passed to CMake during configuration.

Update build instructions for stm32

---

.github/workflows/publish-docs.yaml

The previous fix would always skip publishing. This sets an environmental output in the commit files stage that can be checked before pushing changes.

Fix error in publish docs workflow check

---

.github/workflows/build-docs.yaml
.github/workflows/publish-docs.yaml

Adds missing file triggers for files included in the documentation.

Add missing paths to documentation workflow triggers

---

UPDATING.md

Adds notes about not currently suporting STM32 devices with only 512k of flash, and the just discovered `i2c:write_bytes/2` bug on ESP32 platform.

Add notes to UPDATING.md

---

.github/workflows/publish-docs.yaml

Always run it, and just skip single commit and push commands.

CI: publish-docs: do not make it conditional

---

.github/workflows/publish-docs.yaml

There is likely some problem related to ssh keys, pin them.

CI: pin GitHub ssh keys

---

.github/workflows/publish-docs.yaml

For some reason, even if we add ssh keys to known_hosts, it keeps failing.
The failure is related to confirm prompt, that tries to open tty (that is not available on CI).

CI: fix publish-docs workflow

---

.github/workflows/publish-docs.yaml

CI was green but it wasn't publishing updated doc.
Actually, it wasn't even making a commit.

CI: publish-docs: fix conditional logic

---

src/platforms/stm32/src/lib/gpio_driver.c

There was an incorrect case of passing the pointer to the atom string, instead of the atom index itself in the gpiodriver_set_int function.
On more recent versions of arm-none-eabi compiler this is a compiler error, on some previous versions it was a warning, that must have been overlooked.

Fix bug in STM32 GPIO driver

---

src/platforms/stm32/cmake/compile-flags.cmake

For STM32 devices with 512k flash newlib-nano needs to be used otherwise the compiled binary is too large to leave space for user applications.

Allow continuing to support 512k flash STM32 boards

---

.github/workflows/publish-docs.yaml

Workaround publish-docs issue

---

src/platforms/esp32/main/main.c

Compiling with USE_USB_SERIAL for usb console on s2, would fail as init_usb_serial() is defined after it's called.
Safe for 0.6.5 inclusion.

ESP32-S2: fix compilation with USE_USB_SERIAL

---

CHANGELOG.md
version.cmake

Prepare v0.6.5 release

---

CHANGELOG.md
libs/eavmlib/src/esp_adc.erl

Use proper `erlang:nif_error(undefined)` so that dialyzer doesn't consider the functions never return.

Fix nif declarations in esp_adc module

---

doc/src/programmers-guide.md

Previously failed to mention RX/TX options, and suggested they would default according to the schema, which they dont.
Fixes https://github.com/atomvm/AtomVM/issues/1356

Update UART programmers guide

---

.github/workflows/build-docs.yaml

Fix docs build when branch names contain a /

---

CHANGELOG.md
src/platforms/esp32/components/avm_builtins/gpio_driver.c

Use 1ULL as integer constant (so uint64_t is used), in order to make room for GPIO index >= 32 when shifting.

ESP32: fix `gpio:init/1` on GPIO >= 32

---

doc/src/programmers-guide.md

Guide made it easy to miss the need for try/catch wrapping the get call (if unset). Fixes https://github.com/atomvm/AtomVM/issues/1361

Improve RTC slow mem Programmers guide

---

CHANGELOG.md
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/fconv_fail_invalid.erl
tests/test.c

`fconv` takes also registers as argument, hence they might contain a value that is not a valid number term.

Fix: add missing is_number check to fconv opcode

---

libs/eavmlib/src/ahttp_client.erl

OTP doesn't like `[{binary, true} | ...]`, replace it with `[binary | ...]`.

Fix ahttp_client on OTP

---

.github/workflows/esp32-build.yaml
CMakeModules/BuildErlang.cmake

Fix ESP32 build CI by installing missing rebar3 dependency

---

libs/estdlib/src/supervisor.erl
tests/libs/estdlib/test_supervisor.erl

Add `supervisor:start_child/2`
Add map syntax for supervisor init callback

Extend support of `supervisor` module

---

CHANGELOG.md
libs/eavmlib/src/http_server.erl
src/platforms/generic_unix/lib/socket_driver.c
tests/libs/eavmlib/CMakeLists.txt
tests/libs/eavmlib/test_http_server.erl
tests/libs/eavmlib/tests.erl

* Fix a bug where http_server would fail to send a reply with integers.
* Fix another  bug where http_server crashed with badmatch if connection was closed, including because of previous bug.
* Also fix socket_driver to return `{gen_tcp, closed}` when socket is closed on Linux instead of `{gen_tcp, {recv, 104}}`
Fixes #1366

Fix issues in http_server

---

.github/workflows/esp32-mkimage.yaml

Fix esp32-mkimage workflow by installing rebar3

---

libs/exavmlib/lib/AVMPort.ex

Recent changes introduced a spew of compiler warnings eg. see bottom here: https://github.com/atomvm/AtomVM/pull/1351/files

Fix AVMPort compiler warnings

---

.github/workflows/build-and-test-macos.yaml

See: https://github.com/actions/runner-images/issues/10721

Remove macos-12 from CI as it is deprecated

---

CHANGELOG.md
libs/alisp/src/alisp.erl
tests/libs/alisp/test_alisp.erl

alisp: fix: allow variables with any kind of value

---

src/libAtomVM/nifs.c

Remove unnecessary argc check

---

CHANGELOG.md
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/gc_safe_x_reg_write.erl
tests/test.c

Fix #1379
In few words, `((dreg_gc_safe).base == x_regs)` is not true for x registers >= 16.
Also there is a very minor optimization.

Fix WRITE_REGISTER_GC_SAFE memory corruption

---

CHANGELOG.md
src/libAtomVM/otp_ssl.c

Ensure that ctr_drbg resource is held by ssl context, fixing dependency of resources and destructor chain

Fix destruction of SSL-related resources

---

src/platforms/esp32/components/avm_builtins/gpio_driver.c

5.3.2 needs extra guards for esp32-P4 https://github.com/espressif/esp-idf/commit/706935f46812542a27519b20be4f91e36075d72c
Fixes https://github.com/atomvm/AtomVM/issues/1387
Code changes tested:

Fix esp-idf >= 5.3.2 P4 builds

---

CHANGELOG.md
libs/estdlib/src/erlang.erl
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_split_binary.erl
tests/test.c

Add erlang:split_binary/2

---

libs/estdlib/src/gen_server.erl

Cleanup dead code in gen_server

---

.github/workflows/build-and-test.yaml

https://yamlchecker.com:
```
deficient indentation (287:11)
284 |           cmake_opts_other: "-DAVM_CREATE ...
285 |           arch: "i386"
286 |           compiler_pkgs: "gcc-10 g++-10 g ...
287 |           libc6-dbg:i386 zlib1g-dev:i386  ...
-----------------^
288 |
289 |     env:
```
Tried running `zizmor .github/workflows` but failed due to invalid yaml.

Fix invalid yaml

---

.github/workflows/run-tests-with-beam.yaml

Fix OTP version inconsistency on macOS CI workflow

---

CHANGELOG.md
libs/estdlib/src/inet.erl
tests/libs/estdlib/CMakeLists.txt
tests/libs/estdlib/test_inet.erl
tests/libs/estdlib/tests.erl

Add `inet:getaddr/2`

---

src/libAtomVM/term.h

Remove unused term_is_movable_boxed

---

CHANGELOG.md
src/platforms/esp32/components/avm_builtins/gpio_driver.c

Fixes the implementation of the `none` trigger that has been documented since release-0.5, but was apparently never tested, its use causes a error (see #1386).
Moves the main functionality from `gpiodriver_remove_int` into a new `unregister_interrupt_listener` funtion that is also used when setting the interrupt trigger to `none` to remove an interrupt.
Closes #1386

Fix broken ESP32 gpio interrupt trigger `none`

---

libs/estdlib/src/erlang.erl

Fixes a warning that `Base` is unused in `erlang:binary_to_integer/2` when compiling erlang.erl.

Fix unused `Base` warning when compiling erlang.erl

---

CHANGELOG.md
src/platforms/esp32/main/Kconfig.projbuild
src/platforms/esp32/main/main.c

Improve DX a lot for enabling serial over usb for boards like the S2 Mini.
Will fail in a good way if enabled without esp_tinyusb being installed:
```
/AtomVM/src/platforms/esp32/main/main.c:45:10: fatal error: tinyusb.h: No such file or directory
45 | #include "tinyusb.h"
|          ^~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
HINT: tinyusb.h was removed. Please use esp_tinyusb component from IDF component manager instead.
You can install `esp_tinyusb` using 'idf.py add-dependency espressif/esp_tinyusb' command.
Refer to the migration guide for more details.
```

Add menuconfig option for USE_USB_SERIAL

---

CHANGELOG.md
src/libAtomVM/ets_hashtable.c
src/libAtomVM/externalterm.c
src/libAtomVM/memory.c
src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h
src/libAtomVM/posix_nifs.c
src/libAtomVM/term.c
src/libAtomVM/term.h
tests/erlang_tests/test_binary_to_term.erl
tests/erlang_tests/test_node.erl

Add support for encoded local pids in external terms

---

CHANGELOG.md
src/platforms/esp32/components/avm_builtins/network_driver.c

using ap_sta_network example https://github.com/atomvm/AtomVM/blob/release-0.6/examples/erlang/esp32/ap_sta_network.erl
testing on real devices (and hundreds of wokwi ci runs) - a cold boot often produces a significant wait for sntp sync: 20-30 seconds.
calling esp_sntp_restart() on the got_ip event fixes this. the function is noop if sntp is not init'ed/config'ed. https://github.com/espressif/esp-idf/blob/707d097b01756687cca18be855a2675d150247ae/components/lwip/apps/sntp/sntp.c#L123

Fix slow SNTP sync from cold boot

---

.github/workflows/esp32-build.yaml

Add one more step that builds ESP32 tests using a number of checks for common memory errors.

CI: ESP32 check memory errors

---

CHANGELOG.md
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/libs/estdlib/CMakeLists.txt
tests/libs/estdlib/test_lists_subtraction.erl
tests/libs/estdlib/tests.erl

Add implementation for erlang:--/2.
---------
Signed-off-by: Tomasz Sobkiewicz <tomasz.sobkiewicz@swmansion.com>

Add support for erlang:--/2

---

CHANGELOG.md
src/libAtomVM/context.c
src/libAtomVM/ets_hashtable.c
src/libAtomVM/externalterm.c
src/libAtomVM/memory.c
src/libAtomVM/nifs.c
src/libAtomVM/otp_socket.c
src/libAtomVM/posix_nifs.c
src/libAtomVM/resources.c
src/libAtomVM/term.c
src/libAtomVM/term.h
tests/erlang_tests/ref_to_list_test.erl
tests/erlang_tests/test_binary_to_term.erl
tests/test.c

Add support for encoded refs in external terms

---

.github/workflows/esp32-build.yaml

Fixes the failing `Build ESP32 tests using idf.py with memory checks` step by exporting the rebar3 install directory to PATH.

Fix broken esp32-build workflow

---

CHANGELOG.md
src/libAtomVM/opcodesswitch.h

If a message arrived between `loop_rec` and `wait_timeout`, the execution didn't resume to testing the received message but instead proceeded to the `timeout` opcode. As a result, a timeout occurred immediately.
Fixes #1412 

Fix an issue where a timeout could be triggered immediately

---

CHANGELOG.md
src/platforms/esp32/components/avm_builtins/spi_driver.c

ESP32: SPI: fix spi close command

---

.github/workflows/esp32-simtest.yaml

Make similar changes to the ones done to esp32-build.

esp32-simtest: add erlang-dev

---

.github/workflows/esp32-simtest.yaml

Make similar changes to the ones done to esp32-build.

esp32-simtest: add rebar3

---

.github/workflows/esp32-simtest.yaml

Fix error introduced with #1425 

ESP32: CI: esp32-simtest: fix yaml file

---

.github/workflows/esp32-simtest.yaml

rebar3 requires deps such as erlang-asn1.
Install same dependencies as esp32-build.

ESP32: CI: esp32-simtest: install missing deps

---

CHANGELOG.md
libs/eavmlib/src/atomvm.erl
libs/estdlib/src/erlang.erl
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/test_node.erl

Add `atomvm:get_creation/0`

---

CHANGELOG.md
libs/estdlib/src/net.erl
src/libAtomVM/otp_net.c
src/platforms/esp32/components/avm_sys/CMakeLists.txt
src/platforms/generic_unix/lib/CMakeLists.txt
src/platforms/rp2/src/lib/CMakeLists.txt
tests/libs/estdlib/test_net.erl

Add `net:gethostname/0`

---

code-queries/non-term-to-term-func.ql

After #1413, CodeQL was reporting a lot of noise.

CodeQL: Fix _ATOM handling in non-term-to-term-func

---

CHANGELOG.md
libs/estdlib/src/socket.erl
src/libAtomVM/inet.c
src/libAtomVM/inet.h
src/libAtomVM/otp_socket.c
tests/libs/estdlib/test_tcp_socket.erl
tests/libs/estdlib/test_udp_socket.erl

Add socket:getopt/2

---

.github/workflows/esp32-build.yaml
.github/workflows/esp32-mkimage.yaml
doc/release-notes.md.in

Chore: Bump esp-idf

---

.github/workflows/codeql-analysis.yaml

See also:
- https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
- https://github.com/actions/runner-images/issues/10636

Update CodeQL action

---

src/platforms/esp32/test/main/test_erl_sources/test_select.erl

Just a rework of #1432
Closes #1432

ESP32: fix test_select ESP32-P4

---

.github/workflows/esp32-simtest.yaml

Future proof logic around esp32p4/h2, so they are also expanded for a full_sim_test.

Test esp-idf v5.4-rc1 in sim_test

---

.github/workflows/pico-build.yaml
.github/workflows/stm32-build.yaml
CHANGELOG.md
src/libAtomVM/term.h

Add workaround for latest debian gcc-arm-none-eabi

---

CHANGELOG.md
src/libAtomVM/context.c
src/platforms/esp32/components/avm_builtins/uart_driver.c

- Also fix usage of memory_ensure_free in esp32 uart driver
- Also remove unnecessary condition in context_destroy

Fix double free of esp32 uart driver on close

---

.github/workflows/esp32-build.yaml
.github/workflows/esp32-simtest.yaml
doc/release-notes.md.in

Bumps version the esp32-build.yaml, and esp32-simtest.yaml for runs that include a full_sim_test to ESP-IDF v5.4.
Adds ESP-IDF v5.4 to supported build environments in the release-0.6 release notes.

Add ESP-IDF v5.4 (official) to workflows and supported builds in release notes

---

CHANGELOG.md
src/libAtomVM/scheduler.c

Fix race condition in timeout handling

---

CHANGELOG.md
libs/estdlib/src/gen_server.erl
libs/estdlib/src/supervisor.erl
src/libAtomVM/defaultatoms.def
src/libAtomVM/opcodesswitch.h
tests/libs/estdlib/test_supervisor.erl

- add missing `supervisor:terminate_child/2`, `supervisor:delete_child/2` and `supervisor:restart_child/2`
- fix termination of children of supervisor
- add more termination strategies

Complete supervisor behavior

---

src/libAtomVM/otp_socket.c

Fix a deadlock that was introduced in 555745c8a0cccdb0e1b0fade1993616a3cb16a0c and that happens on platforms without recursive locks (e.g. esp32) by removing an unnessary lock in `socket_recv`.

Fix deadlock in socket code

---

CHANGELOG.md
src/platforms/esp32/components/avm_builtins/network_driver.c
src/platforms/esp32/test/main/test_erl_sources/test_wifi_example.erl

Removes all of the registered event handlers when the driver is stopped.
Fixes the incorrect deletion on the default event loop when the driver is stopped.
Closes #1449

Fix ESP32 network:stop/0

---

src/platforms/stm32/src/lib/stm_sys.h

Adds missing function declarations to stm32/src/lib/stm_sys.h for several platform functions used in main.c from sys.c.

Fix warning about implicit functions on stm32 platform

---

.github/workflows/esp32-mkimage.yaml
CHANGELOG.md
libs/estdlib/src/erlang.erl
src/platforms/esp32/components/avm_sys/sys.c

Adds device info for `erlang:system_info(esp32_chip_info)` for the ESP32P4, as well as building release images. This does not include any network support yet.

Introduce support for ESP32P4

---

CHANGELOG.md
src/platforms/esp32/components/avm_builtins/network_driver.c

The `phy_init` partition has been reserved, but not used. By using the `WIFI_STORAGE_FLASH` location the calibration data is preserved across restarts in flash significantly improving connection times. The data stored using `WIFI_STORAGE_RAM` is lost at boot up and needs to be recalibrated, the option `WIFI_STORAGE_FLASH` will still load the data into ram from flash, but this is much faster than performing a full calibration every boot, and should significantly help battery powered devices that spend time in deep sleep and only wake to collect and relay sensor data to the network.

Utilize reserved `phy_init` partition on ESP32 for wifi calibration data

---

CHANGELOG.md
libs/estdlib/src/CMakeLists.txt
libs/estdlib/src/erl_epmd.erl
tests/libs/estdlib/CMakeLists.txt
tests/libs/estdlib/test_epmd.erl
tests/libs/estdlib/tests.erl

Add `erl_epmd`

---

libs/eavmlib/src/atomvm.erl
src/libAtomVM/posix_nifs.c
tests/libs/eavmlib/test_file.erl
tests/libs/estdlib/test_epmd.erl

Typically allow subprocess to use `$PATH` to find binaries

Allow `subprocess` to use `environ` for environment

---

src/libAtomVM/globalcontext.c
src/libAtomVM/otp_socket.c

Ensure refcount of socket resources is properly handled on demonitor Also ensure that demonitor happens when selected process is cleared

Fix crash in socket refc handling

---

.github/workflows/build-and-test.yaml

After many frustrating runs, this code eventually allowed me to get a trace for a rare core dump related to socket resources.

Upload cores dumped in build-and-test CI

---

CHANGELOG.md
libs/estdlib/src/gen_tcp_socket.erl
libs/estdlib/src/gen_udp_socket.erl
libs/estdlib/src/socket.erl
libs/estdlib/src/ssl.erl
src/libAtomVM/defaultatoms.def
src/libAtomVM/erl_nif.h
src/libAtomVM/globalcontext.c
src/libAtomVM/globalcontext.h
src/libAtomVM/mailbox.c
src/libAtomVM/mailbox.h
src/libAtomVM/otp_socket.c
src/libAtomVM/resources.c
src/libAtomVM/resources.h
src/platforms/esp32/test/main/test_erl_sources/test_ssl.erl
src/platforms/rp2/tests/test_erl_sources/CMakeLists.txt
tests/libs/estdlib/test_tcp_socket.erl
tests/libs/estdlib/test_udp_socket.erl

Add support for socket asynchronous api for `recv` & `recvfrom`

---

libs/exavmlib/lib/Kernel.ex

Adds support for inspecting ports in Elixir, allows for `IO.puts("#{inspect(port)}")`, etc...

Add support for ports to Elixir.Kernel.inspect

---

UPDATING.md
libs/eavmlib/src/console.erl
libs/eavmlib/src/gpio.erl
libs/eavmlib/src/i2c.erl
libs/eavmlib/src/network.erl
libs/eavmlib/src/port.erl
libs/eavmlib/src/spi.erl
libs/eavmlib/src/uart.erl
libs/estdlib/src/erlang.erl
src/libAtomVM/dist_nifs.c
src/libAtomVM/globalcontext.c
src/libAtomVM/globalcontext.h
src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h
src/platforms/emscripten/src/lib/sys.c
src/platforms/esp32/components/avm_builtins/gpio_driver.c
src/platforms/esp32/components/avm_builtins/i2c_driver.c
src/platforms/esp32/components/avm_builtins/socket_driver.c
src/platforms/esp32/components/avm_builtins/spi_driver.c
src/platforms/stm32/src/lib/gpio_driver.c
tests/erlang_tests/test_regecho_driver.erl

- Fix i2c and spi esp32 native code to use ports
- Fix `whereis/1` and `register/2` to work with ports
- Fix specifications related to ports
- Fix documentation of `register/2`

Fix driver usage of ports

---

src/libAtomVM/term.c
tests/erlang_tests/test_binary_to_term.erl

Corrects the format of ports to match the OTP spec (and size that was already defined correctly).

Fix the formatting of local ports

---

.github/workflows/run-tests-with-beam.yaml
libs/eavmlib/src/CMakeLists.txt
libs/eavmlib/src/epmd.erl
tests/libs/estdlib/test_epmd.erl

Add erlang-based epmd server

---

libs/estdlib/src/erlang.erl
libs/estdlib/src/io_lib.erl
src/libAtomVM/memory.c
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_port_to_list.erl
tests/test.c

Add support for io_lib (and io, etc...) to format ports.
Adds port_to_list/1 to erlang module exports to keep dialyzer happy.
Adds a missing clause to handle port terms in `memory_estimate_usage(term)` function that is necessary for formatting ports for io or other purposes.
This is a continuation of #1473.

Add support for formatting ports

---

src/libAtomVM/context.c
src/libAtomVM/context.h
src/libAtomVM/dist_nifs.c
src/libAtomVM/mailbox.c
src/libAtomVM/mailbox.h
src/libAtomVM/memory.c
src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h
tests/libs/estdlib/test_net_kernel.erl

Continuation of #1468 
- Store group leader pid on the heap if it's an external pid
- Introduce a specific signal to change group leader to an external pid as we cannot touch heap from another process
- Add simple test based on rpc and BEAM

Distribution: Add support for external pid as group leader

---

.github/workflows/esp32-simtest.yaml

This executes the simtest simulator inside the github ci action, using (docker) services, instead of using remote servers.
Should increase CI stability, and avoid usage of Wokwi.com server resources.

CI run simtest inside GH action

---

.github/workflows/build-and-test-on-freebsd.yaml

Updates the Ubuntu host to 24.04, and changes to as matrix build with the current stable (14.2) and latest legacy release update (13.4) versions of FreeBSD.
This workflow is a different from most in that the entire build and test is done in a single script in a FreeBSB container on an Ubuntu host. Because it is one large shell script with no separate "jobs" exits needed to be added to ensure the test fails if any important steps fail to complete successfully.
Adds missing rebar3 installation required to complete the tests build.
Closes #1435

Make build-and-test-on-freebsd fail if steps do not complete successfully

---

CHANGELOG.md
src/libAtomVM/nifs.c
src/libAtomVM/term.h
tests/erlang_tests/test_binary_split.erl
tests/test.c

Fix memory corruption caused by `binary:split/2,3`

---

.github/workflows/build-and-test.yaml

Core dumps on relese-0.6

---

libs/estdlib/src/inet.erl
libs/estdlib/src/socket_dist.erl

This allows to connect to localhost if shortnames are used and host cannot be resolved. BEAM succeeds even if gethostbyname(2) fails, typically on macOS 15.

Resolve short names using .local suffix with `inet:getaddr/2`

---

.github/workflows/build-and-test-other.yaml
CHANGELOG.md
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/test_bs.erl

OTP 25 compiler generates bs_match_string, and AtomVM wouldn't support some unaligned matching that worked when compiled by OTP 26+.

Fix unaligned matching of strings for code compiled with OTP < 26

---

.github/workflows/build-and-test-other.yaml

After a number of failures update QEMU to the latest version.
Compiler was segfaulting with s390 and arm64v8 builds, even after a debian image update, so it is likely a problem with user space emulation.
Replace `multiarch/qemu-user-static` with `docker/setup-qemu-action@v3`.

CI: update QEMU used for build-and-test-other

---

doc/src/programmers-guide.md

Documentation should show default option of logger_std_h to be `#{}` instead of `undefined`.
A crash would occur if `undefined` is actually used.

Documentation should show default option of logger_std_h to be #{}

---

libs/eavmlib/src/ledc.erl

Removes an include for a file that does not exist. It was dropped during the PR introducing the ledc driver, but the include line was left, as well as several uses of macros defined in the file.
Removes undefined macros, replacing them with their values, and documents the meaning of the values.

Cleanup ledc driver

---

src/platforms/esp32/components/avm_builtins/i2c_driver.c

Fixes a hard crash of the VM when `i2c:write_bytes/2` is used.
Improves logged errors in the i2c driver by displaying the decoded error string rather than error number in console logs.
Closes #1324

Fix bug in i2c:write_bytes/2

---

.github/workflows/stm32-build.yaml

Fix stm32 CI

---

CHANGELOG.md
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/selval.erl
tests/test.c

Fix bug that was making code such as [1] not working.
[1]:
```erl
selval2(1.0) -> -1;
selval2(2.0) -> -2;
selval2(3.0) -> -3;
selval2(4.0) -> -4;
selval2(5.0) -> 9;
selval2(6.0) -> -6;
selval2(7.0) -> -7;
selval2(8.0) -> -8.
```

Fix comparison in `select_val` opcode

---

src/libAtomVM/otp_socket.c
src/platforms/rp2/src/lib/lwipopts.h

Add support for UDP Multicast to lwIP-based sockets (Pico-W)

---

CHANGELOG.md
libs/eavmlib/src/esp.erl
src/platforms/esp32/components/avm_sys/platform_nifs.c

Primitive allowing for say copying one partition to another. Useful for developing OTA - A/B booting.
See example, that will successfully copy main.avm to second "b" partition and boot of that. (requires https://github.com/atomvm/AtomVM/pull/1502)
```elixir
case :esp.nvs_get_binary(:atomvm, :boot_path) do
:undefined ->
:esp.nvs_put_binary(:atomvm, :boot_path, "/dev/partition/by-name/main.avm")
:timer.sleep(500)
:esp.restart()
"/dev/partition/by-name/main.avm" ->
chunk_size = 65536
size = 884_736
copy_result = copy_partition(0, size, chunk_size)
:esp.nvs_put_binary(:atomvm, :boot_path, "/dev/partition/by-name/mainb.avm")
IO.inspect("boot_path already set, booting to mainb.avm")
:esp.restart()
other ->
IO.inspect("boot_path: #{other}")
end
```
given this partition map:
```
nvs,      data, …
```

Add esp:partition_read/3

---

src/libAtomVM/globalcontext.c

Turns out there was an unnecessary write lock, which can be reduced to a rdlock.
As surfaced here https://github.com/atomvm/AtomVM/pull/1401#discussion_r1942893254 by @jakub-gonet - and confirmed by @pguyot 

Fix: reduce lock on registered_name process_info/2

---

.github/workflows/build-and-test-other.yaml

See also:
- https://github.com/actions/runner-images/issues/11471
- https://github.com/docker/setup-qemu-action/issues/188
- https://github.com/docker/setup-qemu-action/issues/198
Upgrading to QEMU v8.1.5 doesn't seem to help, so
closes #1529
I runt the CI multiple times and it always worked, so I think this downgrade really "fixes" the issue.

Run qemu on Ubuntu 22.04

---

CHANGELOG.md
libs/esp32boot/esp32init.erl

the boot path is a charlist eg erlang "". https://github.com/atomvm/AtomVM/blob/ed48c7c99150e1d708183be6537e1c20c5263492/libs/esp32boot/esp32init.erl#L86
But storing it in nvs with nvs_put_binary, means it's stored as a binary.
minimal fix.
eg this code now works:
```elixir
def start do
case :esp.nvs_get_binary(:atomvm, :boot_path) do
:undefined ->
:esp.nvs_put_binary(:atomvm, :boot_path, "/dev/partition/by-name/main.avm")
:timer.sleep(500)
:esp.restart()
"/dev/partition/by-name/main.avm" ->
IO.inspect("boot_path already set")
other ->
IO.inspect("boot_path: #{other}")
end
end
```
would crash before with badarg, on the second boot with boot_path set. …

Fix boot_path path loading

---

CHANGELOG.md
libs/eavmlib/src/network.erl
src/platforms/esp32/components/avm_builtins/network_driver.c
src/platforms/esp32/test/main/test_erl_sources/test_wifi_example.erl

As evidenced by failing simtest CI on release-0.6 etc.
1. startup should use continue/handle_continue and avoid races + cleaner DRY code.
2. network:stop was using nonblocking call to stop network_port- so rapid stop/start would give the last network:start an old whereis(network_port) that was still shutting down, and lead to errors.
3. somewhat unrelated: sta_rssi was using get_port(), and would crash on no network started - guarded it erlang side, added test.

Fix network.erl race conditions

---

libs/eavmlib/rebar.config

Enables `rebar3 ex_doc` to succeed for eavmlib.
For version it seems to be manual replace in rebar.config eg:
`sed -i "" "s/{version, .*}/{version, \"0.6.5\"}/" rebar.config && rebar3 ex_doc`

Docs - eavmlib ex_doc: add needed include, ex_doc

---

.github/workflows/build-and-test-other.yaml
CHANGELOG.md
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/test_bs.erl

Backport unaligned matching of strings (OTP < 26)

---

CHANGELOG.md
src/libAtomVM/opcodesswitch.h

Check return value for `term_invalid_term()` otherwise error will not be raised, and invalid terms will appear.

opcodesswitch: fix BIF error handling in `CALL_EXT` (and similar)

---

doc/release-notes.md.in

Adds OTP27 and Elixir 1.17 to supported versions.
Adds ESP32-P4 to ESP32 family supported devices.

Update supported OTP versions and platforms in release-notes

---

src/libAtomVM/memory.c

Fixes a false positive critical security bug revealed by codeql in code-scanning/30.
Since it is established before this check that the size does not exceed the free_space, the check is changed to make sure `free_space - size` does not result in 0 free_space, else `should_gc` should be true.

Fix comparison between unsigned subtraction and the value 0

---

CHANGELOG.md
src/libAtomVM/nifs.c

Just check malloc return value.

Add missing out-of-memory handling in binary_to_atom

---

CHANGELOG.md
libs/estdlib/src/ets.erl
src/libAtomVM/ets.c
src/libAtomVM/ets_hashtable.c
src/libAtomVM/ets_hashtable.h
src/libAtomVM/nifs.c
tests/erlang_tests/test_ets.erl

- Enabled ets:insert/2 to accept lists for bulk insertion.
- Extracted helper functions for ets:lookup/2 and ets:insert/2 that do not apply table locks.
The new helper functions can be utilized in the following ETS operations to reduce code duplication:
- ets:update_element/3
- ets:insert_new/2
- ets:update_counter/3
- ets:update_counter/4
- ets:take/2
- ets:delete_object/2
Every mentioned function will be implemented after merging of this PR.

Add option to insert list in ets:insert, ets:lookup refactor

---

doc/src/atomvm-tooling.md
doc/src/build-instructions.md
doc/src/getting-started-guide.md

Updates build instructions for Elixir images on the ESP32 platform.
Updates documentation about partitions on ESP32 to reflect the new offsets used on Elixir enabled images as well as update old references to `lib.avm` to the new `boot.avm` partition name, and updates bootloader offset references with newer esp32 chips.

Update ESP32 Elixir support build instruction and partion documentation

---

src/platforms/esp32/components/avm_builtins/adc_driver.c

The code currently retains the use of ADC_ATTEN_DB_11 until ESP-IDF v5.1.0, but
the first version using ADC_ATTEN_DB_12 is actually ESP-IDF v5.1.3.
Source: https://github.com/espressif/esp-idf/commit/6de9757a4b036dde8db943c8686acd1eeca1fce6

Use ADC_ATTEN_DB_12 for ESP-IDF v5.1.3+ instead of v5.1.1+

---

.github/workflows/build-and-test.yaml
CHANGELOG.md
doc/release-notes.md.in
src/libAtomVM/atom_table.c
src/libAtomVM/atom_table.h
src/libAtomVM/bif.c
src/libAtomVM/bif.h
src/libAtomVM/bifs.gperf
src/libAtomVM/module.c
src/libAtomVM/module.h
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
src/libAtomVM/opcodesswitch.h
tools/packbeam/packbeam.c

Enable again tests against OTP from master branch.
In order to support what will be released as OTP-28 some changes have been required:
- New encoding for atoms
- Uncompressed literals
- to_atom NIFs (`binary_to_atom`, etc...) are now BIFs when used in guards (hence support for GCBIFs in CALL_EXT related opcodes has been introduced for OTP < 28 support and when this optimization is not applied) 

Add support to OTP-28 (master branch)

---

CHANGELOG.md
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/fun_call_bif.erl
tests/test.c

Funs in the form of `fun module:fun/arity` was working only for NIFs.

Fix BIF handling when calling funs

---

CHANGELOG.md

Remove extra back-tick, Fix -> Fixed and reformat to 100 columns.

Fix v6.6.6 changelog section

---

src/platforms/esp32/test/main/test_erl_sources/test_select.erl

Bump ESP32 test_select timeout to avoid flappiness

---

tests/test.c

Make sure everything is flushed before and after running a test, so we make sure output will never be mixed up.

test: add extra fflush()

---

CHANGELOG.md
libs/estdlib/src/ets.erl
src/libAtomVM/ets.c
src/libAtomVM/ets.h
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/test_ets.erl

Currently this solution doesn't support list of UpdateOp to update multiple counters.
Based on:
https://github.com/atomvm/AtomVM/pull/1405
https://www.erlang.org/docs/23/man/ets#update_counter-3

Add ets:update_counter

---

CHANGELOG.md
src/libAtomVM/bif.c
src/libAtomVM/bif.h
src/libAtomVM/bifs.gperf
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/unary_plus.erl
tests/test.c

These changes are made under both the "Apache 2.0" and the "GNU Lesser General Public License 2.1 or later" license terms (dual license).

Fix +/1 (unary plus) not implemented #1512

---

CHANGELOG.md
src/libAtomVM/memory.c
tests/erlang_tests/test_heap_growth.erl

Fix a bug where an out of memory error could occur if a process received messages repeatedly but didn't allocate enough memory to cause a GC. Received messages would accumulate as memory fragments and never be disposed.
The fix consists in forcing a GC if there is a memory fragment, either from a message or from an allocation when running a GC was prohibited. This ensures fragments are processed and referred data from fragments are copied to the heap.
This fix has a small performance penalty as the GC is always triggered where there is a fragment, even if there was no need to run a GC based on available memory.
SPDX-License-Identifier: Apache-2.0 OR …

Run GC when there is a memory fragment to copy message data

---

CHANGELOG.md
libs/estdlib/src/lists.erl
tests/libs/estdlib/test_lists.erl

These changes are made under both the "Apache 2.0" and the "GNU Lesser General Public License 2.1 or later" license terms (dual license).

Add lists:append/1 and lists:append/2.

---

src/libAtomVM/nifs.c

Fixed wrong atom in ets implementation.

Changed memory_atom to out_of_memory atom in ets implementation

---

src/libAtomVM/ets.c
src/libAtomVM/ets.h
src/libAtomVM/nifs.c

Fix memory corruption in `ets_update_counter`

---

CHANGELOG.md
src/libAtomVM/context.c
src/libAtomVM/context.h
src/libAtomVM/mailbox.c
src/libAtomVM/mailbox.h
src/libAtomVM/nifs.c
src/libAtomVM/opcodesswitch.h
src/libAtomVM/resources.c
src/libAtomVM/resources.h
src/libAtomVM/scheduler.c
tests/erlang_tests/test_monitor.erl

Fix concurrency issues and memory leaks related to a poor usage of list of monitors that was accessed by other processes (fix #1384)
Fix semantics of monitor where self cannot monitor itself and a monitor cannot be removed from another process.

Use signals for link/unlink/monitor/demonitor

---

CHANGELOG.md
src/libAtomVM/module.c
src/libAtomVM/module.h
src/libAtomVM/stacktrace.c
tests/erlang_tests/test_stacktrace.erl
tests/erlang_tests/test_stacktrace.hrl

- Fix a crash that happened if a stack element was in another file
- Optimize memory usage by not building lists of line references and of filenames
- Fix parsing of files with no filename at all.
This fixes most occurrences of 'unsupported line_ref tag: 0' (fixes #1388)

Fix handling of filenames in stack traces

---

doc/src/build-instructions.md

Document CONFIG_COMPILER_OPTIMIZATION_PERF and MBEDTLS_ECP_FIXED_POINT_OPTIM in Performance and Power docs.
related: https://github.com/atomvm/AtomVM/pull/1558

Docs: Performance - build options

---

CHANGELOG.md
libs/estdlib/src/erlang.erl

Add spawn_monitor/1, spawn_monitor/3

---

src/libAtomVM/module.h
src/libAtomVM/opcodesswitch.h

Fix advanced tracing

---

CHANGELOG.md
src/libAtomVM/bif.c
src/libAtomVM/bif.h
src/libAtomVM/bifs.gperf
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/float_bif.erl
tests/test.c

Add float/1 BIF

---

CHANGELOG.md
src/libAtomVM/nifs.c
tests/erlang_tests/test_make_tuple.erl
tests/test.c

Fix possible memory corruption in `erlang:make_tuple/2`

---

.github/workflows/build-and-test.yaml
.github/workflows/build-libraries.yaml

1. fail when valgrind detects a memory error
2. run valgrind first, to make easier to deal with bugs and crashes

Improve CI valgrind step

---

examples/emscripten/run_script.erl
examples/emscripten/run_script.html
src/platforms/emscripten/tests/cypress/e2e/examples.spec.cy.js

Calling alert from worker thread no longer works and probably never should have. Update example accordingly.

Fix wasm test with worker thread

---

.github/workflows/wasm-build.yaml

Fix CI issue that appeared while releasing v0.6.5.

CI: fix wasm-build.yaml release step

---

.github/workflows/wasm-build.yaml
CMakeModules/FetchMbedTLS.cmake
src/platforms/emscripten/src/lib/CMakeLists.txt
src/platforms/emscripten/src/lib/emscripten_sys.h
src/platforms/emscripten/src/lib/platform_nifs.c
src/platforms/emscripten/src/lib/sys.c
src/platforms/emscripten/src/main.c
tests/libs/estdlib/tests.erl

This effectively adds support for `erlang:md5/1` on emscripten as listed in #1509

Add support for crypto with emscripten by fetching mbedtls

---

doc/src/build-instructions.md
tools/uf2tool/CMakeLists.txt

By default, `uf2tool` source will be downloaded from `hex` mirrors. Setting `UF2TOOL_PATH` variable allow to use a local checkout of the source tree, thus removing this download at build time.

Add UF2TOOL_PATH CMake variable to avoid download during build time

---

CHANGELOG.md
libs/estdlib/src/erlang.erl
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/test_dict.erl

Add `erlang:get/0` and `erlang:erase/0`

---

src/platforms/rp2/tests/test_erl_sources/CMakeLists.txt

It can bite in some condition when rebuilding for rp2 target.

Add missing `include(ExternalProject)`

---

CHANGELOG.md
src/libAtomVM/opcodesswitch.h

CI should pass also with OTP-21 now.
Note: this appears to be an OTP-21 compiler bug, however the fix is still an improvement on opcode parameters handling.

Fix use after free in `bs_append` and `bs_get_binary2`

---

CHANGELOG.md
src/libAtomVM/bif.c
src/libAtomVM/bif.h
src/libAtomVM/bifs.gperf
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_funs12.erl
tests/test.c

is_function2/3 wasn't handling registers as arity argument (see #1382) and is_function/2 BIF was missing.
See also #1509

Fix `is_function/2` guard and missing BIF

---

src/libAtomVM/context.c

Add explicit cast to please CodeQL. Fix #1582

---

.github/workflows/pico-build.yaml

Fix pico CI by installing doxygen

---

src/libAtomVM/defaultatoms.def
src/libAtomVM/nifs.c
tests/erlang_tests/test_fun_info.erl

Add mock for `erlang:fun_info(F, env)`

---

CHANGELOG.md
libs/estdlib/src/erlang.erl
src/libAtomVM/bif.c
src/libAtomVM/bif.h
src/libAtomVM/bifs.gperf
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/unique.erl
tests/test.c

- Implementation and testing are a bit simplistic, I tried to cover multiple access in tests but we don't have a nice way to poke at VM internals to e.g. test what happens when unique counter is high enough.

Add erlang:unique_integer

---

CHANGELOG.md
src/libAtomVM/nifs.c

A hardcoded `2` as roots count is invalid when the NIF is called as `lists:reverse/1`, possibly resulting in a SEGFAULT or `Found unknown boxed type: C` error during GC
----

Fix SEGFAULT in `nif_lists_reverse`

---

CHANGELOG.md
src/libAtomVM/posix_nifs.c

We've been getting ASAN errors in the calls to `nif_atomvm_posix_read`, and it seems it's because when GC moves things around, it also moves what the `fd_obj_ptr` variable points to. The proposed solution is to move the GC before `enif_get_resource`. We haven't encountered the error after the fix, but please verify that it makes sense.

Fix nif_atomvm_posix_read GC bug

---

src/libAtomVM/context.c
src/libAtomVM/refc_binary.c
src/libAtomVM/resources.c
src/libAtomVM/resources.h

Use ref count and lock on list of monitors for a resource type to ensure that resource still exists when calling the monitor handler.
Should fix #1589

Fix concurrency bug related to resource monitors

---

src/libAtomVM/erl_nif.h
src/libAtomVM/resources.c
tests/test-enif.c

Resource may no longer exist when enif_demonitor_process is called if the monitor was already destroyed as the resource was deallocated. Fix this by storing resource_type in ErlNifMonitor.

Fix possible crash with enif_demonitor_process

---

doc/src/distributed-erlang.md
doc/src/index.rst

Initial documentation of distributed erlang

---

CHANGELOG.md
libs/estdlib/src/erlang.erl
src/libAtomVM/bif.c
src/libAtomVM/bif.h
src/libAtomVM/bifs.gperf
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/is_record.erl
tests/test.c

Add `erlang:is_record/2`

---

CHANGELOG.md
libs/estdlib/src/ets.erl
src/libAtomVM/ets.c
src/libAtomVM/ets.h
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/test_ets.erl

See also #1509
- Added ets:delete/1.
- Extracted helper functions for ets:delete that will be used in future function implementations.
Based on https://github.com/atomvm/AtomVM/pull/1405.
The new helper functions can be utilized in the following ETS operations to reduce code duplication:
- ets:take/2
- ets:delete_object/2

Add `ets:delete/1`, `ets:delete` refactor

---

libs/eavmlib/src/websocket.erl

Fix edoc for websocket.erl

---

src/libAtomVM/opcodesswitch.h
tests/erlang_tests/test_bs.erl

1. OP_BS_MATCH_STRING would ignore length of matched binary strings during comparisons, thus possibly making comparison of unallocated data. Probably harmless on microcontrollers, but Valgrind has the right to complain.
2. OP_BS_MATCH_STRING would also be disabled if MINIMUM_OTP_COMPILER_VERSION was greater than 25, but it can be generated (rarely) by OTP-27.
3. term_set_match_state_offset was called including in cases where there was no match. This may have been harmless as Erlang compiler may always dispose match state when match fails.

Fix several issues with OP_BS_MATCH_STRING

---

src/libAtomVM/erl_nif.h
src/libAtomVM/otp_socket.c
src/libAtomVM/otp_ssl.c
src/libAtomVM/posix_nifs.c
src/platforms/emscripten/src/lib/platform_nifs.c
src/platforms/esp32/components/avm_builtins/adc_driver.c
src/platforms/esp32/components/avm_builtins/storage_nif.c

Also fix a couple of possible memory leaks in error paths

Clarify enif_make_resource usage

---

src/libAtomVM/context.h
src/libAtomVM/scheduler.c

Remove unused reductions in Context

---

libs/estdlib/src/erlang.erl

Fix specification of distribution nifs

---

src/platforms/emscripten/src/lib/platform_nifs.c

Fix harmless typo in emscripten platform_nifs

---

libs/estdlib/src/erlang.erl
libs/estdlib/src/net_kernel.erl
tests/libs/estdlib/test_net_kernel.erl

- add erlang:is_alive/0
- add net_kernel:get_net_ticktime/0
- add documentation for net_kernel:epmd_module/0

Add few functions related to distribution

---

src/libAtomVM/defaultatoms.def
src/libAtomVM/dist_nifs.h
src/libAtomVM/nifs.c
tests/erlang_tests/test_system_info.erl

Add `erlang:system_info/1` additions for remote shell

---

src/libAtomVM/bif.c
src/libAtomVM/bif.h
src/libAtomVM/bifs.gperf
src/libAtomVM/nifs.c
src/libAtomVM/term.h
tests/erlang_tests/test_binary_part.erl
tests/test.c

Add `binary_part/3` to BIFs

---

.github/workflows/build-and-test.yaml

Github is sunsetting the ubuntu20 runner on april 15th, so it needs to be in containers.
https://github.com/actions/runner-images/issues/11101

CI: Containerize ubuntu 20

---

CHANGELOG.md
libs/estdlib/src/lists.erl
tests/libs/estdlib/test_lists.erl

Add `lists:flatmap/2`

---

CHANGELOG.md
libs/estdlib/src/code.erl

Add `code:is_loaded/1` and `code:which/1`

---

CHANGELOG.md
libs/estdlib/src/erlang.erl
libs/estdlib/src/io_lib.erl
libs/estdlib/src/string.erl
tests/libs/estdlib/test_io_lib.erl
tests/libs/estdlib/test_string.erl

Add support for:
- `io_lib:chars_length/1`
- `io_lib:fwrite/2`
- `io_lib:printable_list/1`
- `io_lib:write/1`
- `io_lib:write_atom/1`
- `io_lib:write_string/1` and `io_lib:write_string/2`
See also #1509 

Add several missing io_lib functions

---

CHANGELOG.md
libs/estdlib/src/application.erl

Add `application:get_env/2`

---

CHANGELOG.md
libs/estdlib/src/CMakeLists.txt
libs/estdlib/src/init.erl

Add `init:get_argument/1`, `init:get_plain_arguments/0` and `init:notify_when_started/1`

---

.github/workflows/build-and-test-other.yaml
src/libAtomVM/iff.c
src/libAtomVM/module.c
src/libAtomVM/module.h

Modules can be unaligned when they are loaded from a binary and reads should therefore be unaligned. This yielded a crash on arm32v7 CI.
Also update arm32v7 CI to use bookworm debian image

Fix read 32 bits accesses to modules to be unaligned

---

CMakeModules/BuildElixir.cmake
tests/libs/exavmlib/Some.Submodule.ex
tests/libs/exavmlib/Tests.ex

Need the ability to add extra modules to Elixir testing eg for GenServer tests (https://github.com/atomvm/AtomVM/pull/1476) etc.

CI: Add Elixir pack_test

---

src/platforms/esp32/test/sim_boards/diagram.esp32.json
src/platforms/esp32/test/sim_boards/diagram.esp32c6.json

Use the same  "cpuFrequency" as upstream does for their extensive esp-idf (wifi) testing: https://github.com/wokwi/esp32-test-binaries/blob/main/test/wifi_function/diagram.esp32c6.json

CI: Adjust sim boards to upstream defaults

---

CHANGELOG.md
tools/packbeam/packbeam.c

The memory leak in `do_pack` prevented successful building with address sanitizer (`-fsanitize=address`) enabled

Fix memory leak in `packbeam.c`

---

src/platforms/rp2040/pico_sdk_import.cmake

Avoid issues where PICO_SDK_PATH is accidentally set in the environment. Users could still force `PICO_SDK_PATH` using CMake defines.

Force git clone of Pico-SDK

---

src/platforms/esp32/components/avm_builtins/gpio_driver.c
src/platforms/esp32/components/avm_builtins/spi_driver.c

Also replace 3 with TUPLE_SIZE(2) for clarity

Fix error result in esp32 spi_driver

---

src/platforms/esp32/components/avm_builtins/gpio_driver.c
src/platforms/stm32/src/lib/gpio_driver.c

Fix bug introduced with af32e1213.

Fix GPIO port driver

---

.github/workflows/esp32-build.yaml
.github/workflows/pico-build.yaml
.github/workflows/stm32-build.yaml
.github/workflows/wasm-build.yaml
CHANGELOG.md

Add codeql to esp32-build.yaml workflow
Add codeql to pico-build.yaml workflow
Add codeql to stm32-build.yaml workflow
Add codeql to wasm-build.yaml workflow

Run codeql anaysis on all platforms

---

README.Md
doc/src/index.rst

Update it, AtomVM is less in the early stage, and more solid nowadays.

Revamp README.Md

---

src/libAtomVM/context.c
src/libAtomVM/context.h

Chage `context_process_signal_set_group_leader` `ctx` parameter to `const` since we are just reading it.

Context: add missing const to read-only ctx parameter

---

src/libAtomVM/nifs.c

Add missing `context_destroy` in error handling

---

src/libAtomVM/smp.h

Fix compilation of smp.h with C++ and disabled SMP

---

src/libAtomVM/globalcontext.c

Setting `module_platform_data` to NULL is not necessary as it's done by `module_new_from_iff_binary` which memsets the structure to 0. On the contrary, if `module_new_from_iff_binary` returns NULL it would crash.

Fix crash when loading module fails, for example because of OOM

---

src/platforms/esp32/components/avm_builtins/spi_driver.c

Removes the unnecessary use of esp_err_to_term, which takes an error integer and converts it to an atom term. The value passed was already a term (atom) and does not need any further processing before being passed to the create_pair funtion.

Fix ESP32 SPI driver about passing a term to a function expecting a non-term

---

src/libAtomVM/module.c
src/libAtomVM/module.h
src/libAtomVM/opcodesswitch.h

Out of memory errors can happen when loading large modules without this fix.

Reduce memory footprint of line refs

---

.github/workflows/build-and-test-other.yaml
CMakeModules/BuildElixir.cmake
CMakeModules/BuildErlang.cmake
tests/erlang_tests/code_load/CMakeLists.txt
tools/uf2tool/CMakeLists.txt

Use add_custom_command to ensure we don't rebuild files

Fix CMake targets to avoid useless rebuilds

---

src/platforms/rp2/tests/test_erl_sources/CMakeLists.txt

Fix name of UF2Tool target that was renamed in #1668

Fix compilation for RP2

---

CMakeModules/FetchMbedTLS.cmake
CMakeModules/mbedtls.patch

Patch MbedTLS to fix a legit compilation error
Also bump mbedtls to 3.6.3.1

Fix compilation with emscripten 4.0.9

---

src/platforms/rp2/src/lib/lwipopts.h

See [#1588](https://github.com/atomvm/AtomVM/issues/1588).
I compiled (and run) this change with src/platforms/rp2 for pico and pico_w. I really would like to test this with pico2_w, but this platform seems not available at the moment, because _deps/pico_sdk-src is a little bit older or not available right now.
I learned about lwip and LWIP_NUM_SYS_TIMEOUT_INTERNAL and how it is calculated. AtomVM is a little bit different in this regard, because sntp is optional for the VM user. I hope it is acceptable to waste one lwip memory slot if sntp is not used at all. 
If needed, I think I can test this …

Fix for PANIC if using sntp with pico-w (#1588)

---

.github/workflows/build-and-test.yaml
CHANGELOG.md
libs/estdlib/src/erlang.erl
libs/exavmlib/lib/BadArityError.ex
libs/exavmlib/lib/CMakeLists.txt
libs/exavmlib/lib/Function.ex
libs/exavmlib/lib/Protocol.ex
tests/libs/exavmlib/Tests.ex

Function.ex, Protocol.ex & erlang:fun_info/1.
Changes CI to also run against elixir 1.18.
CI would fail: https://github.com/petermm/AtomVM/actions/runs/15026767721/job/42229370347
```
Running Elixir tests
Unable to open Elixir.Protocol.beam
Failed load module: Elixir.Protocol.beam
Warning: module Elixir.Protocol cannot be resolved.
CRASH 
======
pid: <0.1.0>
Stacktrace:
[{Elixir.Enumerable,impl_for,1,[{file,"/home/runner/work/AtomVM/AtomVM/libs/exavmlib/lib/Enumerable.ex"},{line,22}]},{Elixir.Enumerable,impl_for!,1,[{file,"/home/runner/work/AtomVM/AtomVM/libs/exavmlib/lib/Enumerable.ex"},{line,22}]},{Elixir.Enumerable,count,1,[{file,"/home/runner/work/AtomVM/AtomVM/libs/exavmlib/lib/Enumerable.ex"},{line,177}]},{Elixir.Enum,count,1,[{file,"/home/runner/work/AtomVM/AtomVM/libs/exavmlib/lib/ …
```

CI: Add & Improve Elixir 1.18 support

---

libs/estdlib/src/erlang.erl

Define `nif_error/1` to silence an OTP28 warning

---

.github/workflows/build-and-test-macos.yaml
.github/workflows/run-tests-with-beam.yaml

#1680 was a failure, fix it
Also fix run tests with BEAM on macOS which were also broken by OTP28 release

Fix macOS CI

---

.github/workflows/esp32-build.yaml
.github/workflows/esp32-mkimage.yaml
.github/workflows/esp32-simtest.yaml

CI: release-0.6 bump esp-idf patch versions

---

CHANGELOG.md
src/libAtomVM/module.c

Literals are encoded as external terms, so they might make use of heap fragments and their memory allocation might fail. Existing code already deal with this, so we can just raise instead of abort().
There is still a very very low change we found a corrupt external term, but we are not able to distinguish the situations, so we also print a warning.

module: do not abort when OOM while loading literal

---

CHANGELOG.md
src/libAtomVM/opcodesswitch.h

I never found this issue, but they told me that `allocate_heap` never accounts for boxed immediate integers, so we must fix this regardless a crash has been observed or not.

Fix potential memory corruption with boxed immediate integers

---

.github/workflows/esp32-mkimage.yaml
.github/workflows/esp32-simtest.yaml
CHANGELOG.md

Use esp-idf v5.4.1 for both simtest and mkimage, so it will be used for released images.

ESP32: "default" to esp-idf v5.4.1

---

.github/workflows/build-linux-artifacts.yaml

Use qemu action (as we do in build-and-test-other) rather the previous one. This should fix a segfault that has been observed.

Use `setup-qemu-action` in `build-linux-artifacts`

---

src/libAtomVM/opcodesswitch.h

Remove redundant assignment in if_end/0

---

src/libAtomVM/opcodesswitch.h

Fix trace of is_function/2

---

src/libAtomVM/opcodesswitch.h

Simplify test_arity/2 as it assumes arg is a tuple

---

CHANGELOG.md
libs/exavmlib/lib/Process.ex

Needed for future Registry.ex
Carbon copy from Elixir source.

Process.ex link/1 and unlink/1

---

.github/workflows/publish-docs.yaml
doc/conf.py.in
doc/edoc/gendoc.erl.in

Documentation will have its own dedicated repo and domain.

Move documentation to doc.atomvm.org

---

CHANGELOG.md
libs/estdlib/src/erlang.erl
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/erlang_module_loaded.erl
tests/test.c

Add erlang:module_loaded/1

---

src/libAtomVM/opcodesswitch.h

Compiler always emit a OP_IS_TUPLE before OP_SELECT_TUPLE_ARITY. Replace check with an assert that can be disabled on release builds.

Remove unnecessary check in OP_SELECT_TUPLE_ARITY

---

src/libAtomVM/opcodesswitch.h

Reduction decrement code was probably forgotten here.

Add missing reduction decrement in OP_CALL_FUN2

---

src/libAtomVM/opcodesswitch.h

Fix is_function2 code loader trace

---

doc/conf.py.in

Filter out branches that are not release-* or main, so 'feature/' do not show up in documentation versions.

Avoid feature branches showing up

---

src/libAtomVM/memory.c
src/libAtomVM/term.h

`memory.c` had a missing semicolon, `get/put_tuple_element` in `term.h` unpacked header directly instead of using function. Additionally, first condition is already checked by term_is_tuple().
There's one unfixed assert `TERM_DEBUG_ASSERT((t & 0x3) == 0x2);`
but fixing it would create conflicts with #1701 (changes magic values to macros).

Fix term asserts

---

tests/libs/estdlib/test_inet.erl

Replace old domain with new test domain.

test_inet: use new test.atomvm.org

---

src/libAtomVM/context.h
src/libAtomVM/opcodesswitch.h

Cast terms to uintptr_t and intptr_t when an integer is required, to avoid "Passing a term to a function expecting a non-term" and "Passing a non-term to a function expecting a term" warnings.
Also change Context.cp type to term for the same reason.
This change is 100% safe since term is already defined as uintptr_t.

opcodesswitch: fix false positive CodeQL warnings

---

src/libAtomVM/module.c

An assembly module can have a line_refs_table but no line information at all.

Fix a crash when a module has no line information

---

src/libAtomVM/context.c
src/libAtomVM/context.h
src/libAtomVM/module.c
src/libAtomVM/module.h
src/libAtomVM/opcodesswitch.h
src/libAtomVM/stacktrace.c

Move and rename `dump` to `context_dump`
Factorize and rename `cp_to_mod_lbl_off` to `module_cp_to_label_offset`
Move and rename `get_catch_label_and_change_module` to `context_get_catch_label`
These functions are used by native code

Move and rename several functions out of opcodeswitch

---

src/libAtomVM/opcodesswitch.h

- `OP_BS_GET_INTEGER2` : live is unused
- `OP_BS_GET_FLOAT2` : arg2 is live, is a literal and is unused
- `OP_PUT_MAP_ASSOC` and `OP_PUT_MAP_EXACT` : fix comments that are outdated since we have memory_ensure_free_with_roots

Small fixes to opcodeswitch

---

src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_op_bs_start_match.erl
tests/erlang_tests/test_op_bs_start_match_asm.S
tests/test.c

Fix fail cases in OP_BS_START_MATCH3 & OP_BS_START_MATCH4

---

CHANGELOG.md
src/libAtomVM/opcodesswitch.h
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_bs_start_match_live.erl
tests/test.c

OP_BS_MATCH4: fix preservation of src

---

CMakeModules/BuildErlang.cmake

- add ../include so applications can have includes
- add libs/ so tests can refer to application includes

Improve include search path when compiling Erlang code

---

src/libAtomVM/opcodesswitch.h

Erlang compiler refuses to compile assembly if src is not a match state.
For example:
```
test_op_bs_get_utf8_asm:1: function bs_get_utf8/1+4:
Internal consistency check failed - please report this bug.
Instruction: {test,bs_skip_utf16,
{f,3},
[{x,0},3,{field_flags,[unsigned,big]}]}
Error:       {bad_type,{needed,{t_bs_context,1}},{actual,any}}:
```
So we can assume we always have a match state.

OP_BS_*UTF*: replace VERIFY_IS_MATCH_STATE with asserts

---

CHANGELOG.md
libs/estdlib/src/lists.erl
tests/libs/estdlib/test_lists.erl

Add `lists:keysort/2`

---

src/libAtomVM/opcodesswitch.h

OP_BS_START_MATCH*: only gc if allocating a match state

---

.github/workflows/build-and-test-macos.yaml

macOS CI: set fail-fast to false

---

CMakeModules/FindElixir.cmake

Only search for Elixir once

---

src/libAtomVM/nifs.c

Fix heap calculation in erlang:atom_to_binary/1,2

---

.github/workflows/build-and-test-macos.yaml

Many macOS CI failures seem to come from this test.

macOS CI: implement workaround for random nxdomain issue in net_kernel test

---

CHANGELOG.md
libs/estdlib/src/lists.erl
tests/libs/estdlib/test_lists.erl

Quick sort is way too slow when sorting labels and lines during jit compilation.

Replace quick_sort with merge_sort for lists

---

CHANGELOG.md
libs/estdlib/src/lists.erl
tests/libs/estdlib/test_lists.erl

- `lists:seq(1, 0)` is valid and now returns an empty list
- `lists:seq(1, 0, 1)` is also valid and now returns an empty list

Fix `lists:seq/2,3` when they should return an empty list

---

src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf

Throw undef when the function is called, as it means the NIF was not found.

Implement `erlang:nif_error/1`

---

src/libAtomVM/opcodesswitch.h
tests/erlang_tests/fail_apply_last.erl

Truncate stack only after checking module and function, thus generating a more helpful stacktrace, following what BEAM does.

OP_APPLY_LAST: fix stacktrace on failure

---

src/libAtomVM/memory.c
src/libAtomVM/term.h

Continuation of #1701 
Replace if/elseif with term_is_* functions with a logic based on term type bits.
This has a significant impact on garbage collection performance.

Optimize `memory_scan_and_copy` and `memory_scan_and_rewrite`

---

examples/erlang/disterl.erl
examples/erlang/esp32/epmd_disterl.erl

Fix disterl example: do not start kernel

---

CHANGELOG.md
libs/estdlib/src/erlang.erl
src/libAtomVM/context.c
src/libAtomVM/defaultatoms.def
src/libAtomVM/dist_nifs.c
tests/erlang_tests/test_process_info.erl
tests/libs/estdlib/test_net_kernel.erl

Also add `monitored_by` in `process_info/2` to test this fix
Fix #1782 

Fix leak with disterl monitor by name

---

CHANGELOG.md
src/libAtomVM/opcodesswitch.h

Fix a bug where result of bs_start_match2 and bs_start_match4 could be written at the wrong address if a GC occurred.
Only witnessed with serialized funs PR on armv5/v7

Fix possible memory corruption with OP_BS_START_MATCH{2,4}

---

CHANGELOG.md
src/libAtomVM/context.c
src/libAtomVM/defaultatoms.def

This PR adds a mock implementation for `process_info(Pid, current_stacktrace)`, which always returns an empty list. The OTP calls it in various places and crashes, because the current implementation returns `badarg`. I'd be happy to provide an actual implementation, but, to my knowledge, it's not possible with the current internal API for creating stacktraces.

Add mock implementation for process_info(Pid, current_stacktrace)

---

src/libAtomVM/dist_nifs.c

Fix leak in disterl demonitor

---

src/platforms/emscripten/CMakeLists.txt

Enable stacktraces in WASM by default

---

.clang-format
C_CODING_STYLE.md
src/libAtomVM/posix_nifs.c

clang-format >= 15 has `InsertBraces` option.
Enable it as described in AVMCCS-F002 rule.

.clang-format: enable `InsertBraces` option

---

tests/valgrind-suppressions.sup

Update valgrind suppressions

---

src/libAtomVM/nifs.c

clang-format: fix formatting of nifs.c

---

tests/test.c

Enable forgotten test bs_append_extra_words

---

src/libAtomVM/opcodesswitch.h
tests/erlang_tests/test_op_bs_create_bin.erl
tests/erlang_tests/test_op_bs_create_bin_asm.S

I don't seem to be able to reproduce this with Erlang code, but I have been definitely hit by this bug at some point. The test is written in assembly.

opcodesswitch: fix OP_BS_CREATE_BIN that can have an allocator list

---

.github/workflows/wasm-build.yaml
src/platforms/emscripten/tests/cypress/e2e/websockets.spec.cy.js
src/platforms/emscripten/tests/src/test_websockets.erl
src/platforms/emscripten/tests/src/test_websockets.html

wss://echo.websocket.org works well but is sometimes unavailable from GitHub CI. Replace it with a local docker container that preforms the same echo service, leveraging os:getenv/1 to pass the URL from JS to Erlang.

wasm CI: use docker container instead of flappy remote server

---

CHANGELOG.md
libs/estdlib/src/lists.erl
src/libAtomVM/defaultatoms.def
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_list_to_bitstring.erl
tests/erlang_tests/test_lists_keyfind.erl
tests/erlang_tests/test_lists_keymember.erl
tests/erlang_tests/test_lists_member.erl
tests/test.c

Credit: @FKubisSWM, @TheSobkiewicz

Add some list-related NIFs

---

src/libAtomVM/bif.c
src/libAtomVM/intn.c
src/libAtomVM/intn.h
tests/erlang_tests/bigint.erl
tests/erlang_tests/test_bs_int.erl

Add support for bigint to:
- `bsl`/`bsr`
- `band`/`bor`/`bxor`
- `bnot`
Also `bsl`/`bsr` do not depend anymore or undefined behaviors (and they may raise overflow exception).

Add support for bigint to bitwise BIFs

---

libs/jit/src/jit.erl

JIT: Fix decode_compact_term_integer on 32 bits platforms

---

libs/jit/src/jit.erl

Free Dest register if it is a pointer to an extended VM register.

JIT: free Dest register with OP_BS_GET_POSITION

---

src/libAtomVM/jit.c

PR #1784 and PR#1770 were concurrently merged but unserialization of functions required a change to jit primitives that mirrored the change in opcodesswitch

JIT: Fix unserialization of functions

---

CHANGELOG.md
CMakeLists.txt
src/libAtomVM/CMakeLists.txt
src/libAtomVM/opcodesswitch.h

This PR adds an option to disable process dumps. The problem with process dumps is that they're printed whenever the process exits with a non-standard reason, and this doesn't necessarily mean that the process terminated unexpectedly. For example, some of the Elixir compiler processes exit with `{:ok, atom(), binary()}` and that's the expected behaviour. The OTP relies on the logger to print information about abruptly terminated processes, and so we try to do in Popcorn, thus we need to disable the crash dumps.

Add AVM_PRINT_PROCESS_CRASH_DUMPS option

---

libs/jit/src/jit.erl

Continuation of #1770 
Avoid calls to TERM_COMPARE primitive for comparison with literals in OP_IS_EXACT and OP_IS_NOT_EXACT.
Current benchmark:
|test                 |JIT disabled (c06edb2bca8dacc8c17661575b39bcfc2c5922ea)|HEAD~1, JIT enabled (c06edb2bca8dacc8c17661575b39bcfc2c5922ea)|This PR (9b14b166899f3248189b71c6c157c6ae110df6c4) |
|--------------|---------------- |------------------------|--------|
|erlang-tests   | 11.45s                  |  10.51s                            | 9.95s  |
|benchmark (entire run)                      | 17.03                 |  15.71 (incl. compilation)           | 15.35s
|benchmark : pingpong_speed_test | 3.59s                 |  3.20s                            | 3.23s |
|benchmark : prime_speed_test       |  0.26s                            | 0.21s …

JIT: optimize out calls to term compare

---

libs/jit/src/jit.erl

Continuation of #1770 
Required on platforms with very few registers (armv6m)

JIT: reduce register usage on binary matching

---

libs/estdlib/src/code_server.erl
libs/jit/src/jit.erl
libs/jit/src/jit_precompile.erl
src/libAtomVM/iff.c
src/libAtomVM/iff.h
src/libAtomVM/module.c
src/libAtomVM/module.h
src/libAtomVM/nifs.c
src/libAtomVM/nifs.gperf
tests/erlang_tests/CMakeLists.txt
tests/erlang_tests/test_code_server_nifs.erl
tests/libs/jit/jit_tests.erl
tests/test.c
tools/packbeam/packbeam.c

Continuation of:
-  #1770 
- #1833
First optimization using type information: simplify some term_to_int implementations.
Current benchmark:
|test                 |JIT disabled (c06edb2bca8dacc8c17661575b39bcfc2c5922ea)|HEAD~1, JIT enabled (9b14b166899f3248189b71c6c157c6ae110df6c4)|This PR (b775240224693b873ed69c74f08673e0d30f9ec3) |
|--------------|---------------- |------------------------|--------|
|erlang-tests   | 11.45s                  | 9.95s  | 9.94s |
|benchmark (entire run)                      | 17.03s                 | 15.35s | 15.52s |
|benchmark : pingpong_speed_test | 3.59s                 | 3.23s | 3.38s |
|benchmark : prime_speed_test       |  0.26s                            | 0.17s | 0.17s |
|benchmark : sudoku_solution_test |  0.26s                            | 1.34s | …

JIT: optimize term to int using types

---

.github/workflows/build-and-test-other.yaml

Lately it was randomly failing since it was taking more than 15 minutes. Increase timeout to 30 minutes to make sure it is not cancelled just before completion.

CI: build-and-test-other: increase timeout to 30 minutes

---

libs/jit/src/jit.erl

Continuation of:
- #1848 
Patterns such as:
```erlang
<<"🌑"/utf8, Moons255Str/binary>> = Moons256Str,
```
(as found in test_binary_to_atom)
do match a 32 bits integer in a binary. It is typically encoded by compiler with a 31 bits match followed by a 1 bit match, maybe because of some BEAM optimization (?).
```
{bs_start_match4,{atom,no_fail},1,{x,0},{x,1}}.
{bs_match,{f,27},
{x,1},
{commands,[{ensure_at_least,32,1},
{'=:=',nil,31,2018494024},
{'=:=',nil,1,1}]}}.
```
In our case, if the pattern value is larger than 28 bits, the `?PRIM_BITSTRING_EXTRACT_INTEGER` primitive will return a boxed integer on 32 bits platforms, which we need to unbox for comparison.
If we confirm the compiler always matches up to 31 bits, we could actually optimize this differently, or maybe squash the two.
These …

JIT: Fix binary matching with large integers on 32bits

---

src/libAtomVM/context.c
src/libAtomVM/context.h
src/libAtomVM/opcodesswitch.h

The computed goto is a GCC extension that isn't implemented by clang when targeting wasm. In some cases the compiler failed to optimize it.

Remove unnecessary computed goto

---

libs/jit/src/jit_x86_64.erl

x86-64: fix register exhaustion issue

---

libs/jit/src/jit_x86_64.erl

x86-64: add move_to_native_register/2,3 with {x_reg, extra}

---

libs/jit/src/jit_x86_64.erl

x86-64: add get_array_element with {free, Reg}

---

libs/jit/src/jit.erl

JIT: reduce & fix register usage of OP_BS_GET_BINARY2

---

tests/erlang_tests/CMakeLists.txt

Use full path to fix some random failures with CMake's make generator

JIT: Use full path DEPENDS for jit_precompile

---

CHANGELOG.md
UPDATING.md
src/libAtomVM/nifs.c
tests/erlang_tests/bigint.erl

Make sure that `list_to_integer` / test `integer_to_list` are properly tested and support big integers.

bigint: fix `list_to_integer` / test `integer_to_list`

---

src/libAtomVM/bif.c
src/libAtomVM/term.h

term_is_integer (it checks if an integer can be converted to `avm_int_t`) doesn't match existing naming:
- `term_to_int` (`term` -> `avm_int_t`)
- `term_from_int` (`avm_int_t` -> `term`)
Rename also term_is_pos_integer and similar functions.

Add `term_is_int` as replacement for `term_is_integer`
